lib/rules/no-invalid-v-bind.js

Add sync modifier to v-bind

---

docs/rules/no-reserved-keys.md
lib/rules/no-reserved-keys.js
tests/lib/rules/no-reserved-keys.js

Rename rule `no-reservered-keys` to `no-reserved-keys`.

---

lib/rules/no-multi-spaces.js
tests/lib/rules/no-multi-spaces.js

Fix: "no-multi-spaces" will effect js file and throw a error

---

tools/update-rules.js

Chore: deprecated rule links in readme.md

---

lib/utils/index.js
tests/lib/rules/return-in-computed-property.js

[patch] Ensure that executeOnVueComponent is called after other queries.

---

docs/rules/no-duplicate-attributes.md

Fix typo in docs no-duplicate-attributes

---

lib/rules/require-default-prop.js
tests/lib/rules/require-default-prop.js

Fix eslint crash when using object spread inside prop definition

---

lib/rules/no-dupe-keys.js
tests/lib/rules/no-dupe-keys.js

[Fixes #314] Prevent data leakage in no-dupe-keys rule

---

lib/utils/index.js
tests/lib/rules/no-async-in-computed-properties.js

Fix: no-async-in-computed-properties crash (fixes #390)

---

lib/rules/valid-v-on.js
tests/lib/rules/valid-v-on.js

Fix: valid-v-on false positive (fixes #351)

---

lib/utils/indent-common.js
tests/fixtures/script-indent/export-named-declaration-04.vue
tests/fixtures/script-indent/issue407.vue

Fix: wrong indentation (fixes #407)

---

docs/rules/attributes-order.md

Corrected Spelling.
enfore -> enforce

Spelling correction

---

package.json

Upgrade babel-eslint

---

lib/rules/attributes-order.js

Fixes https://github.com/vuejs/eslint-plugin-vue/issues/432

Include slot-scope in attributes-order

---

lib/rules/require-prop-type-constructor.js
tests/lib/rules/require-prop-type-constructor.js

Fix #560 Allow null in require-prop-type-constructor

---

lib/rules/no-unused-components.js
tests/lib/rules/no-unused-components.js

#598 Ignore templates with src tag in no-unused-components

---

README.md

Old: 
[![NPM version](https://img.shields.io/npm/v/eslint-plugin-vue.svg?style=flat)](https://npmjs.org/package/eslint-plugin-vue) [![NPM downloads](https://img.shields.io/npm/dm/eslint-plugin-vue.svg?style=flat)](https://npmjs.org/package/eslint-plugin-vue) [![CircleCI](https://circleci.com/gh/vuejs/eslint-plugin-vue.svg?style=svg)](https://circleci.com/gh/vuejs/eslint-plugin-vue)
New:
[![NPM version](https://img.shields.io/npm/v/eslint-plugin-vue.svg?style=flat)](https://npmjs.org/package/eslint-plugin-vue) [![NPM downloads](https://img.shields.io/npm/dm/eslint-plugin-vue.svg?style=flat)](https://npmjs.org/package/eslint-plugin-vue) [![CircleCI](https://img.shields.io/circleci/project/github/vuejs/eslint-plugin-vue/master.svg?style=flat)](https://circleci.com/gh/vuejs/eslint-plugin-vue) …

Update shields in readme

---

lib/rules/component-name-in-template-casing.js
tests/lib/rules/component-name-in-template-casing.js

Fix #637 - Don't ignore elements with "is" binding

---

lib/rules/valid-v-model.js
tests/lib/rules/valid-v-model.js

Fixed: `valid-v-model` message #648

---

lib/utils/indent-common.js
tests/lib/rules/html-indent.js

I am very sorry. I accidentally committed to master.
This PR will revert the incorrect commit.
---
This reverts commit 0f27d019e68e49878ef1145ab6d4469ae8401f11.

Revert "Fix: ignore preformatted tokens in `html-indent`"

---

.eslintrc.js
lib/rules/no-async-in-computed-properties.js
lib/rules/prop-name-casing.js
lib/utils/indent-common.js

https://github.com/vuejs/eslint-plugin-vue/pull/659#discussion_r234442576

chore: enable no-mixed-operators to catch potentially harmful expressions

---

lib/rules/no-multi-spaces.js
lib/utils/index.js

The current link points to documentation that was moved. This updates it.

Update "What is the latest version" Warning Link

---

lib/rules/require-default-prop.js
lib/rules/require-valid-default-prop.js
lib/utils/index.js
tests/lib/rules/require-default-prop.js
tests/lib/rules/require-valid-default-prop.js

fix(require-default-prop, require-valid-default-prop): resolve the property name

---

docs/rules/valid-v-slot.md
lib/rules/valid-v-slot.js
tests/lib/rules/valid-v-slot.js

New: valid-v-slot rule (fixes #802)

---

package.json

I have updated `vue-eslint-parser` to avoid the PR issues below.
https://github.com/mysticatea/vue-eslint-parser/pull/44
Please review 🙏

fix: update vue-eslint-parser

---

lib/rules/order-in-components.js

this PR should speed up the node traverse, improves #910

pref: improve traverse

---

.circleci/config.yml
package.json

Fixed jsx parsing error

---

docs/rules/script-indent.md

https://github.com/vuejs/eslint-plugin-vue/issues/987

Typescript doc for vue/html-indent

---

docs/rules/html-closing-bracket-newline.md

- Fix missing word in opening sentence

Update grammar in ESLint documentation

---

.vscode/settings.json
lib/rules/require-default-prop.js
lib/utils/index.js
tests/lib/rules/require-default-prop.js

Fixed an error when using spread elements in `vue/require-default-prop`.

---

docs/rules/README.md
docs/rules/no-deprecated-v-on-native-modifier.md
lib/configs/vue3-essential.js
lib/index.js
lib/rules/no-deprecated-v-on-native-modifier.js
tests/lib/rules/no-deprecated-v-on-native-modifier.js

Add `vue/no-deprecated-v-on-native-modifier` rule

---

docs/rules/README.md
docs/rules/no-deprecated-dollar-listeners-api.md
lib/configs/vue3-essential.js
lib/index.js
lib/rules/no-deprecated-dollar-listeners-api.js
tests/lib/rules/no-deprecated-dollar-listeners-api.js
tests/lib/rules/no-deprecated-events-api.js

Add `vue/no-deprecated-dollar-listeners-api` rule

---

docs/rules/README.md
docs/rules/no-unused-properties.md
lib/index.js
lib/rules/no-unused-properties.js
lib/utils/index.js
tests/lib/rules/no-unused-properties.js

This PR is derived from #871.
This PR change is Vue.js 3.x support and some fixes.
---
close #871
close #631

Add `vue/no-unused-properties` rule (from #871)

---

lib/rules/comma-style.js
tests/lib/rules/comma-style.js

Fixed an error for v-slot in `vue/comma-style` rule.

---

lib/rules/no-unused-properties.js
lib/utils/index.js
tests/lib/rules/no-unused-properties.js

Fixed false positives for render props and template refs in `vue/no-unused-properties` rule.

---

tests/lib/rules/html-indent.js
tests/lib/rules/script-indent.js

Related to https://github.com/vuejs/eslint-plugin-vue/pull/1216#issuecomment-647865394

Fixed CI failing when using ESLint 7.3.

---

docs/rules/no-unsupported-features.md

From https://github.com/vuejs/eslint-plugin-vue/pull/1254/files#diff-86b20cade68a6fa81dfb9c4a6295da05R33

doc(typo): change `v-id` to `v-is`

---

tests/lib/rules/no-side-effects-in-computed-properties.js

Add test for no-side-effects-in-computed-properties rule to check #1282

---

docs/README.md

This will make the tool more interesting for those of us not using `.vue` files yet.

Mention that .js files are linted as well

---

lib/utils/index.js
tests/lib/rules/require-explicit-emits.js
tests/lib/rules/return-in-computed-property.js

Fix false positives for quoted 'emits' in vue/require-explicit-emits rule

---

lib/rules/require-explicit-emits.js
tests/lib/rules/require-explicit-emits.js

Update `vue/require-explicit-emits` rule to support `<script setup>`

---

lib/rules/no-boolean-default.js
tests/lib/rules/no-boolean-default.js

Update `vue/no-boolean-default` rule to support `<script setup>`

---

lib/rules/require-emit-validator.js
tests/lib/rules/require-emit-validator.js

Update `vue/require-emit-validator` rule to support `<script setup>`

---

docs/.vuepress/config.js

Chore: Replace the link to the online demo.

---

lib/rules/no-reserved-keys.js
tests/lib/rules/no-reserved-keys.js

fixed message string

---

lib/rules/no-unused-properties.js
lib/utils/property-references.js
tests/lib/rules/no-unused-properties.js

Fix false positives for toRefs in `vue/no-unused-properties` rule

---

package.json
tests/lib/rules/no-async-in-computed-properties.js

related to #1690
https://github.com/vuejs/vue-eslint-parser/releases/tag/v8.0.1

Upgrade vue-eslint-parser to use patch.

---

lib/utils/style-variables/index.js

Fix memory leak

---

lib/rules/component-api-style.js
tests/lib/rules/component-api-style.js

Fix crash in `component-api-style` rule

---

lib/rules/no-dupe-keys.js
tests/lib/rules/no-dupe-keys.js

Allow `asyncData` in `vue/no-dupe-keys`

---

lib/rules/valid-next-tick.js
tests/lib/rules/valid-next-tick.js

Skip conditional expressions in `vue/valid-next-tick`

---

docs/rules/no-boolean-default.md
docs/rules/prefer-true-attribute-shorthand.md
docs/rules/require-default-prop.md

Link to related rules in docs

---

docs/rules/match-component-import-name.md

Fix interactive example in docs for `vue/match-component-import-name`

---

docs/rules/no-required-prop-with-default.md

Follow-up to #1943 and  #2002.
CC @neferqiqi

Fix `vue/no-required-prop-with-default` docs

---

lib/rules/order-in-components.js
tests/lib/rules/order-in-components.js

Add support for `defineOptions` to `vue/order-in-components` rule

---

package.json

https://github.com/vuejs/vue-eslint-parser/releases/tag/v9.3.0

Upgrade to vue-eslint-parser v9.3 that supports Vue 3.3.

---

docs/rules/multi-word-component-names.md
docs/rules/no-reserved-component-names.md

Document related rules for component name rules

---

lib/rules/html-self-closing.js
tests/lib/rules/html-self-closing.js

Ignore blocks in `vue/html-self-closing`

---

docs/rules/index.md
docs/rules/no-deprecated-model-definition.md
lib/index.js
lib/rules/no-deprecated-model-definition.js
tests/lib/rules/no-deprecated-model-definition.js

Add `vue/no-deprecated-model-definition` rule

---

eslint-internal-rules/no-invalid-meta-docs-categories.js
eslint.config.js
lib/processor.js
lib/rules/attributes-order.js
lib/rules/block-lang.js
lib/rules/block-tag-newline.js
lib/rules/comment-directive.js
lib/rules/define-emits-declaration.js
lib/rules/define-props-declaration.js
lib/rules/html-closing-bracket-newline.js
lib/rules/html-self-closing.js
lib/rules/multiline-html-element-content-newline.js
lib/rules/no-boolean-default.js
lib/rules/no-extra-parens.js
lib/rules/no-multiple-template-root.js
lib/rules/no-restricted-props.js
lib/rules/no-unused-components.js
lib/rules/no-unused-properties.js
lib/rules/require-default-prop.js
lib/rules/require-prop-comment.js
lib/rules/require-valid-default-prop.js
lib/rules/this-in-template.js
lib/rules/v-on-handler-style.js
lib/rules/v-slot-style.js
lib/utils/indent-common.js
lib/utils/index.js
lib/utils/property-references.js
lib/utils/selector.js
lib/utils/ts-utils/ts-ast.js

Enable more `eslint-plugin-unicorn` rules

---

package.json

Bump dependencies to latest version

---

lib/rules/require-toggle-inside-transition.js
tests/lib/rules/require-toggle-inside-transition.js

Fixed false negatives for whitespace in `vue/require-toggle-inside-transition` rule

---

lib/configs/vue3-strongly-recommended.js
lib/rules/v-on-event-hyphenation.js
tests/lib/configs/configs.js

Fixed broken config of `plugin:vue/vue3-strongly-recommended`

---

lib/utils/ref-object-references.js

I realized that I had left a unnecessary code behind, so I'll remove it in this PR.

Remove unnecessary code

---

lib/rules/no-undef-properties.js
tests/lib/rules/no-undef-properties.js

Fix false positives for `defineModel` in `vue/no-undef-properties` rule

---

package.json

Chore: upgrade vue-eslint-parser to v9.4.2

---

lib/rules/no-useless-v-bind.js
tests/lib/rules/no-useless-v-bind.js

fix(no-useless-v-bind): remove spaces around string in fixes

---

lib/rules/v-bind-style.js
tests/lib/rules/v-bind-style.js

fix https://github.com/vuejs/eslint-plugin-vue/issues/2409

fix(v-bind-style): only change kebabCase to camelCase

---

docs/.vitepress/config.mts

| Before | After |
| ------ | ----- |
| ![grafik](https://github.com/vuejs/eslint-plugin-vue/assets/202916/3cebbc38-262e-4e51-924f-595ce093fb91) | ![grafik](https://github.com/vuejs/eslint-plugin-vue/assets/202916/c4af1d53-8fb2-4e09-ba61-842bb5ad6887) |
See documentation: https://vitepress.dev/reference/default-theme-config#outline

Show nested outline in docs

---

lib/rules/require-toggle-inside-transition.js
tests/lib/rules/require-toggle-inside-transition.js

feat(require-toggle-inside-transition): check directive

---

lib/rules/no-setup-props-reactivity-loss.js
tests/lib/rules/no-setup-props-reactivity-loss.js

Keen for feedback 🫡 , fix #2470

fix(no-setup-props-reactivity-loss): report template literal

---

docs/rules/index.md
docs/rules/no-computed-properties-in-data.md
docs/rules/prefer-define-options.md
eslint.config.js
lib/rules/no-computed-properties-in-data.js
lib/rules/prefer-define-options.js

Enforced via https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-description.md

Remove trailing period in rule descriptions

---

lib/rules/require-typed-object-prop.js
tests/lib/rules/require-typed-object-prop.js

Exclude JavaScript components in `vue/require-typed-object-prop`

---

docs/user-guide/index.md

doc: add  example for Vue class component

---

lib/rules/custom-event-name-casing.js
tests/lib/rules/custom-event-name-casing.js

fix(custom-event-name-casing): check defineEmits variable name in template

---

package.json

* Fixes #2618.
* https://github.com/eslint-stylistic/eslint-stylistic/pull/617 was merged and released as https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v2.12.0.

Update @stylistic/eslint-plugin to v2.12.0

---

docs/rules/index.md
tools/update-docs-rules-index.js

by using Markdown link definitions

Improve rules docs source readability

---

lib/index.d.ts
lib/index.js
tools/update-lib-index.js

Resolve the remaining todo in the code base.
Will added to #2166.

Remove setup-compiler-macros environments

---

lib/rules/prefer-use-template-ref.js
tests/lib/rules/prefer-use-template-ref.js

This PR fixes #2635 and add test for it.

fix(prefer-use-template-ref): fix crash when use non-block setup function

---

docs/rules/index.md
docs/rules/no-implicit-coercion.md

Update `vue/no-implicit-coercion` rule docs

---

docs/user-guide/index.md
lib/configs/base.js
lib/configs/flat/base.js
package.json
tools/update-lib-configs.js
tools/update-lib-flat-configs.js

Reverts vuejs/eslint-plugin-vue#2672

Revert "Remove globals from config"

---

package.json

This PR upgrades vue-eslint-parser to v10.

Upgrade vue-eslint-parser to v10

---

docs/rules/prefer-true-attribute-shorthand.md
lib/rules/prefer-true-attribute-shorthand.js
tests/lib/rules/prefer-true-attribute-shorthand.js

feat(prefer-true-attribute-shorthand): add `except` option

---

lib/rules/html-self-closing.js

Better report location for `vue/html-self-closing`

---

lib/rules/require-default-prop.js
tests/lib/rules/require-default-prop.js

fix(require-default-prop): report props destructure

---

tests/lib/rules/eqeqeq.js

See https://github.com/vuejs/eslint-plugin-vue/actions/runs/15012909073/job/42184802441

chore: fix ci error in eqeqeq

---

tests/lib/rules/key-spacing.js

- #2793
---
This PR converts all error assertions for `key-spacing` to include both error message and full location checks.

test(key-spacing): make tests more strict

---

tests/lib/rules/no-deprecated-data-object-declaration.js

- #2793
---
This PR converts all error assertions for `no-deprecated-data-object-declaration` to include both error message and full location checks.

test(no-deprecated-data-object-declaration): make tests more strict
