vuejs/eslint-plugin-vue

- index.js
- package.json
> Upgrade eslint-plugin-html

- README.md
If you're using other configs, inserting eslint-config-vue might add too much noise.
There is only one rule added by this plugin, we could show how to use it and _optionally_ extend the recommended vue rules.
> Note that eslint-config-vue is optional.

- README.md
As we discussed I added `attention` section that explains what is currently on master branch, so that no one will be confused that what he installed is not relevant with the docs.
> Add "attention" section about beta release

- lib/rules/html-no-self-closing.js
- tests/lib/rules/html-no-self-closing.js
There's a small typo on `html-no-self-closing` rule, `shuld` => `should`
> Fix Should typo

- lib/config/base.js
Fixes #30.
This PR ensures that this plugin uses correct `vue-eslint-parser` even if modules are not flatten.
> Fix: more robust parser setting (fixes #30)

- .github/ISSUE_TEMPLATE.md
I created the issue template based on [ESLint's issue template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE.md).
I expect that the issue template helps us to get information what we need to investigate bugs.
> Chore: add issue template

- lib/utils/index.js
Related to #35. Tested on Atom editor and on CLI, fixes Atom issue and no changes on CLI.
> Changing console.assert to node assert

- README.md
- docs/rules/order-in-components.md
- lib/recommended-rules.js
- lib/rules/order-in-components.js
- package-lock.json
- package.json
- tests/lib/rules/order-in-components.js
This PR adds new rule regarding this proposition: #13 
This rule will be applied on:
- `export default {}` inside `.vue` and `.jsx` files
- `new Vue({})` in any file
- `Vue.component('xxx', {})` or `component('xxx', {})` in any file
Thing to be noted - we won't support dynamically loaded components, as it's not so obvious to tell if it actually is or is not a vue component.
> New rule `order-in-components`

- package-lock.json
- package.json
- tests/lib/rules/no-parsing-error.js
Fixes #51, fixes #52, fixes #55.
This PR upgrades `vue-eslint-parser` to fix several issues.
- https://github.com/mysticatea/vue-eslint-parser/commit/65a673a23fdaa36b7fd76163ba8ca187f5e60379 fixed crash if foreign attributes exist. Thank you, @benjarwar!
- https://github.com/mysticatea/vue-eslint-parser/commit/8168db16df3eaa327bacded0f244f0565b563a0f fixed crash if `<tbody>`/`<thead>` elements are omitted.
> Fix: upgrade vue-eslint-parser (fixes #51, fixes #52, fixes #55)

- docs/rules/no-confusing-v-for-v-if.md
- docs/rules/no-invalid-template-root.md
- docs/rules/no-invalid-v-bind.md
- docs/rules/no-invalid-v-cloak.md
- docs/rules/no-invalid-v-else-if.md
- docs/rules/no-invalid-v-else.md
- docs/rules/no-invalid-v-for.md
- docs/rules/no-invalid-v-html.md
- docs/rules/no-invalid-v-if.md
- docs/rules/no-invalid-v-model.md
- docs/rules/no-invalid-v-on.md
- docs/rules/no-invalid-v-once.md
- docs/rules/no-invalid-v-pre.md
- docs/rules/no-invalid-v-show.md
- docs/rules/no-invalid-v-text.md
- lib/rules/no-invalid-template-root.js
- tests/lib/rules/no-invalid-template-root.js
Fixes #41.
This PR removes the warnings about empty templates.
> Fix: `no-invalid-template-root` has false positive about empty templates (fixes #41)

- README.md
- lib/recommended-rules.js
- lib/rules/html-no-self-closing.js
> Disable "html-no-self-closing" rule in recommended configuration (Resolves #48)

- docs/rules/no-invalid-v-on.md
- lib/rules/no-invalid-v-on.js
- tests/lib/rules/no-invalid-v-on.js
Fixes #49.
This PR fixes false positive of `no-invalid-v-on` rule.
If a `v-on` directive has verb modifiers (`.stop` or `.prevent`), now that rule allow the directive even if it does not have attribute values.
> Fix: allow `v-on` without attribute values if it has verb modifiers (fixes #49)

- lib/rules/order-in-components.js
Rule `vue/order-in-components` throws eslint rule schema validation error on custom order
bacause is missing schema definition
issue: #73
> Add missing schema to rule order-in-components

- README.md
- lib/utils/index.js
This PR adds FAQ about "Use the latest vue-eslint-parser" errors.
Also, the error message points that.
Please check this description is enough or not.
> Docs: add FAQ about vue-eslint-parser

- lib/rules/no-invalid-v-on.js
- tests/lib/rules/no-invalid-v-bind.js
- tests/lib/rules/no-invalid-v-on.js
> Add support for v-on="$listeners" (#89)

- docs/rules/return-in-computed-property.md
- lib/rules/return-in-computed-property.js
- tests/lib/rules/return-in-computed-property.js
This PR implements rules proposed in #75
**DONE:**
> Add `return-in-computed-property` rule.

- docs/rules/no-async-in-computed-properties.md
- lib/rules/no-async-in-computed-properties.js
- lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/no-async-in-computed-properties.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
This PR implements rules proposed in #53 
**DONE:**
> Add `no-async-in-computed-properties` rule

- docs/rules/no-shared-component-data.md
- lib/rules/name-property-casing.js
- lib/rules/no-async-in-computed-properties.js
- lib/rules/no-shared-component-data.js
- lib/rules/no-side-effects-in-computed-properties.js
- lib/rules/order-in-components.js
- lib/rules/return-in-computed-property.js
- lib/utils/index.js
- tests/lib/rules/no-shared-component-data.js
This PR implements rules proposed in #79 
**DONE:**
**Importnant:**
This rule splits `executeOnVueComponent` into `executeOnVueInstance` and `executeOnVueComponent` and adds alias `executeOnVue`
- if you want to process only Vue components use `utils.executeOnVueComponent`
- if you want to process only `new Vue` use `utils.executeOnVueInstance`
- If you want to process both use `utils.executeOnVue`
> Add `no-shared-component-data` rule.

- lib/rules/name-property-casing.js
- lib/utils/casing.js
- tests/lib/utils/casing.js
Currently if there is any `number` in component name it will trigger error.
I decided to move casing functions to separate file because there is going to ba at-least 2-3 more rules witch are going to use same behavior, and i was able to write tests for it.
> Allow to use numbers in component names

- docs/rules/no-parsing-error.md
- lib/rules/html-end-tags.js
- lib/rules/html-no-self-closing.js
- lib/rules/no-confusing-v-for-v-if.js
- lib/rules/no-invalid-template-root.js
- lib/rules/no-invalid-v-else-if.js
- lib/rules/no-invalid-v-else.js
- lib/rules/no-invalid-v-for.js
- lib/rules/no-invalid-v-if.js
- lib/rules/no-invalid-v-model.js
- lib/rules/no-parsing-error.js
- lib/rules/no-template-key.js
- lib/rules/no-textarea-mustache.js
- lib/rules/require-component-is.js
- lib/rules/require-v-for-key.js
- lib/utils/index.js
- package-lock.json
- package.json
- tests/lib/rules/no-invalid-template-root.js
- tests/lib/rules/no-parsing-error.js
Thank you for waiting!
I have almost done to rewrite `vue-eslint-parser`. :sparkles: 
- This PR should fix three bugs: fixes #36, fixes #56, fixes #96.
- This PR enhances `no-parsing-errors` rule. It allows us to catch syntax errors of HTML. Those are opt-in for now since enhancement which increases errors is a breaking change.
- There are some changes to internal API.
- I changed AST of `<template>` a bit. Notable changes are below:
- We can get element names with `element.name` property now. It was `element.startTag.id.name` before. 
- We can get the namespace of elements with `element.namespace`. The value of namespaces are defined in [there](https://infra.spec.whatwg.org/#namespaces).
- `VOnExpression` node is added in order to handle #96 correctly.
- The spec of AST is …
> Update: upgrade vue-eslint-parser (fixes #36, fixes #56, fixes #96)

- docs/rules/require-prop-types.md
- lib/rules/name-property-casing.js
- lib/rules/require-prop-types.js
- lib/utils/index.js
- tests/lib/rules/require-prop-types.js
- tests/lib/utils/index.js
This PR implements rules proposed in #19
**DONE:**
> Add `require-prop-types` rule.

- docs/rules/no-dupe-keys.md
- docs/rules/no-reservered-keys.md
- lib/rules/no-dupe-keys.js
- lib/rules/no-reservered-keys.js
- lib/utils/index.js
- lib/utils/vue-reserved.json
- package-lock.json
- tests/lib/rules/no-dupe-keys.js
- tests/lib/rules/no-reservered-keys.js
- tests/lib/utils/index.js
This PR implements rules proposed in #86
**DONE:**
> Add rules: `no-dupe-keys` and `no-reserved-keys`

- lib/rules/html-no-self-closing.js
- lib/utils/index.js
- lib/utils/svg-elements.json
**Old:**
- `isHtmlElementName(string)`
- `isSvgElementName(string)`
**New:**
- `isKnownHtmlElementNode(ASTNode)`
- `isSvgElementNode(ASTNode)`
- `isMathMLElementNode(ASTNode)`
and broken / deprecated / unused `getTemplateBodyTokenStore` is removed in this commit
> Add namespace check of svg & mathML instead of tag names

- docs/rules/attribute-hyphenation.md
- lib/rules/attribute-hyphenation.js
- package-lock.json
- package.json
- tests/lib/rules/attribute-hyphenation.js
This PR implements rules proposed in #92
**TODO:**
This PR contains changes proposed in #120 and should be merged after it.
> Add rule `attribute-hyphenation`.

- docs/rules/require-render-return.md
- lib/rules/require-render-return.js
- lib/rules/return-in-computed-property.js
- lib/utils/index.js
- tests/lib/rules/require-render-return.js
- tests/lib/rules/return-in-computed-property.js
This PR implements rules proposed in #107
**DONE:**
fixes #107
> Add rule `require-render-return`.

- .eslintignore
- package-lock.json
- package.json
- tests/lib/rules/no-invalid-v-text.js
This PR fixes #125.
New `vue-eslint-parser` has not defined `parserServices` if the source code is not Vue.js SFC. But rules require it.
I fixed it and added some tests.
> [diff of vue-eslint-parser](https://github.com/mysticatea/vue-eslint-parser/compare/v2.0.0-beta.4...master?w=1)
> Fix: parserServices must exist always (fixes #125)

- lib/rules/require-render-return.js
- lib/rules/return-in-computed-property.js
- lib/utils/index.js
- tests/lib/rules/require-render-return.js
- tests/lib/rules/return-in-computed-property.js
> Fix issue return in computed properties & render to match only corret nodes

- README.md
- lib/utils/index.js
- tests/lib/utils/vue-component.js
> Allow to use @vue/component to set enable parsing vue objects

- package.json
Fixes #134.
This PR fixes the problem that `eslint-plugin-vue` does not work on ESLint 4.4.0 because it has changed a private API that `vue-eslint-parser` depends on.
Diff:
- https://github.com/mysticatea/vue-eslint-parser/commit/40f48bec8ab1d4d2532f677dcca679514451872b
> The root cause is that `vue-eslint-parser` depends on a private API in order to traverse `<template>` separately from the main traversing, but I cannot solve the problem for now.
> Fix: support ESLint 4.4.0 (fixes #134)

- lib/rules/require-valid-default-prop.js
- tests/lib/rules/require-valid-default-prop.js
- Improve coverage for FunctionExpression and ArrowFunctionExpression
- Fix traversing over many types (return -> continue)
> Fix small mistake in `require-valid-default-prop`

- docs/rules/no-multi-spaces.md
- lib/rules/no-multi-spaces.js
- package.json
- tests/lib/rules/no-multi-spaces.js
This PR implement rule proposed in #133
> Add "no-multi-spaces" rule (fixes #133)

- lib/rules/order-in-components.js
- lib/utils/index.js
- tests/lib/rules/html-end-tags.js
- tests/lib/rules/name-property-casing.js
- tests/lib/rules/no-async-in-computed-properties.js
- tests/lib/rules/no-dupe-keys.js
- tests/lib/rules/no-reservered-keys.js
- tests/lib/rules/no-shared-component-data.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/order-in-components.js
- tests/lib/rules/require-prop-types.js
- tests/lib/rules/require-render-return.js
- tests/lib/rules/require-valid-default-prop.js
- tests/lib/rules/valid-v-for.js
Fix issues with trying to access undefined properties
- `Cannot read property 'type' of null` when `return` has no argument
Improvements:
- `iterateProperties` - utils
- `checkOrder` - order-in-components
- `getComputedProperties` - utils
- `iterateFunctionExpression` - utils
- add more tests
This changes provide spread operator support support for all rules.
> Improve support for spread operator

- lib/utils/index.js
- tests/lib/utils/vue-component.js
This PR adds support for `Vue.mixin` and treat it as components
fixes #136 
pointed out in [chat.vuejs.org](http://chat.vuejs.org)
> Treat Vue.mixin as components

- docs/rules/no-this-in-template.md
- lib/rules/no-this-in-template.js
- tests/lib/rules/no-this-in-template.js
> Add `no-this-in-template` rule.

- lib/rules/no-shared-component-data.js
- tests/lib/rules/no-shared-component-data.js
> Fix 'no-shared-component-data' false positive when using arrow functions

- docs/rules/require-default-prop.md
- lib/rules/require-default-prop.js
- tests/lib/rules/require-default-prop.js
This PR implements `require-default-prop` rule, that was proposed in #122.
cc @armano2
> Add "require-default-prop" rule (fixes #122)

- docs/rules/no-this-in-template.md
- docs/rules/require-render-return.md
- docs/rules/this-in-template.md
- lib/rules/no-this-in-template.js
- lib/rules/this-in-template.js
- lib/utils/js-reserved.json
- package.json
- tests/lib/rules/no-this-in-template.js
- tests/lib/rules/this-in-template.js
> Rename and add options to `this-in-template`.

- lib/rules/valid-v-for.js
- tests/lib/rules/valid-v-for.js
Fix #164, don't report error when nested v-for refers iterator.
Do report error when nested v-for doesn't refer iterator.
Supersede #167
> polish template v-for error report

- docs/rules/this-in-template.md
Corrects the example in the `this-in-template` doc
> Corrected example code for this-in-template

- package.json
- tests/lib/rules/valid-template-root.js
Fixes #165.
I updated `vue-eslint-parser` to ignore PUG template: https://github.com/mysticatea/vue-eslint-parser/commit/4b264ad8b94599822c09855ac0d0db7dad28db55
This PR applies the patch to this plugin.
> Fix: ignore PUG (fixes #165)

- docs/rules/max-attributes-per-line.md
The first value of the array is expected to be the severity.
Keys must be in double quotes.
> Fix max-attributes-per-line example json configuration

- .editorconfig
- README.md
- docs/rules/html-self-closing.md
- docs/rules/max-attributes-per-line.md
- docs/rules/no-dupe-keys.md
- docs/rules/no-parsing-error.md
- docs/rules/no-reserved-keys.md
- docs/rules/no-reservered-keys.md
- docs/rules/order-in-components.md
- docs/rules/return-in-computed-property.md
Some minor enhancements in consistency and tidying up a little bit. I hope such pull requests are ok.
> Tidying up

- docs/rules/html-end-tags.md
- lib/rules/html-end-tags.js
- tests/lib/rules/html-end-tags.js
> html-end-tags: don't fail for self-closing elements

- docs/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
fixes #100 
almost finished.:)
I'm not very familiar with the ASTs, so please let me know if missing something.
> New: no-unused-vars (fixes #100).

- lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
> (fixes #230) Fix assignment check in `no-side-effects-in-computed-property`

- docs/rules/html-end-tags.md
> Update html-end-tags doc

- README.md
I think the `essential` rules make the most sense as a default implied recommendation, as they're the most universally useful, without anything opinionated.
I also updated the comments slightly and commented out the base config and example rule, so that users blindly copying and pasting don't add anything unnecessary. Without it commented out, some users may also assume that `eslint:recommended` is required for the plugin to work.
> Update example config to use essential rules

- docs/rules/html-indent.md
Cross-reference: https://github.com/vuejs/eslint-plugin-vue/pull/205#issuecomment-344459432
> Adjust html-indent default doc to reflect 0a1237b

- docs/rules/valid-v-model.md
- lib/rules/valid-v-model.js
- tests/lib/rules/valid-v-model.js
> [Fixes #238] Don't report dynamic types on inputs with v-model directive

- lib/rules/valid-v-model.js
- tests/lib/rules/valid-v-model.js
> [Fixes #240] Fix `valid-v-model` rule

- lib/rules/valid-v-on.js
https://vuejs.org/v2/guide/events.html#exact-Modifier
> Added exact as valid modifier

- README.md
This PR adds a link to the playground. I expect this to help potential users to try this plugin quickly.
> Docs: add playground link

- lib/rules/html-end-tags.js
- lib/rules/html-self-closing.js
- lib/utils/index.js
- tests/lib/rules/html-end-tags.js
- tests/lib/rules/html-self-closing.js
This PR fixes #268 and some similar cases:
- [Case 1](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PjwhLS1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwicnVsZXMiOnsidnVlL2h0bWwtZW5kLXRhZ3MiOjIsInZ1ZS9uby1wYXJzaW5nLWVycm9yIjoyfX0=)
- [Case 2](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxzdmc+XG4gICAgICA8IVtDREFUQVt0ZXN0XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsInJ1bGVzIjp7InZ1ZS9odG1sLWVuZC10YWdzIjoyLCJ2dWUvbm8tcGFyc2luZy1lcnJvciI6Mn19)
- [Case 3](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDwhLS1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwicnVsZXMiOnsidnVlL2h0bWwtZW5kLXRhZ3MiOjIsInZ1ZS9uby1wYXJzaW5nLWVycm9yIjoyfX0=)
- [Case …
> [Fix] Incorrect errors in invalid EOF cases (fixes #268)

- lib/rules/html-end-tags.js
- lib/rules/html-quotes.js
- lib/rules/html-self-closing.js
- lib/utils/index.js
- tests/lib/rules/html-end-tags.js
- tests/lib/rules/html-quotes.js
- tests/lib/rules/html-self-closing.js
This PR makes `vue/html-quotes` rule fixable. If the quotes exist in the attribute value, the rule replaces those quotes by HTML entities.
This PR includes #274 to address invalid EOF.
> [Update] Make `vue/html-quotes` fixable

- lib/rules/mustache-interpolation-spacing.js
- tests/lib/rules/mustache-interpolation-spacing.js
This PR improves the range of `vue/mustache-interpolation-spacing` errors.
It's currently:
> ![image](https://user-images.githubusercontent.com/1937871/33514382-5ee5082a-d796-11e7-9167-1565c303c360.png)
> [Playground](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuXHQ8ZGl2Pnt7Zm9vfX08L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJydWxlcyI6eyJ2dWUvbXVzdGFjaGUtaW50ZXJwb2xhdGlvbi1zcGFjaW5nIjoyfX0=)
I feel that this is confused a bit because the editor indicates that the errors exist on the identifier `foo`. (As a side note, this demo's editor is same as VSCode's, [Microsoft/monaco-editor](https://github.com/Microsoft/monaco-editor).) So I changed the range of the errors by:
> ![image](https://user-images.githubusercontent.com/1937871/33514413-f4e68768-d796-11e7-91c9-abfa31695d5f.pn …
> [Update] Improve the range of `mustache-interpolation-spacing`

- lib/rules/no-shared-component-data.js
- tests/lib/rules/no-shared-component-data.js
This PR makes `vue/no-shared-component-data` fixable. The autofix wraps the `data` property's value by a function expression.
At first glance, the unit tests make wrong indentations, but this is intentional. This strategy is same as core rules; one rule does one thing. A combination of rules will make correct autofix.
> [Update] Make `vue/no-shared-component-data` fixable

- circle.yml
- eslint-internal-rules/consistent-docs-description.js
- lib/rules/name-property-casing.js
- lib/rules/no-confusing-v-for-v-if.js
- lib/rules/no-dupe-keys.js
- lib/rules/no-multi-spaces.js
- lib/rules/no-shared-component-data.js
- lib/rules/require-default-prop.js
- lib/rules/require-prop-types.js
- lib/rules/require-render-return.js
- lib/rules/return-in-computed-property.js
- lib/rules/v-bind-style.js
- lib/rules/v-on-style.js
- lib/rules/valid-v-for.js
- lib/rules/valid-v-model.js
- lib/utils/index.js
- package.json
- tests/lib/rules-without-vue-eslint-parser.js
- tools/update-rules.js
Fixes #213.
It intended to show the message "Use the latest vue-eslint-parser", but it crashes.
This PR fixes the crash and adds tests to check that rules don't crash with `babel-eslint`.
> [Fix] Crash with babel-eslint

- lib/rules/html-indent.js
- tests/lib/rules/html-indent.js
Fixes #241.
This PR fixes `vue/html-indent` rule about comments.
If the next token of a comment is the following tokens, the rule allows the indentation of comments at either the same as the next line or the previous line. If neither, the rule auto-fixes the indentation of comments to the same as the previous line.
- `HTMLEndTagOpen` (e.g. `</div`)
- `VExpressionEnd` (`}}`)
- `}`
- `]`
- `)`
> Fix: html-indent about comments (fixes #241)

- lib/rules/html-indent.js
- tests/lib/rules/html-indent.js
Fixes #264.
This PR fixes `vue/html-indent` rule about the indentation of binary expressions.
Before, the second line of binary expressions always has 1 indent from the first line.
After this PR, the second line of binary expressions has the same indentation as the first line in *except* the following cases:
- The first token of the binary expression is on the same line as the previous token.
```js
{
foo: a
+ b
}
```
- The first token of the binary expression is the first token of the statement.
```js
a
+ b
```
EDIT: additionally:
- The first token of the binary expression is the first token of an argument of `CallExpression`/`NewExpression`.
```js
foo(
a
+ b,
c
+ d
)
```
- The first token of the binary expression is the first token of an element of `ArrayExpression`.
```js
[
a
+ b,
c
+ d …
```
> Fix: html-indent about binary expressions (fixes #264)

- docs/rules/html-self-closing.md
`vue/html-self-closing` must be used as a key in the eslint config to
make it work correctly. Also this is consitent with the example json for
other rules.
> Fix html-self-closing example json

- lib/index.js
- package.json
Swap out `requireindex` dependency with the more recently updated
dependency `require-all`. The old dependency uses deprecated API that
breaks when running in a Jest testing environment.
Fixes #290
> chore(package): Swap out `requireindex`

- README.md
- docs/rules/html-quotes.md
- docs/rules/max-attributes-per-line.md
- docs/rules/no-shared-component-data.md
This PR:
- updates default settings in `max-attributes-per-line` rule documentation to be aligned with actual implementation and style guide
- updates `no-shared-component-data` and `html-quotes` docs, so it's clear they're also fixable
> [Fixes #300] Update docs

- docs/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
This PR fixes `no-unused-vars` rule, so it doesn't throw a warning, when some of the properties are not used even when the last property was used.
As pointed in #294 currently code like this throws warnings:
```html
<template>
<div v-for="(v, i, c) in foo">{{c}}</div>
</template>
```
In this PR I'm checking if the last property was referenced anywhere. If yes then we simply ignore other properties, if not -> we check references of all properties as before.
> [Fixes #294] Fix no-unused-vars rule

- lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
This PR updates REGEX to check whether `this.xxx` haven't been used as an argument in an expression. If yes - don't throw a warning.
> [Fixes #306] Update REGEX in no-side-effects-in-computed-properties

- package.json
This PR upgrades `vue-eslint-parser` to the latest version. I have dropped `-beta` postfix.
> Chore: upgrade vue-eslint-parser

- docs/rules/html-indent.md
- lib/rules/html-indent.js
- tests/lib/rules/html-indent.js
As pointed in #293 currently indent rule requires attributes to be aligned as the first one:
```html
<div id="foo"
class="abc"
style="font-color: red;"
>
</div>
```
It's not that common I think, and most people prefer to use it like this:
```html
<div id="foo"
class="abc"
style="font-color: red;"
>
</div>
```
This PR updates indent rule to force the second version.
Though I'm thinking whether we shouldn't add an optional setting to make it possible to align to the first token if needed.
What do you think guys? @mysticatea @chrisvfritz
> [Fixes #293] Update indent rule

- README.md
- docs/rules/html-closing-bracket-newline.md
- lib/rules/html-closing-bracket-newline.js
- tests/lib/rules/html-closing-bracket-newline.js
This PR adds a new rule to enforce the location of closing brackets `>` of HTML tags.
> [New] Add `html-closing-bracket-newline` (fixes #169)

- README.md
- docs/rules/html-closing-bracket-spacing.md
- lib/rules/html-closing-bracket-spacing.js
- tests/lib/rules/html-closing-bracket-spacing.js
Fixes #229.
This PR adds `vue/html-closing-bracket-spacing` rule. This is the spacing style version of #190. It requires or disallows a space before tag's closing brackets.
> New: html-closing-bracket-spacing rule (fixes #229)

- lib/rules/require-prop-types.js
- tests/lib/rules/require-prop-types.js
> [Fixes #315] Report missing prop types only for assigned arrays and objects

- README.md
- docs/rules/comment-directive.md
- lib/base-rules.js
- lib/essential-rules.js
- lib/index.js
- lib/processor.js
- lib/recommended-rules.js
- lib/rules/comment-directive.js
- lib/strongly-recommended-rules.js
- tests/lib/rules/comment-directive.js
Fixes #260.
This PR adds supports of directive comments in `<template>`:
- ``
- ``
- ``
- ``
The mechanism is:
1. `vue/directive-comment` rule reports those comments.
2. The post-processor of this plugin removes `vue/directive-comment` errors and the reported errors in disabled areas.
This PR adds `vue/directive-comment` rule to `base` category, but the rule doesn't report any errors (as more exact, all `vue/directive-comment` errors are removed in post-process), so it doesn't break user's CI builds.
> New: directive comments (fixes #260)

- lib/rules/comment-directive.js
- tests/lib/rules/comment-directive.js
`` was parsed to `` (i.e. disable 2 rules `-line` and `foo` after the comment) wrongly. This PR fixes the bug -- it requires one or more spaces between `eslint-disable` and the first rule name.
This is a bug fix which increases warnings, so needs `semver-minor`.
> Fix: unintentional disabling

- lib/utils/indent-common.js
- tests/fixtures/html-indent/solo-html-comment-01.vue
- tests/lib/rules/html-indent.js
Fixes #330.
This PR includes #309 to avoid confliction.
This PR changes the indentation of comments. If it detects solo comment (the next token is closing token and primary expected indentation and secondary expected indentation are same), then makes +1 indentation for the comment. See https://github.com/vuejs/eslint-plugin-vue/pull/333/commits/7fd45c4ae3ce741ed99d0d4000316ca5e39d48e5 for details.
This change needs `semver-minor` because it's a bug fix which can increase warnings.
> Fix: `html-indent` for solo comment (fixes #330)

- docs/rules/order-in-components.md
Because the instructions say these options should be added to the `.eslintrc` file the format must be JSON. Therefore I have added the missing quotes in the snippet. Hope this is OK, (my first PR).
> fixed a JSON formatting error in the options example

- lib/utils/indent-common.js
- tests/lib/rules/html-indent.js
Fixes #365.
`<pre>` element reserves whitespaces in itself, so `html-indent` rule shouldn't change those whitespaces.
This PR fixes `html-indent` rule to ignore inside of `<pre>` elements.
> Fix: vue/html-indent ignores `<pre>` (fixes #365)

- README.md
- lib/utils/index.js
- tests/lib/utils/vue-component.js
#319
This PR adds support for detecting `Vue.extend` as components, also it adds missing information about `Vue.mixin` in readme.
Unfortunately I think it should be merged once we're ready to release new major version, as it might potentially break some CI builds.
> [Fixes #319] Add Vue.extend support

- docs/rules/no-multi-spaces.md
Simple wording change `witch` -> `which`.
> Fixes wording in docs

- lib/utils/indent-common.js
- tests/fixtures/script-indent/no-linebreak-script.vue
Fixes #367.
This PR fixes the bug that `vue/script-indent` rule removes the first `<script>` tag if there is no line terminator after the tag: [online demo](https://mysticatea.github.io/vue-eslint-demo/#eJw1jUEKwjAURK8is44IXYYilIIX0AuEZBYBScP/aVFL726CcTdvBt7s8EsgLEb1EnO5bk5Obrx0goGsTyrsjm1lr88xBaYCOxwGv3yPn2oZ/vh45ybV7DyrgyGWRXrZDqcUbvHFMLdzg+xEKXWjZiFxfAFldDPz).
> Fix: fix script-indent to prevent removing <script> tag (fixes #367)

- lib/rules/max-attributes-per-line.js
- tests/lib/rules/max-attributes-per-line.js
This PR makes `vue/max-attributes-per-line` fixable. 
The autofix insert line feed at maximum number of attributes location
>  [Update] Make `vue/max-attributes-per-line` fixable

- lib/rules/order-in-components.js
- tests/lib/rules/order-in-components.js
This PR makes `vue/order-in-components` fixable. #299
In case of `The "A" property should be above the "B" property` error, autofix will move A before B
> [Update] Make `vue/order-in-components` fixable

- lib/utils/indent-common.js
- tests/fixtures/html-indent/v-start-tag-02.vue
- tests/fixtures/html-indent/v-start-tag-03.vue
- tests/fixtures/html-indent/v-start-tag-04.vue
- tests/fixtures/html-indent/v-start-tag-05.vue
- tests/fixtures/script-indent/array-expression-02.vue
- tests/fixtures/script-indent/function-declaration-04.vue
- tests/fixtures/script-indent/object-expression-03.vue
> Fix: indent rules false positive (fixes #375)

- README.md
- docs/rules/attributes-order.md
- lib/index.js
- lib/rules/attributes-order.js
- tests/lib/rules/attributes-order.js
resolves https://github.com/vuejs/eslint-plugin-vue/issues/170
> [New] Add `vue/attribute-order`

- lib/rules/prop-name-casing.js
- package.json
- tests/lib/rules/no-parsing-error.js
- tests/lib/rules/valid-v-show.js
This PR upgrades `vue-eslint-parser` to `2.0.3` and fixes some tests.
Additionally, fixes a linting error of `no-multi-spaces` rule.
> Upgrade vue eslint parser

- README.md
It sure looks to me like there are four configurations in the list, not two.
> fix a typo in number of configurations

- docs/rules/valid-template-root.md
Simply detected and deleted duplicate in a sentence in `/docs/rules/valid-template-root.md`
> Docs: Delete duplicate sentence

- lib/rules/prop-name-casing.js
- tests/lib/rules/prop-name-casing.js
> [Fix] 'vue/prop-name-casing` to not warn variable computed property

- README.md
Believe this should be that way around.  Blindly tried to use it in an `npm install`.   Suppose I should read what I'm installing in more detail...
But so the next person isn't confused as simply as I was :joy:
> docs: fix typo in plugin name

- .gitignore
- docs/rules/attribute-hyphenation.md
- lib/rules/attribute-hyphenation.js
- tests/lib/rules/attribute-hyphenation.js
Changes:
- By default it'll still ignore `data-` and `aria-`, added to the default ignore list is `slot-scope` as this is a Vue attribute that cannot be un-hyphenated.
- Users can now do `"vue/attribute-hyphenation": ["error", "never", {"ignore": ["data-", "aria-", "my-prop"]}]` to overwrite the existing ignore list.
- Added `/.idea` folder created by Phpstorm to the `/.gitignore` list.
> Update attribute-hyphenation to allow a custom ignore list

- lib/rules/require-default-prop.js
- tests/lib/rules/require-default-prop.js
This PR fixes #416 by allowing users to use `default` key not only as Identifier, but also as a Literal in `require-default-prop` rule:
```
{
'default': 0,
}
```
> (Fixes #416) Allow "default" key to be used also as a Literal

- lib/rules/no-side-effects-in-computed-properties.js
- lib/utils/index.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/utils/index.js
This PR fixes #420, by introducing parser that simplifies given MemberExpression or CallExpression to version that can be properly verified in terms of potential side-effect in the chain.
So for example this kind of code:
```js
this.categories['test']
.map(c => c.items)
.sort()[0]
.anotherProp
.slice(1)
.reduce((acc, item) => {
// item.push(10)
return acc + item.length;
}, 0)
.length
```
Is being simplified to this:
```
this.categories.test.map().sort()[].anotherProp.slice().reduce().length
```
And now we can properly check for potential side-effects in the given chain without potential false-positives hidden in inner scopes.
> (Fixes #420) Fix false positive in no-side-effect-in-cp

- lib/utils/index.js
- tests/lib/rules/no-async-in-computed-properties.js
- tests/lib/utils/index.js
This PR fixes #436 by adding extra check to allow using object rest spread operator inside CP.
> (Fixes #436) Fix 'getComputedProperties'

- lib/rules/attribute-hyphenation.js
- tests/lib/rules/attribute-hyphenation.js
Commit f9e1eee3fe711b9dfedc037fe25aa5570370296e introduced the "ignore" config option for the attribute-hyphenation rule.  However, that commit has a few problems:
- The added testcase doesn't actually test the functionality at all
- The code only works correctly if the ignore list has exactly 1 item in it
- There are spelling mistakes in the test
See each individual commit message for more details.
> Fix attribute-hyphenation ignore lists

- docs/rules/no-v-html.md
- lib/rules/no-v-html.js
- tests/lib/rules/no-v-html.js
This PR adds vue/no-v-html rule.
This implements rule proposed in #434
> ⭐️New: Add `vue/no-v-html` rule

- docs/rules/attributes-order.md
- docs/rules/html-self-closing.md
- docs/rules/max-attributes-per-line.md
- docs/rules/name-property-casing.md
- docs/rules/no-async-in-computed-properties.md
- docs/rules/no-confusing-v-for-v-if.md
- docs/rules/no-reserved-keys.md
- docs/rules/no-shared-component-data.md
- docs/rules/no-textarea-mustache.md
- docs/rules/no-use-v-if-with-v-for.md
- docs/rules/no-v-html.md
- docs/rules/order-in-components.md
- docs/rules/prop-name-casing.md
- docs/rules/require-component-is.md
- docs/rules/require-default-prop.md
- docs/rules/require-prop-types.md
- docs/rules/require-v-for-key.md
- docs/rules/require-valid-default-prop.md
- docs/rules/v-bind-style.md
- docs/rules/v-on-style.md
As discussed in #439 this PR adds missing links to related resources.
> ⚙️Chore: Add related links to rules docs (fixes #439)

- docs/rules/require-prop-types.md
- lib/rules/require-prop-types.js
- tests/lib/rules/require-prop-types.js
According to [the docs](https://vuejs.org/v2/guide/components-props.html#Prop-Validation), if the `type` property is insufficient and more complex type-checking is required, one can use the `validator` property. Currently `eslint-plugin-vue` reports an error in such cases.
> Fix: Allow props with `validator` without `type` in `vue/require-prop-types`

- docs/rules/attribute-hyphenation.md
- docs/rules/attributes-order.md
- docs/rules/html-closing-bracket-newline.md
- docs/rules/html-closing-bracket-spacing.md
- docs/rules/html-end-tags.md
- docs/rules/html-indent.md
- docs/rules/html-quotes.md
- docs/rules/html-self-closing.md
- docs/rules/max-attributes-per-line.md
- docs/rules/mustache-interpolation-spacing.md
- docs/rules/name-property-casing.md
- docs/rules/no-multi-spaces.md
- docs/rules/no-shared-component-data.md
- docs/rules/order-in-components.md
- docs/rules/prop-name-casing.md
- docs/rules/script-indent.md
- docs/rules/v-bind-style.md
- docs/rules/v-on-style.md
- tools/update-docs.js
This PR fixes broken links in the description of the `--fix` option.
`eslint` was fixed in the following PR.
https://github.com/eslint/eslint/pull/10658
> 📝Fixed links for description of `--fix` option.

- README.md
As proposed in #262 this PR adds section that explains a bit how to work with new rules.
[rendered](https://github.com/vuejs/eslint-plugin-vue/blob/e32f69819ec39ad8cb230e2ccea24b96b5fe68f1/README.md)
I didn't add any deep specifics, rather pointers. But I think it should be enough to get people started :)
> 📝Docs: Add "working-with-rules" section in README

- docs/rules/html-closing-bracket-newline.md
- lib/rules/html-closing-bracket-newline.js
- tests/lib/rules/html-closing-bracket-newline.js
This PR introduces update to default setting for `html-closing-bracket-newline`, to force new line in case of multiline elements.
```
{
"singleline": "never",
"multiline": "always"
}
```
The reason behind this update, is that in case of multiline elements, having closing tag on a separate line makes the code more readable. Especially when there are many elements in the template. We could compare it to JS objects. We don't write:
```js
const a = {
key: 'value' };
```
but rather:
```js
const a = {
key: 'value'
};
```
Incorrect code regarding new setting:
```html
<SomeComponent
class="lorem"
:lorem="ipsum" />
```
Correct code:
```html
<SomeComponent
class="lorem"
:lorem="ipsum"
/>
```
`singleline` setting stays as is, forcing devs to keep closing tag at the same line.
> Update default settings in html-closing-bracket-newline

- README.md
- docs/rules/no-unused-components.md
- lib/configs/essential.js
- lib/index.js
- lib/rules/no-unused-components.js
- lib/utils/casing.js
- lib/utils/index.js
- tests/lib/rules/no-unused-components.js
- tests/lib/utils/index.js
This PR implements rule proposed in #414
> (implements #414) Add "no-unused-components" rule

- README.md
- docs/rules/singleline-html-element-content-newline.md
- lib/index.js
- lib/rules/singleline-html-element-content-newline.js
- tests/lib/rules/singleline-html-element-content-newline.js
This PR adds `vue/singleline-html-element-content-newline` rule.
This implements rule proposed in https://github.com/vuejs/eslint-plugin-vue/pull/547#issuecomment-410517455
It is related to #415.
> [New] Add `vue/singleline-html-element-content-newline` rule

- docs/rules/no-unused-components.md
- lib/rules/no-unused-components.js
- lib/utils/index.js
- tests/lib/rules/no-unused-components.js
This PR addresses issues pointed in #556 
I'm open to suggestion regarding `ignoreWhenBindingPresent` setting
> Fix #556: (no-unused-component) Fix component detection, add "ignoreWhenBindingPresent" option

- docs/rules/no-v-html.md
According to OWASP shorthand XSS stands for Cross-Site Scripting: https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)
> Fixed typo in v-html rule description

- lib/rules/html-self-closing.js
- tests/lib/autofix.js
fixed #554
By extending the range of autofix of `html-self-closing`, I restricted `eslint` from autofixing `html-self-closing` and `component-name-in-template-casing` at the same time.
> Fix: Made not to conflict when `html-self-closing` and `component-name-in-template-casing` are autofix

- README.md
I had an issue where the plugin works, but red markings of errors remained. So I found out the instructions for this section are missing a note regarding Vetur. You need the following setting to complete the setup:
```
"vetur.validation.template": false
```
**Note**: While it solved my issue, there is something to consider with how it's applied. Eslint is mostly used in a per-project manner. This means, if you apply the rule above to `settings.json`, it's applied globally, thus Vue projects that do not use this plugin will not show template errors. To solve this, you need to apply the setting locally. In the context of VS Code, it's easy. You just save a "workspace" to your project root and that creates a file, where you can apply the settings, thus locally. See …
> Add Vetur settings to "Why doesn't it work on .vue file?"

- lib/rules/order-in-components.js
- tests/lib/autofix.js
- tests/lib/rules/order-in-components.js
Fixed #566 
This pull request, if there is no trailing comma, make sure `vue/order-in-components` does not leave trailing comma after autofix.
Until now, after moving the target property up, we did not delete the last comma of the previous property. because of this, if the target property is the last property, the trailing comma will always remain.
With this fix, autofix will no conflict with `"comma-dangle": ["error", "always"]`.
> Fix: if no trailing comma, not to leave trailing comma after fixed of `order-in-components`

- docs/rules/valid-v-on.md
- lib/rules/valid-v-on.js
- tests/lib/rules/valid-v-on.js
> Fix #519 add custom modifiers to `vue/valid-v-on`

- lib/rules/no-unused-components.js
- tests/lib/rules/no-unused-components.js
The `no-unused-components` raises an error when the component is imported in camelCase. This PR fixes this behavior.
```vue
<template>
<div>
<the-button />
</div>
</template>
<script>
import theButton from './theButton.vue'
export default {
components: {
theButton
}
}
</script>
```
> Improve detection of components in no-unused-components rule

- docs/rules/use-v-on-extact.md
- lib/rules/use-v-on-exact.js
- tests/lib/rules/use-v-on-exact.js
Implementation of rule `use-v-on-exact` from #271
> Add rule `use-v-on-exact` #271 

- lib/rules/require-default-prop.js
- lib/rules/require-prop-type-constructor.js
- lib/rules/require-prop-types.js
- lib/rules/require-valid-default-prop.js
- lib/utils/index.js
- package.json
- tests/lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/require-default-prop.js
- tests/lib/rules/require-prop-type-constructor.js
- tests/lib/rules/require-prop-types.js
- tests/lib/rules/require-valid-default-prop.js
- tests/lib/utils/vue-component.js
Add typescript specific changes:
* Add "as" helper
* Fix `vue/require-default-prop`
* Fix `vue/require-prop-types`
* Fix `vue/require-prop-type-constructor`
* Fix `vue/require-valid-default-prop`
* Allow to use `export default (Vue as VueConstructor<Vue>).extend({` syntax
Fix issues: #564 #575
> #564 #575 Fix issues with Typescript

- docs/rules/script-indent.md
Found at https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/script-indent.md
> Add missing vue/ suffix to rule example

- docs/rules/use-v-on-exact.md
The doc name for `use-v-on-exact` was misspelt: https://github.com/vuejs/eslint-plugin-vue/pull/602/files
> fixed: Corrected doc name use-v-on-exact

- docs/rules/no-multi-spaces.md
- lib/rules/no-multi-spaces.js
- tests/lib/rules/no-multi-spaces.js
This PR implements proposition from #535
> (Implements #535) Add "ignoreProperties" option to "no-multi-spaces" rule

- lib/rules/valid-v-model.js
- tests/lib/rules/valid-v-model.js
This PR is fix false positives of iteration variable in `vue/valid-v-model`.
Fixes #240
> Fix false positives of iteration variable in `vue/valid-v-model`

- lib/utils/casing.js
- tests/lib/rules/attribute-hyphenation.js
- tests/lib/utils/casing.js
fix issue #550 
`assert.equal` throws more detailer errors than `assert.ok`
```
AssertionError: expected 'XXXXX' to equal 'YYYYY'
```
instead of 
```
AssertionError: expected false to be truthy
```
> Fix logic behind kabab case and snake case for propID

- lib/rules/valid-v-on.js
- tests/lib/rules/valid-v-on.js
This PR improves error message pointed in #614. By default if there is no value or one of the two verb modifiers we throw an error, but if someone attempts to use forbidden JS keyword the parser stripes it from AST and we throw the wrong message. Now I'm making sure that the value is really empty, both in the AST and in the code itself, otherwise the rule will throw a message about forbidden value.
> Fix #614 - Improve errors in valid-v-on, detect forbidden keywords

- .eslintrc.js
- lib/rules/max-attributes-per-line.js
- lib/utils/index.js
- tests/lib/rules/max-attributes-per-line.js
This PR addresses issue #616
[x] Replaces white spaces with new line instead of just adding new line
[x] Improves `binding` error message
[x] Improves `event` error message
[x] Improves `directive` error message
> Fix #616 - update max attrs per line error message, remove white spaces

- lib/rules/attributes-order.js
- lib/rules/component-name-in-template-casing.js
- lib/rules/no-shared-component-data.js
This PR changes to use multiple-autofixes.
https://eslint.org/blog/2017/06/eslint-v4.1.0-released#applying-multiple-autofixes-simultaneously
> Update: use multiple-autofixes.

- lib/rules/component-name-in-template-casing.js
- lib/rules/multiline-html-element-content-newline.js
- lib/rules/no-spaces-around-equal-signs-in-attribute.js
- lib/rules/singleline-html-element-content-newline.js
- lib/rules/use-v-on-exact.js
Let's enable remaining rules in the v5, except `script-indent` which will remain an `opt-in` rule, for those that want an extra indentation, otherwise original ESLint indent rule is perfectly fine.
> chore: Update uncategorized rules' categories

- lib/utils/index.js
- tests/lib/rules/require-render-return.js
i found this issue while doing: 
https://armano2.github.io/eslint-plugin-vue/rules/require-render-return.html#rule-details
and
http://armano2.github.io/eslint-plugin-vue/rules/return-in-computed-property.html#rule-details
> Fix issues with `require-render-return` and `return-in-computed-property`

- tools/update-lib-configs.js
Currently we report errors for all rules, but it's not a very semantic way of telling user something's not exactly ok. We should rather report errors only for things that are crucial - that is `base` and `essential` rules, and for recommendations throw warnings instead. It will also give users the ability to set treshold value. cc @chrisvfritz
> chore: Report errors only for base and essential rules

- lib/utils/indent-common.js
- tests/fixtures/script-indent/issue625.vue
This PR fixes #625.
The logic to implement indentation like [Conditional Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types) (a.k.a., flatten ternary expressions) did false positive.
I made stricter it.
> Fix: make strict for flatten ternary expr (fixes #625)

- lib/utils/indent-common.js
- tests/lib/rules/html-indent.js
> Fixed: not to indentation the contents on the `<textarea>` in `html-indent`

- lib/utils/indent-common.js
- package.json
- tests/fixtures/html-indent/v-filter-sequence-expression-01.vue
- tests/fixtures/html-indent/v-filter-sequence-expression-02.vue
- tests/fixtures/html-indent/v-filter-sequence-expression-03.vue
- tests/fixtures/html-indent/v-filter-sequence-expression-04.vue
- tests/fixtures/html-indent/v-filter-sequence-expression-05.vue
- tests/lib/rules/no-unused-vars.js
This PR updates `vue-eslint-parser` to v4.
I have published [vue-eslint-parser@4.0.0](https://github.com/mysticatea/vue-eslint-parser/releases/tag/v4.0.0) and it changed the AST about Vue.js Filters syntax. Before, the syntax is expressed by `BinaryExpression` because `|` is so in JavaScript. Now, the syntax is expressed by a special node `VFilterSequenceExpression`.
```
interface VFilterSequenceExpression <: Expression {
type: "VFilterSequenceExpression"
expression: Expression
filters: [ VFilter ]
}
interface VFilter <: Node {
type: "VFilter"
callee: Identifier
arguments: [ Expression ]
}
```
This update fixes some bugs:
- Fixes #687
- Fixes the bug that `vue/no-unused-vars` rule flags variables as used by the filter names.
Also, this PR updates `vue/html-indent` rule to support the new …
> Chore: update vue-eslint-parser to v4

- docs/.vuepress/components/eslint-code-block.vue
> The bottom padding of the interactive code examples seems a little excessive and I think might also be increasing a little with each line in the initial code.
https://github.com/vuejs/eslint-plugin-vue/pull/534#pullrequestreview-180095362
After: https://armano2.github.io/eslint-plugin-vue/rules/no-dupe-keys.html
Before: https://vuejs.github.io/eslint-plugin-vue/rules/no-dupe-keys.html
-----------
> Chore: improve editor style in vuepress

- lib/rules/order-in-components.js
when running tests on node 11 we are getting a lot of errors related to sort function in order in components, this change make sure that results are going to be consistent....
https://v8.dev/blog/array-sort
https://mathiasbynens.be/demo/sort-stability
> the V8 implementation changed from QuickSort to TimSort
https://github.com/nodejs/node/issues/24294
------ 
Not sure if we should add node 11 to circleci build env
> Fix: order in components for node 11

- docs/user-guide/README.md
Hello, this PR fix docs of a key bind description for macOS.
> docs: Add macOS key bind for opening preference

- lib/rules/component-name-in-template-casing.js
This PR moves `component-name-in-template-casing` to uncategorized from `strongly-recommended` category.
There are some reasons:
1. This rule can break user code by autofix. If a user uses `x-element` Web Component, the rule breaks it. To avoid this broken, the user needs to configure `ignores` option. Therefore, this rule doesn't fit `vue/strongly-recommended` preset.
1. There is a bikeshedding. https://github.com/vuejs/eslint-plugin-vue/pull/397#issuecomment-443663855, https://github.com/vuejs/eslint-plugin-vue/pull/397#issuecomment-443886771, https://github.com/vuejs/eslint-plugin-vue/issues/691#issuecomment-443400173, and https://github.com/vuejs/eslint-plugin-vue/issues/691#issuecomment-443400290. Users which use kebab-casing is much and our style guide allows it.
> Chore: move component-name-in-template-casing rule to uncategorized

- lib/rules/no-async-in-computed-properties.js
- tests/lib/rules/no-async-in-computed-properties.js
> fix(no-async-in-computed-properties): Allow async in nested scopes

- docs/rules/component-name-in-template-casing.md
- lib/rules/component-name-in-template-casing.js
- lib/utils/regexp.js
- tests/lib/autofix.js
- tests/lib/rules/component-name-in-template-casing.js
- tests/lib/utils/regexp.js
This PR makes the following changes to `component-name-in-template-casing` rule.
- Add `registeredComponentsOnly` option.
- Change the default for `registeredComponentsOnly` options to true.
- ~~Add `globalRegisteredComponents` option.~~
- ~~Add `globalRegisteredComponentPatterns` option.~~
- Changed to be able to set regexp for `ignores` option.
The feature of each additional option is as follows.
- `registeredComponentsOnly` ... If `true`, only registered components (in PascalCase) are checked. If `false`, check all.
default `true`
- ~~`globalRegisteredComponents` (`string[]`) ... (Only available when `registeredComponentsOnly` is `true`) The name of globally registered components.~~
- ~~`globalRegisteredComponentPatterns` (`string[]`) ... (Only available when `registeredComponentsOnly` …
> Fix: Add `registeredComponentsOnly` option to `component-name-in-template-casing` rule

- README.md
- docs/developer-guide/README.md
- docs/rules/jsx-uses-vars.md
- docs/user-guide/README.md
- lib/rules/require-default-prop.js
- package.json
- tests/lib/rules/require-default-prop.js
- tools/update-docs.js
This PR updates `http:` links to `https:`.
> Chore: Update `http:` links to `https:`

- docs/.vuepress/config.js
Added a link to [Playground](https://mysticatea.github.io/vue-eslint-demo) on the [documentation page](https://vuejs.github.io/eslint-plugin-vue/).
> Chore: Add link to Playground on documentation page

- docs/rules/README.md
- docs/rules/no-restricted-syntax.md
- lib/index.js
- lib/rules/no-restricted-syntax.js
- tests/lib/rules/no-restricted-syntax.js
>  ⭐️New: Add `vue/no-restricted-syntax` rule

- package.json
- tests/lib/rules/no-unused-vars.js
- tests/lib/rules/valid-v-else-if.js
- tests/lib/rules/valid-v-else.js
- tests/lib/rules/valid-v-for.js
Fixes #716
Fiees #722
Fixes #733
See the release note https://github.com/mysticatea/vue-eslint-parser/releases/tag/v5.0.0 for details.
- No rule looks to depend on `VSlotScopeExpression#id` property that was removed.
- As a side effect, it gets ignoring expressions in the attributes of the top-level tags. This affects some test cases and I wrapped those tests by `<template>` element.
> Chore: update vue-eslint-parser

- docs/rules/multiline-html-element-content-newline.md
- lib/rules/multiline-html-element-content-newline.js
- tests/lib/rules/multiline-html-element-content-newline.js
Close #683
This PR adds `allowEmptyLines` option to `vue/multiline-html-element-content-newline` rule.
- `allowEmptyLines` ... if `true`, it allows empty lines around content. If you want to disallow multiple empty lines, use [no-multiple-empty-lines] in combination.  
default `false`
[no-multiple-empty-lines]: https://eslint.org/docs/rules/no-multiple-empty-lines
> Update: Add `allowEmptyLines` option to `vue/multiline-html-element-content-newline` rule

- docs/rules/README.md
- docs/rules/arrow-spacing.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/arrow-spacing.js
- tests/lib/rules/arrow-spacing.js
This PR adds the wrapper rule of the `arrow-spacing` core rule to apply to the expressions in `<template>`.
> ⭐️New: Add `vue/arrow-spacing` rule

- docs/rules/README.md
- docs/rules/block-spacing.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/block-spacing.js
- tests/lib/rules/block-spacing.js
This PR adds the wrapper rule of the `block-spacing` core rule to apply to the expressions in `<template>`.
> ⭐️New: Add `vue/block-spacing` rule

- lib/rules/no-unused-components.js
- tests/lib/rules/no-unused-components.js
> fix(no-unused-components): crash when `:is` in `<component>` is empty

- docs/rules/valid-v-else.md
Change v-if-else into v-else-if
> Fix spelling mistake

- lib/rules/no-async-in-computed-properties.js
- tests/lib/rules/no-async-in-computed-properties.js
no-async-in-computed-properties errors out when there is no return value in a function.
> Fix no async with empty returns

- lib/rules/no-boolean-default.js
- tests/lib/rules/no-boolean-default.js
Currently the rule `no-boolean-default` breaks when used with option `'default-false'` on a boolean prop that does not have `default` property, with exception:
```
TypeError: Cannot read property 'value' of undefined
at booleanProps.forEach.propDef (lib/rules/no-boolean-default.js:7:2342)
at Array.forEach (<anonymous>)
at utils.executeOnVueComponent.obj (lib/rules/no-boolean-default.js:7:1808)
at ExportDefaultDeclaration:exit (lib/utils/index.js:174:251)
at listeners.(anonymous function).forEach.listener (node_modules/eslint/lib/util/safe-emitter.js:45:58)
at Array.forEach (<anonymous>)
at Object.emit (node_modules/eslint/lib/util/safe-emitter.js:45:38)
at NodeEventGenerator.applySelector (node_modules/eslint/lib/util/node-event-generator.js:251:26)
at NodeEventGenerator.applySelectors …
```
> Fix: no-boolean-default with 'default-false' on boolean props with unset default

- docs/rules/no-unused-components.md
In #606, the rule `no-unused-component` was updated to detect component usage when registered using camelCase as well as PascalCase.
There's a line of text in the documentation that still states PascalCase as required.  It'd be nice to update that.
> Rule documentation should match change in #606

- docs/rules/README.md
- docs/rules/no-empty-pattern.md
- lib/index.js
- lib/rules/no-empty-pattern.js
- tests/lib/rules/no-empty-pattern.js
This PR adds the wrapper rule of the [no-empty-pattern](https://eslint.org/docs/rules/no-empty-pattern) core rule to apply to the expressions in `<template>`.
> ⭐️New: Add `vue/no-empty-pattern` rule

- docs/rules/README.md
- docs/rules/dot-location.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/dot-location.js
- tests/lib/rules/dot-location.js
This PR adds the wrapper rule of the [dot-location](https://eslint.org/docs/rules/dot-location) core rule to apply to the expressions in `<template>`.
> ⭐️New: Add `vue/dot-location` rule

- docs/rules/v-on-function-call.md
Seems like it was missed in the original #481 PR.
> Use correct 'v-on-function-call' rule name in options example

- docs/rules/README.md
- docs/rules/keyword-spacing.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/keyword-spacing.js
- tests/lib/rules/keyword-spacing.js
This PR adds the wrapper rule of the [keyword-spacing](https://eslint.org/docs/rules/keyword-spacing) core rule to apply to the expressions in `<template>`.
> ⭐️New: Add `vue/keyword-spacing` rule

- docs/rules/require-direct-export.md
- docs/rules/v-on-function-call.md
Update to docs style of new docs.
> Chore: update docs of `require-direct-export.md` and `v-on-function-call.md`

- docs/rules/README.md
- docs/rules/no-deprecated-scope-attribute.md
- lib/index.js
- lib/rules/no-deprecated-scope-attribute.js
- lib/rules/syntaxes/scope-attribute.js
- tests/lib/rules/no-deprecated-scope-attribute.js
`vue/no-deprecated-scope-attribute` rule reports deprecated `scope` attribute in Vue.js v2.5.0+.
```vue
<template>
<ListComponent>
<template v-slot:name="props">
{{ props.title }}
</template>
<template slot="name" slot-scope="props">
{{ props.title }}
</template>
</ListComponent>
<ListComponent>
<template slot="name" scope="props">
{{ props.title }}
</template>
</ListComponent>
</template>
```
---
refs https://github.com/vuejs/eslint-plugin-vue/issues/800#issuecomment-460646676
> ⭐️New: Add vue/no-deprecated-scope-attribute rule

- docs/rules/v-slot-style.md
- lib/rules/v-slot-style.js
- tests/lib/rules/v-slot-style.js
> New: v-slot-style rule (fixes #801)

- docs/rules/valid-v-on.md
This had the wrong name for the rule in the example.
> Fix: copy/paste error in `valid-v-on`

- lib/rules/order-in-components.js
eslin@6 has moved `traverser.js` to `lib/shared`
https://github.com/eslint/eslint/pull/11555
> refactor: remove eslint internal `traverser`

- docs/user-guide/README.md
typescript-eslint-parser is deprecated and to be replaced by @typescript-eslint/parser
As stated on https://www.npmjs.com/package/typescript-eslint-parser
> Update @typescript-eslint/parser link

- package.json
This PR updates the `eslint-plugin-vue-libs` package, that was just updated to list ESlint@6 in peerDependencies.
> Chore: Update eslint-plugin-vue-libs

- docs/rules/attributes-order.md
"ex" is far less common an abbreviation for "example" than "e.g."
I also deleted some trailing whitespace.
> Updated attributes-order.md: "ex:" --> "e.g."

- lib/rules/use-v-on-exact.js
- tests/lib/rules/use-v-on-exact.js
This change modifies the use-v-on-exact rule so that it doesn't flag key handlers that are for different keys. For example, this should still cause a warning:
```
<input
@keydown.tab="foo"
@keydown.shift.tab="bar"/>
``` 
While code like this is fine:
```
<input
@keydown.enter="foo"
@keydown.shift.tab="bar"/>
```
I have a few instances of this in my code, and I don't believe it can cause any issues, but I may be mistaken. Please let me know what you think.
> fix(use-v-on-exact): Don't flag events with different key codes

- lib/index.js
Feel free to just close if these rules were left unregistered because they're not done or there are known issues. 🙂 I registered them because I needed to use them on a project.
> Fix: register v-slot-style and valid-v-slot

- docs/rules/README.md
- docs/rules/prop-name-casing.md
- lib/rules/prop-name-casing.js
- tests/lib/rules/prop-name-casing.js
This PR removes the `prop-name-casing` autofix.
The autofix of `prop-name-casing` breaks the program as pointed out in the following comment.
https://github.com/vuejs/eslint-plugin-vue/pull/402#issuecomment-445428304
> Drop autofix of prop-name-casing.

- package.json
This change removes the peerDependencies warning.
close #981
> Upgrade vue-eslint-parser@^6.0.5

- lib/rules/no-async-in-computed-properties.js
- tests/lib/rules/no-async-in-computed-properties.js
> Fixed false positives inside the ternary operator in `no-async-in-computed-properties`

- lib/rules/require-prop-type-constructor.js
- lib/utils/index.js
- tests/lib/rules/require-prop-type-constructor.js
> Fixed an issue that caused an error when extra commas were included in `require-prop-type-constructor`

- lib/rules/require-prop-type-constructor.js
- tests/lib/rules/require-prop-type-constructor.js
> Fixed an issue that code was broken by autofix of require-prop-type-constructor

- docs/rules/README.md
- docs/rules/component-tags-order.md
- lib/index.js
- lib/rules/component-tags-order.js
- package.json
- tests/lib/rules/component-tags-order.js
> ⭐️New: Add `vue/component-tags-order` rule

- docs/rules/component-definition-name-casing.md
- lib/rules/component-definition-name-casing.js
- lib/rules/name-property-casing.js
- tests/lib/rules/component-definition-name-casing.js
this rule replaces `vue/name-property-casing`
fix issue: #251
> ⭐️New: Add `component-definition-name-casing` rule.

- docs/rules/README.md
- docs/rules/no-deprecated-slot-scope-attribute.md
- lib/index.js
- lib/rules/no-deprecated-slot-scope-attribute.js
- lib/rules/syntaxes/slot-scope-attribute.js
- tests/lib/rules/no-deprecated-slot-scope-attribute.js
`vue/no-deprecated-slot-scope-attribute` rule reports deprecated `slot-scope` attribute in Vue.js v2.6.0+.
```vue
<template>
<ListComponent>
<template v-slot="props">
{{ props.title }}
</template>
</ListComponent>
<ListComponent>
<template slot-scope="props">
{{ props.title }}
</template>
</ListComponent>
</template>
```
---
refs https://github.com/vuejs/eslint-plugin-vue/issues/800#issuecomment-460646676
> ⭐️New: Add vue/no-deprecated-slot-scope-attribute rule

- docs/rules/README.md
- docs/rules/no-unsupported-features.md
- lib/index.js
- lib/rules/no-unsupported-features.js
- lib/rules/syntaxes/dynamic-directive-arguments.js
- lib/rules/syntaxes/slot-scope-attribute.js
- lib/rules/syntaxes/v-bind-prop-modifier-shorthand.js
- lib/rules/syntaxes/v-slot.js
- tests/lib/rules/no-unsupported-features.js
- tests/lib/rules/no-unsupported-features/dynamic-directive-arguments.js
- tests/lib/rules/no-unsupported-features/slot-scope-attribute.js
- tests/lib/rules/no-unsupported-features/utils.js
- tests/lib/rules/no-unsupported-features/v-bind-prop-modifier-shorthand.js
- tests/lib/rules/no-unsupported-features/v-slot.js
`vue/no-unsupported-features` rule reports unsupported Vue.js syntax on the specified version.
This rule checks the following syntaxes.
- Vue.js 2.6.0+
- [dynamic directive arguments](https://vuejs.org/v2/guide/syntax.html#Dynamic-Arguments).
- [v-slot](https://vuejs.org/v2/api/#v-slot) directive.
- Vue.js 2.5.0+
- [slot-scope](https://vuejs.org/v2/api/#slot-scope-deprecated) attributes.
- Vue.js `">=2.6.0-beta.1 <=2.6.0-beta.3"` or 2.6 custom build
- [v-bind](https://vuejs.org/v2/api/#v-bind) with `.prop` modifier shorthand. https://github.com/vuejs/vue/issues/7582
https://github.com/vuejs/vue/blob/dev/scripts/feature-flags.js#L3
---
refs https://github.com/vuejs/eslint-plugin-vue/issues/800#issuecomment-460646676
> ⭐️New: Add vue/no-unsupported-features rule

- lib/rules/order-in-components.js
Leverage the `Array.includes()` method to check for existence over `indexOf` which is kinda obsolete.
> refactor: use Array.includes() to check for existence

- docs/rules/README.md
- docs/rules/max-len.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/max-len.js
- tests/lib/rules/max-len.js
This PR adds the `vue/max-len` rule.
`vue/max-len` rule enforces a maximum line length to increase code readability and maintainability.
`vue/max-len` rule is the similar rule as core [max-len] rule but it applies to the source code in `.vue`.
The following options are available for the `vue/max-len` rule.
- `code` ... enforces a maximum line length. default `80`
- **`template`** ... enforces a maximum line length for `<template>`. defaults to value of `code`
- `tabWidth` ... specifies the character width for tab characters. default `2`
- `comments` ... enforces a maximum line length for comments. defaults to value of `code`
- `ignorePattern` ... ignores lines matching a regular expression. can only match a single line and need to be double escaped when written in YAML or JSON
- …
> New: Add vue/max-len rule

- docs/rules/README.md
- docs/rules/no-irregular-whitespace.md
- lib/index.js
- lib/rules/no-irregular-whitespace.js
- tests/lib/rules/no-irregular-whitespace.js
This PR adds the `vue/no-irregular-whitespace` rule.
`vue/no-irregular-whitespace` rule is aimed at catching invalid whitespace that is not a normal tab and space.
`vue/no-irregular-whitespace` rule is the similar rule as core [no-irregular-whitespace] rule but it applies to the source code in `.vue`.
The following options are available for the `vue/no-irregular-whitespace` rule.
- `skipStrings`: if `true`, allows any whitespace characters in string literals. default `true`
- `skipComments`: if `true`, allows any whitespace characters in comments. default `false`
- `skipRegExps`: if `true`, allows any whitespace characters in regular expression literals. default `false`
- `skipTemplates`: if `true`, allows any whitespace characters in template literals. default `false`
- …
> New: Add vue/no-irregular-whitespace rule

- lib/rules/attributes-order.js
Attributes moved to constant to prevent string duplication
> rule:attrubutes-order moved attributest to constants

- lib/utils/indent-common.js
- tests/fixtures/html-indent/opts-ignores-vattribute-01.vue
- tests/lib/rules/html-indent.js
> Fixed: "ignores" option of `html-indent` does not work

- lib/rules/component-definition-name-casing.js
- lib/rules/match-component-file-name.js
- lib/rules/no-reserved-component-names.js
- lib/utils/index.js
- tests/lib/rules/component-definition-name-casing.js
- tests/lib/rules/match-component-file-name.js
- tests/lib/rules/no-reserved-component-names.js
> Fixed crashes of `no-reserved-component-names`, `match-component-file-name` and `component-definition-name-casing` rules.

- package.json
Introduced in https://github.com/vuejs/eslint-plugin-vue/pull/841
Moves `semver` from `devDependencies` to `dependencies` since it's needed by two rules.
https://github.com/vuejs/eslint-plugin-vue/blob/0c80259ac96a65695b0668adbf2a577316ff7307/lib/rules/no-unsupported-features.js#L7
https://github.com/vuejs/eslint-plugin-vue/blob/0c80259ac96a65695b0668adbf2a577316ff7307/lib/rules/syntaxes/v-bind-prop-modifier-shorthand.js#L6
Ref https://github.com/yarnpkg/berry/issues/654
> fix: list semver as a dependency

- docs/rules/match-component-file-name.md
`match-component-file-name` rule can be applied to .ts?x files. So docs should be updated.
> Update match-component-file-name docs

- docs/user-guide/README.md
> Auto Fix is enabled by default. Use the single string form.
warning is shown due to changes in vscode-eslint.
As autoFix is set to `true` by default, object format in `eslint.validate` is now deprecated.
Check [vscode-eslint#7b5c40536131aa94eccd8a175e37104f5b785071](https://github.com/microsoft/vscode-eslint/commit/7b5c40536131aa94eccd8a175e37104f5b785071#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R223)
> README.md-VSCode ESlint Auto Fix

- docs/rules/README.md
- docs/rules/padding-line-between-blocks.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/component-tags-order.js
- lib/rules/padding-line-between-blocks.js
- tests/lib/rules/padding-line-between-blocks.js
This PR adds the `vue/padding-line-between-blocks` rule.
The `vue/padding-line-between-blocks` rule requires or disallows blank lines between the given 2 blocks.
---
close #855
> New: Add `vue/padding-line-between-blocks` rule

- docs/rules/attributes-order.md
- lib/rules/attributes-order.js
- tests/lib/rules/attributes-order.js
This allows an option "alphabetical" to sort attributes within groupings alphabetically 
close: https://github.com/vuejs/eslint-plugin-vue/issues/968
> New: attributes-order adding alphabetical ordering within groupings

- lib/rules/no-side-effects-in-computed-properties.js
- lib/utils/index.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
> Fixed false positives in `no-side-effects-in-computed-properties`

- docs/rules/html-quotes.md
- lib/rules/html-quotes.js
- tests/lib/rules/html-quotes.js
This PR adds an `avoidEscape` option to the `vue/html-quotes` rule
---
close #874
> Add `avoidEscape` option to `vue/html-quotes` rule

- docs/rules/attributes-order.md
- lib/rules/attributes-order.js
- package.json
- tests/lib/rules/attributes-order.js
> Fixed false positives for binded and unbinded attrs in 'vue/attributes-order' with `alphabetical` option.

- lib/rules/no-use-v-if-with-v-for.js
- tests/lib/rules/no-use-v-if-with-v-for.js
> Fixed no-use-v-if-with-v-for error when using destructuring for iteration or using iteration of expression

- docs/rules/valid-v-bind-sync.md
Copy-paste error on the [valid-v-bind-sync docs](https://eslint.vuejs.org/rules/valid-v-bind-sync.html): The link to the Vue.js guide for `.sync` pointed to a Markdown link syntax.
> Fix guide link on valid-v-bind-sync rule docs

- docs/rules/README.md
- docs/rules/component-definition-name-casing.md
- docs/rules/component-tags-order.md
- docs/rules/name-property-casing.md
- docs/rules/v-slot-style.md
- docs/rules/valid-v-bind-sync.md
- docs/rules/valid-v-slot.md
- lib/configs/essential.js
- lib/configs/recommended.js
- lib/configs/strongly-recommended.js
- lib/rules/component-definition-name-casing.js
- lib/rules/component-tags-order.js
- lib/rules/name-property-casing.js
- lib/rules/v-slot-style.js
- lib/rules/valid-v-bind-sync.js
- lib/rules/valid-v-slot.js
- Change `plugin:vue/essential` config
- Add `vue/valid-v-bind-sync` rule
- Add `vue/valid-v-slot` rule
- Change `plugin:vue/strongly-recommended` config
- Add `vue/component-definition-name-casing` rule
- Add `vue/v-slot-style` rule
- Remove `vue/name-property-casing` rule
- Change `plugin:vue/recommended` config
- Add `vue/component-tags-order` rule
- Change `vue/name-property-casing` rule to be deprecate.
> Change the ruleset for categories

- docs/rules/README.md
- docs/rules/no-custom-modifiers-on-v-model.md
- docs/rules/no-deprecated-v-bind-sync.md
- docs/rules/no-v-model-argument.md
- docs/rules/valid-v-bind.md
- docs/rules/valid-v-model.md
- lib/configs/essential.js
- lib/index.js
- lib/rules/no-custom-modifiers-on-v-model.js
- lib/rules/no-deprecated-v-bind-sync.js
- lib/rules/no-v-model-argument.js
- lib/rules/valid-v-model.js
- tests/lib/rules/no-custom-modifiers-on-v-model.js
- tests/lib/rules/no-deprecated-v-bind-sync.js
- tests/lib/rules/no-v-model-argument.js
- tests/lib/rules/valid-v-model.js
* support for `v-model:argument` syntax (replacement for `v-bind.sync`)
*  support for `v-model.customModifier` syntax
**Relates to:**
#1035 
[RFC0005](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0005-replace-v-bind-sync-with-v-model-argument.md)
[RFC0011](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0011-v-model-api-change.md)
**Scope:**
* `vue/valid-v-model` - modify rule implementation to do not report an error when:
* `v-model` is used with an argument on Vue Component. (`v-model:argument` syntax)
* `v-model` is used with custom modifiers on Vue Component. (`v-model. customModifier` syntax)
* `vue/no-v-model-argument`- new rule which reports an error when `v-model` is used with an argument on Vue Component (Vue 2 backward compatibility rule, previously handled by …
> Vue3 v-model API changes

- docs/rules/README.md
- docs/rules/no-ref-as-operand.md
- lib/index.js
- lib/rules/no-ref-as-operand.js
- package.json
- tests/lib/rules/no-ref-as-operand.js
This PR adds the `vue/no-ref-as-operand` rule.
The `vue/no-ref-as-operand` rule reports cases where a ref is used incorrectly as an operand.
---
ref #1035
> New: Add `vue/no-ref-as-operand` rule

- docs/rules/README.md
- docs/rules/no-setup-props-destructure.md
- lib/index.js
- lib/rules/no-setup-props-destructure.js
- package.json
- tests/lib/rules/no-setup-props-destructure.js
This PR adds the `vue/no-setup-props-destructure` rule.
The `vue/no-setup-props-destructure` rule reports the destructuring of `props` passed to `setup` causing the value to lose reactivity.
---
ref #1035
> New: Add `vue/no-setup-props-destructure` rule

- docs/user-guide/README.md
- lib/utils/index.js
- tests/lib/rules/component-definition-name-casing.js
- tests/lib/rules/match-component-file-name.js
- tests/lib/rules/no-reserved-component-names.js
- tests/lib/rules/no-shared-component-data.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/order-in-components.js
- tests/lib/rules/require-render-return.js
- tests/lib/utils/vue-component.js
This PR makes that the following Vue components are validated by each rule:
- `app.component('name', {/*component*/})`
- `app.mixin({/*component*/})`
- `createApp({/*component*/})`
---
ref #1035
> Updated to detect Vue3 components.

- lib/utils/index.js
- tests/lib/rules/no-dupe-keys.js
- tests/lib/rules/no-reserved-keys.js
- tests/lib/rules/no-template-shadow.js
current iterateProperties doesn't support arrow function properties. However it supports functions and iterate their returned objects. 
So we can't treat properties from arrow functions same way:
default way works:
```
data: function () {
return {
property: 'value'
}
},
```
But following examples won't work:
```
data: () => {
return {
property: 'value'
}
},
```
or like this:
```
data: () => ({
property: 'value'
}),
```
Pull request adds support for `ArrowFunctionExpression` in `iterateProperties`.
> Fix iterateProperties to support arrow functions

- docs/rules/README.md
- docs/rules/no-unused-vars.md
- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
implement proposal https://github.com/vuejs/eslint-plugin-vue/issues/1058
feat https://github.com/vuejs/eslint-plugin-vue/issues/1058
> feat: add fixable, no more error when unused variable with prefix _

- lib/rules/no-dupe-keys.js
- lib/rules/no-reserved-keys.js
- tests/lib/rules/no-dupe-keys.js
- tests/lib/rules/no-reserved-keys.js
This PR change `vue/no-dupe-key`, `no-reserved-keys` rule to handle `setup`.
ref #1035
> no-xxxx-keys: change to handle setup

- docs/rules/README.md
- docs/rules/no-deprecated-data-object-declaration.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-deprecated-data-object-declaration.js
- tests/lib/rules/no-deprecated-data-object-declaration.js
This PR adds the vue/no-deprecated-data-object-declaration rule.
This rule reports use of deprecated object declaration on `data` property.
[RFC0019](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0019-remove-data-object-declaration.md)
ref #1035
> New: Add `vue/no-deprecated-data-object-declaration` rule

- docs/rules/README.md
- docs/rules/no-template-target-blank.md
- lib/index.js
- lib/rules/no-template-target-blank.js
- tests/lib/rules/no-template-target-blank.js
> New: add `vue/no-template-no-target-blank` rule

- docs/rules/README.md
- docs/rules/no-watch-after-await.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-watch-after-await.js
- tests/lib/rules/no-watch-after-await.js
This PR adds the `vue/no-watch-after-await` rule.
The `vue/no-watch-after-await` rule reports the `watch()` after `await` expression. 
---
ref #1035
> New: Add `vue/no-watch-after-await` rule

- docs/rules/README.md
- docs/rules/require-v-if-inside-transition.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/require-v-if-inside-transition.js
- tests/lib/rules/require-v-if-inside-transition.js
This PR adds the `vue/require-v-if-inside-transition` rule.
This rule reports elements inside `<transition>` that do not control the display.
ref #1035
> New: Add `vue/require-v-if-inside-transition` rule

- docs/rules/README.md
- docs/rules/no-deprecated-inline-template.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-deprecated-inline-template.js
- tests/lib/rules/no-deprecated-inline-template.js
This PR adds the `vue/no-deprecated-inline-template` rule.
This rule reports deprecated `inline-template` attributes (removed in Vue.js v3.0.0+)
ref #1035
> New: Add `vue/no-deprecated-inline-template` rule

- docs/rules/README.md
- docs/rules/no-deprecated-html-element-is.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-deprecated-html-element-is.js
- tests/lib/rules/no-deprecated-html-element-is.js
This PR adds `vue/no-deprecated-html-element-is` rule that reports deprecated the `is` attribute on HTML elements (removed in Vue.js v3.0.0+)
> Add `vue/no-deprecated-html-element-is` rule

- docs/rules/README.md
- docs/rules/no-deprecated-vue-config-keycodes.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-deprecated-vue-config-keycodes.js
- tests/lib/rules/no-deprecated-html-element-is.js
- tests/lib/rules/no-deprecated-vue-config-keycodes.js
This PR adds `vue/no-deprecated-vue-config-keycodes` rule that reports use of deprecated `Vue.config.keyCodes` (in Vue.js 3.0.0+)
> Add `vue/no-deprecated-vue-config-keycodes` rule

- docs/rules/README.md
- docs/rules/no-deprecated-functional-template.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-deprecated-functional-template.js
- tests/lib/rules/no-deprecated-functional-template.js
This PR adds `vue/no-deprecated-functional-template` rule that reports deprecated the `functional` template (in Vue.js 3.0.0+)
> Add `vue/no-deprecated-functional-template` rule

- docs/rules/README.md
- docs/rules/no-deprecated-vue-config-keycodes.md
- docs/rules/require-explicit-emits.md
- lib/index.js
- lib/rules/no-async-in-computed-properties.js
- lib/rules/no-deprecated-events-api.js
- lib/rules/no-lifecycle-after-await.js
- lib/rules/no-setup-props-destructure.js
- lib/rules/no-side-effects-in-computed-properties.js
- lib/rules/no-watch-after-await.js
- lib/rules/require-explicit-emits.js
- lib/rules/require-render-return.js
- lib/rules/return-in-computed-property.js
- lib/utils/index.js
- tests/lib/rules/no-setup-props-destructure.js
- tests/lib/rules/require-explicit-emits.js
This PR adds `vue/require-explicit-emits` rule.
`vue/require-explicit-emits` rule reports event triggers not declared with the `emits` option. (The `emits` option is a new in Vue.js 3.0.0+)
[Vue RFCs - 0030-emits-option](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0030-emits-option.md)
refs #1035
> Add `vue/require-explicit-emits` rule

- docs/rules/README.md
- docs/rules/return-in-emits-validator.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/return-in-emits-validator.js
- tests/lib/rules/return-in-emits-validator.js
This PR adds `vue/return-in-emits-validator` rule.
`vue/return-in-emits-validator` rule enforces that a `return` statement is present in `emits` validators. (The `emits` option is a new in Vue.js 3.0.0+)
[Vue RFCs - 0030-emits-option](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0030-emits-option.md)
refs #1035
> Add `vue/return-in-emits-validator` rule

- docs/.vuepress/config.js
- docs/.vuepress/shim/module.js
- docs/rules/comment-directive.md
- docs/rules/no-template-target-blank.md
- docs/user-guide/README.md
- lib/rules/comment-directive.js
- package.json
- tests/lib/rules/comment-directive.js
- Add the support of descriptions in directive comments.
- Add the support for block-level directive comments.
> Improve HTML comment directives.

- lib/rules/return-in-emits-validator.js
- tests/lib/rules/return-in-emits-validator.js
> Fix false positives for arrow function in `vue/return-in-emits-validator`rule

- docs/rules/README.md
- docs/rules/comma-spacing.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/comma-spacing.js
- lib/utils/index.js
- tests/lib/rules/comma-spacing.js
This PR adds the wrapper rule of the [comma-spacing](https://eslint.org/docs/rules/comma-spacing) core rule to apply to the expressions in `<template>`.
> Add `vue/comma-spacing` rule

- docs/rules/README.md
- docs/rules/prefer-template.md
- lib/index.js
- lib/rules/prefer-template.js
- tests/lib/rules/prefer-template.js
This PR adds the wrapper rule of the [prefer-template](https://eslint.org/docs/rules/prefer-template) core rule to apply to the expressions in `<template>`.
> Add `vue/prefer-template` rule

- docs/rules/README.md
- docs/rules/template-curly-spacing.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/template-curly-spacing.js
- tests/lib/rules/template-curly-spacing.js
This PR adds the wrapper rule of the [template-curly-spacing](https://eslint.org/docs/rules/template-curly-spacing) core rule to apply to the expressions in `<template>`.
> Add `vue/template-curly-spacing` rule

- lib/rules/v-on-function-call.js
- tests/lib/rules/v-on-function-call.js
> Fix false positives for member call and autofix error in `vue/v-on-function-call` rule.

- docs/rules/README.md
- docs/rules/no-mutating-props.md
- lib/configs/essential.js
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-mutating-props.js
- lib/utils/index.js
- tests/lib/rules/no-mutating-props.js
- tests/lib/utils/index.js
> Add `vue/no-mutating-props` rule (from #633)

- lib/rules/no-async-in-computed-properties.js
- lib/rules/no-lifecycle-after-await.js
- lib/rules/no-mutating-props.js
- lib/rules/no-setup-props-destructure.js
- lib/rules/no-side-effects-in-computed-properties.js
- lib/rules/no-unused-properties.js
- lib/rules/no-watch-after-await.js
- lib/rules/require-explicit-emits.js
- lib/rules/require-render-return.js
- lib/rules/return-in-computed-property.js
- lib/rules/return-in-emits-validator.js
- lib/utils/index.js
- Made the side effect analysis logic of the "no-side-effects-in-computed-properties" rule common.
- Made the setup function visit common.
- Made the Vue object visit common.
> Refactoring

- docs/rules/README.md
- docs/rules/no-arrow-functions-in-watch.md
- lib/index.js
- lib/rules/no-arrow-functions-in-watch.js
- tests/lib/rules/no-arrow-functions-in-watch.js
Fixes #1113
If this rules should be categorized please let me know
> Add new `vue/no-arrow-functions-in-watch` rule

- docs/rules/space-in-parens.md
- lib/configs/no-layout-rules.js
- lib/rules/space-in-parens.js
- lib/utils/index.js
- tests/lib/rules/space-in-parens.js
This PR adds the wrapper rule of the [space-in-parens](https://eslint.org/docs/rules/space-in-parens) core rule to apply to the expressions in `<template>`.
> Add `vue/space-in-parens` rule

- lib/rules/require-valid-default-prop.js
- lib/utils/index.js
- tests/lib/rules/require-valid-default-prop.js
- Change `vue/require-valid-default-prop` rule to track the` return` statement in the `function` defined in `default`. close #1044
- Change `vue/require-valid-default-prop` rule to check `BigInt`.
- Improved the location of reporting errors in `vue/require-valid-default-prop` rule.
> Improved `vue/require-valid-default-prop` rule

- lib/rules/no-unused-vars.js
- tests/lib/rules/no-unused-vars.js
Fixed an issue where variables before the one matching `ignorePattern` were not checked.
> Fixed false negatives when using ignorePattern for `vue/no-unused-var` rule.

- docs/rules/html-indent.md
- lib/rules/html-indent.js
- lib/utils/indent-common.js
- tests/fixtures/html-indent/close-bracket-01.vue
- tests/fixtures/html-indent/close-bracket-02.vue
- tests/fixtures/html-indent/close-bracket-03.vue
- tests/fixtures/html-indent/close-bracket-04.vue
- tests/fixtures/html-indent/close-bracket-05.vue
- tests/fixtures/html-indent/close-bracket-06.vue
- Added `closeBracket.startTag`, `closeBracket.endTag` and `closeBracket.selfClosingTag` options to `vue/html-indent` rule.
So that the closeBracket offset value can be set for each tag type.
- Changed `vue/html-indent` rule to calculate the base point of the indent offset of the closing bracket of the end tag by the start tag.
Close #728
Close #756 (PR)
> Improved closing bracket indentation for `vue/html-indent` rule.

- docs/rules/README.md
- docs/rules/custom-event-name-casing.md
- lib/configs/essential.js
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/custom-event-name-casing.js
- tests/lib/rules/custom-event-name-casing.js
This PR adds `vue/custom-event-name-casing` rule.
The `vue/custom-event-name-casing` rule that enforces using kebab-case custom event names.
The `vue/custom-event-name-casing` rule is add to categories `essential` and `vue3-essential`.
close #356
> Add `vue/custom-event-name-casing` rule

- docs/rules/comment-directive.md
- lib/processor.js
- lib/rules/comment-directive.js
- tests/lib/rules/comment-directive.js
This PR adds reportUnusedDisableDirectives option to `vue/comment-directive` rule.
The reportUnusedDisableDirectives option of `vue/comment-directive` rule provides similar feature to ESLint's reportUnusedDisableDirectives option.
Enable this option to report unused `eslint-disable` HTML comments.
> Add reportUnusedDisableDirectives option to `vue/comment-directive` rule

- docs/rules/README.md
- docs/rules/no-useless-concat.md
- lib/index.js
- lib/rules/no-useless-concat.js
- tests/lib/rules/no-useless-concat.js
This PR adds the wrapper rule of the [no-useless-concat](https://eslint.org/docs/rules/no-useless-concat) core rule to apply to the expressions in `<template>`.
> Add `vue/no-useless-concat` rule

- docs/rules/README.md
- docs/rules/dot-notation.md
- lib/index.js
- lib/rules/dot-notation.js
- tests/lib/rules/dot-notation.js
This PR adds the wrapper rule of the [dot-notation](https://eslint.org/docs/rules/dot-notation) core rule to apply to the expressions in `<template>`.
> Add `vue/dot-notation` rule

- docs/rules/README.md
- docs/rules/no-deprecated-dollar-scopedslots-api.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-deprecated-dollar-scopedslots-api.js
- tests/lib/rules/no-deprecated-dollar-scopedslots-api.js
This PR adds `vue/no-deprecated-dollar-scopedslots-api` rule.
`vue/no-deprecated-dollar-scopedslots-api` rule reports use of deprecated `$scopedSlots`.
- [0006-slots-unification](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0006-slots-unification.md)
> Add `vue/no-deprecated-dollar-scopedslots-api` rule.

- docs/rules/README.md
- docs/rules/require-slots-as-functions.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/require-slots-as-functions.js
- tests/lib/rules/require-slots-as-functions.js
This PR adds `vue/require-slots-as-functionsi` rule.
`vue/require-slots-as-functions` rule enforces the properties of `$slots` to be used as a function. 
- [0006-slots-unification](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0006-slots-unification.md)
> Add `vue/require-slots-as-functions` rule.

- docs/rules/README.md
- docs/rules/no-multiple-slot-args.md
- lib/configs/recommended.js
- lib/configs/vue3-recommended.js
- lib/index.js
- lib/rules/no-multiple-slot-args.js
- tests/lib/rules/no-multiple-slot-args.js
This PR adds `vue/no-multiple-slot-args` rule.
`vue/no-multiple-slot-args` rule disallows to pass multiple arguments to scoped slots.  
close #812
> Add `vue/no-multiple-slot-args` rule.

- docs/rules/no-ref-as-operand.md
- lib/rules/no-ref-as-operand.js
- tests/lib/rules/no-ref-as-operand.js
- Changed `vue/no-ref-as-operand` rule to additionally track variables generated by `computed`, `toRef`, `customRef` and `shallowRef`.
- Changed `vue/no-ref-as-operand` rule to report incorrect use of TemplateLiteral and MemberExpression.
> Improved `vue/no-ref-as-operand` rule.

- lib/rules/valid-v-bind-sync.js
- lib/rules/valid-v-bind.js
- lib/rules/valid-v-else-if.js
- lib/rules/valid-v-else.js
- lib/rules/valid-v-for.js
- lib/rules/valid-v-html.js
- lib/rules/valid-v-if.js
- lib/rules/valid-v-model.js
- lib/rules/valid-v-on.js
- lib/rules/valid-v-show.js
- lib/rules/valid-v-slot.js
- lib/rules/valid-v-text.js
- lib/utils/index.js
- tests/lib/rules/valid-v-bind-sync.js
- tests/lib/rules/valid-v-bind.js
- tests/lib/rules/valid-v-cloak.js
- tests/lib/rules/valid-v-else-if.js
- tests/lib/rules/valid-v-else.js
- tests/lib/rules/valid-v-for.js
- tests/lib/rules/valid-v-html.js
- tests/lib/rules/valid-v-if.js
- tests/lib/rules/valid-v-model.js
- tests/lib/rules/valid-v-on.js
- tests/lib/rules/valid-v-once.js
- tests/lib/rules/valid-v-pre.js
- tests/lib/rules/valid-v-show.js
- tests/lib/rules/valid-v-slot.js
- tests/lib/rules/valid-v-text.js
- for `vue/valid-v-bind-sync`, `vue/valid-v-bind`, `vue/valid-v-else-if`, `vue/valid-v-for`, `vue/valid-v-html`, `vue/valid-v-if`, `vue/valid-v-model`, `vue/valid-v-on`, `vue/valid-v-show`, `vue/valid-v-slot` and `vue/valid-v-text` rules.
close #921
> Improved to not report that a value is required when parsing error

- docs/rules/README.md
- docs/rules/no-bare-strings-in-template.md
- lib/index.js
- lib/rules/no-bare-strings-in-template.js
- lib/utils/regexp.js
- package.json
- tests/lib/rules/no-bare-strings-in-template.js
This PR adds `vue/no-bare-strings-in-template` rule that disallows the use of bare strings in `<template>`.  
close #491
> Add `vue/no-bare-strings-in-template` rule

- docs/rules/README.md
- docs/rules/no-useless-v-bind.md
- lib/index.js
- lib/rules/no-useless-v-bind.js
- tests/lib/rules/no-useless-v-bind.js
This PR adds `vue/no-useless-v-bind` rule that reports `v-bind` with a string literal value.
> Add `vue/no-useless-v-bind` rule

- docs/rules/comment-directive.md
- docs/rules/component-tags-order.md
- lib/rules/component-tags-order.js
- tests/lib/rules/component-tags-order.js
This PR makes the name array can be specified in the one order option of the `vue/component-tags-order` rule. And change the default setting.
> Change `vue/component-tags-order` rule to allow name array to be specified with one order option

- lib/utils/index.js
- tests/lib/rules/no-dupe-keys.js
> Fixed false positives for getter/setter in `vue/no-dupe-keys` rule

- lib/rules/order-in-components.js
- lib/rules/require-explicit-emits.js
- tests/lib/rules/order-in-components.js
- tests/lib/rules/require-explicit-emits.js
- Add options for Vue.js 3.x
- `emits` to after `props`.
- `setup` to after `emits`.
- `beforeUnmount` and `unmounted` to LIFECYCLE_HOOKS.
- `renderTracked` and `renderTriggered` to LIFECYCLE_HOOKS.
- Add options for Vue.js 2.x
- `provide` and `inject` to after `mixins`.
- `errorCaptured` to LIFECYCLE_HOOKS.
- Changed the position where `vue/require-explicit-emits` rule suggests adding `emits`.
refs #1134
> Changed the default order setting of `vue/order-in-components` rule.

- docs/rules/README.md
- docs/rules/no-restricted-v-bind.md
- lib/index.js
- lib/rules/no-restricted-v-bind.js
- tests/lib/rules/no-restricted-v-bind.js
This PR adds `vue/no-restricted-v-bind` rule that disallow specific argument in `v-bind`.
The following options can be used to report misuse such as `:v-model`.
```json
{
"vue/no-restricted-v-bind": ["error", "/^v-/"]
}
```
So, close #328, close #935. 
---
The following options can be used to report misuse such as `:click`.
```json
{
"vue/no-restricted-v-bind": ["error", "click"]
}
```
So, close #740.
---
The following options can be used to report typos such as `:stlye`.
```json
{
"vue/no-restricted-v-bind": ["error", "stlye"]
}
```
refs #992.
> Add `vue/no-restricted-v-bind` rule

- docs/rules/README.md
- docs/rules/no-restricted-static-attribute.md
- lib/index.js
- lib/rules/no-restricted-static-attribute.js
- tests/lib/rules/no-restricted-static-attribute.js
This PR adds `vue/no-restricted-static-attribute` rule that disallow specific attribute.
The following options can be used to report typos such as `stlye`.
```json
{
"vue/no-restricted-static-attribute": ["error", "stlye"]
}
```
We can close the issue #992 by combining it with the `vue/no-restricted-v-bind` rule added in #1191.
Close #992.
> Add `vue/no-restricted-static-attribute` rule

- docs/rules/README.md
- docs/rules/object-property-newline.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/object-property-newline.js
- tests/lib/rules/object-property-newline.js
This PR adds the wrapper rule of the [object-property-newline](https://eslint.org/docs/rules/object-property-newline) core rule to apply to the expressions in `<template>`.
> Add `vue/object-property-newline` rule

- docs/rules/README.md
- docs/rules/object-curly-newline.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/object-curly-newline.js
- tests/lib/rules/object-curly-newline.js
This PR adds the wrapper rule of the [object-curly-newline](https://eslint.org/docs/rules/object-curly-newline) core rule to apply to the expressions in `<template>`.
> Add `vue/object-curly-newline` rule

- docs/rules/require-direct-export.md
- lib/rules/require-direct-export.js
- tests/lib/rules/require-direct-export.js
And, add option `disallowFunctionalComponentFunction` to revert to the old behavior.
close #1197
> Fixed false positives for Vue 3 functional component in `vue/require-direct-export` rule.

- docs/rules/attribute-hyphenation.md
- docs/rules/custom-event-name-casing.md
- docs/rules/no-potential-component-option-typo.md
- docs/rules/no-restricted-static-attribute.md
- docs/rules/no-restricted-syntax.md
- docs/rules/no-restricted-v-bind.md
- docs/rules/no-unused-properties.md
- Now only one type of emoji is used: the one that was most used in the documentation;
- Fixed some wrong notation `✗ BAD` and `✓ GOOD`
> Fixed the usage of '✗ BAD' and '✓ GOOD' in the documentation

- docs/rules/README.md
- docs/rules/operator-linebreak.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/operator-linebreak.js
- tests/lib/rules/operator-linebreak.js
This PR adds the wrapper rule of the [operator-linebreak](https://eslint.org/docs/rules/operator-linebreak) core rule to apply to the expressions in `<template>`.
> Add `vue/operator-linebreak` rule

- docs/rules/README.md
- docs/rules/func-call-spacing.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/func-call-spacing.js
- tests/lib/rules/func-call-spacing.js
This PR adds the wrapper rule of the [func-call-spacing](https://eslint.org/docs/rules/func-call-spacing) core rule to apply to the expressions in `<template>`.
> Add `vue/func-call-spacing` rule

- docs/rules/order-in-components.md
- lib/rules/order-in-components.js
> Add Nuxt and Vue Router properties in `order-in-components`

- .eslintrc.js
- lib/rules/order-in-components.js
- lib/rules/require-direct-export.js
- lib/utils/index.js
- tests/lib/rules/order-in-components.js
- tests/lib/rules/require-direct-export.js
- tests/lib/utils/vue-component.js
Format the files for which the PR has been finished.
> Format some files

- docs/rules/v-on-function-call.md
- lib/rules/no-restricted-v-bind.js
- lib/rules/v-on-function-call.js
- tests/lib/rules/v-on-function-call.js
> Fixed wrong autofix in `vue/v-on-function-call` rule and `ignoreIncludesComment` option to `vue/v-on-function-call` rule

- docs/rules/no-bare-strings-in-template.md
- docs/rules/require-prop-type-constructor.md
- lib/rules/no-bare-strings-in-template.js
- tests/lib/rules/no-bare-strings-in-template.js
This PR replaces some words.
Also, change the option name in the `vue/no-bare-strings-in-template` rule.
This is a breaking change, but we'll change this rule as it's only released in alpha stage.
> Replace words

- docs/rules/README.md
- docs/rules/no-deprecated-destroyed-lifecycle.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-deprecated-destroyed-lifecycle.js
- tests/lib/rules/no-deprecated-destroyed-lifecycle.js
This PR adds `vue/no-deprecated-destroyed-lifecycle` rule.
The `vue/no-deprecated-destroyed-lifecycle` rule reports use of deprecated `destroyed` and `beforeDestroy` lifecycle hooks.
> Add `vue/no-deprecated-destroyed-lifecycle` rule

- docs/rules/README.md
- docs/rules/no-restricted-component-options.md
- lib/index.js
- lib/rules/no-restricted-component-options.js
- tests/lib/rules/no-restricted-component-options.js
This PR adds `vue/no-restricted-component-options` rule.
The `vue/no-restricted-component-options` rule allows you to specify component options that you don't want to use in your application.
> Add `vue/no-restricted-component-options` rule

- package.json
- tools/update-lib-configs.js
- tools/update-lib-index.js
> chore(tools): use ESLint class

- docs/rules/README.md
- docs/rules/no-empty-component-block.md
- lib/index.js
- lib/rules/no-empty-component-block.js
- tests/lib/rules/no-empty-component-block.js
close #952 
This PR adds vue/no-empty-component-block rule.
> feat: Add no-empty-component-block rule

- lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
Hi, thanks for great plugin!
I'm using object property to set `el` of Vue.
However, I get a `TypeError` when I update eslint-plugin-vue to `v7.0.0-alpha.7` and run eslint.
for example:
```javascript
const dummy = { app: '#app' }
new Vue({
el: dummy.app,
template: '<p>test</p>',
});
```
```
TypeError: Cannot read property 'body' of undefined
```
I think the cause of this issue is that the `scopeStack` has no default value.
but, I’m not sure if this PR is the best solution.
Could you please review this PR or use another best solution to fix this issue?
Thanks.
> Fixed no-side-effects-in-computed-properties when el is object

- lib/rules/no-async-in-computed-properties.js
- lib/rules/no-bare-strings-in-template.js
- lib/rules/no-lifecycle-after-await.js
- lib/rules/no-setup-props-destructure.js
- lib/rules/no-side-effects-in-computed-properties.js
- lib/rules/no-template-shadow.js
- lib/rules/no-watch-after-await.js
- lib/rules/require-direct-export.js
- lib/rules/require-valid-default-prop.js
- lib/rules/return-in-emits-validator.js
- lib/rules/sort-keys.js
- lib/rules/this-in-template.js
- tests/lib/rules/no-async-in-computed-properties.js
- tests/lib/rules/no-setup-props-destructure.js
- tests/lib/rules/no-watch-after-await.js
This PR is fixes for rules with similar issues as #1226.
> Fixed crash in `vue/no-async-in-computed-properties`, `vue/no-setup-props-destructure` and `vue/no-watch-after-await`

- lib/rules/no-empty-component-block.js
- lib/rules/padding-line-between-blocks.js
- tests/lib/rules-without-vue-sfc.js
- tests/lib/rules/no-empty-component-block.js
- tests/lib/rules/padding-line-between-blocks.js
- typings/eslint-plugin-vue/util-types/parser-services.ts
> Fixed crash when using `vue/no-empty-component-block` and `vue/padding-line-between-blocks` rules in `.js` file

- docs/user-guide/README.md
- lib/configs/base.js
- tools/update-lib-configs.js
This PR removes `jsx:true` from the shareable configs provided by eslint-plugin-vue.
After this, if the user wants to use JSX, they need to set `jsx:true`.
close #1223
> Remove jsx:true from shareable configs.

- docs/rules/README.md
- docs/rules/no-lone-template.md
- lib/configs/recommended.js
- lib/configs/vue3-recommended.js
- lib/index.js
- lib/rules/no-lone-template.js
- tests/lib/rules/no-lone-template.js
This PR adds `vue/no-lone-template` rule.
`vue/no-lone-template` rule that disallow unnecessary `<template>` element.
This rule reports `<template>` elements that have no specific directives (`v-if`, `v-else`, `v-else-if`, `v-for`, `v-slot`, `slot`, `slot-scope` and `scope`).
Note: `slot` and `slot-scope` are deprecated in Vue.js 2.6, `scope` is deprecated in Vue.js 2.5.
The name of the this rule was inspired by [no-lone-blocks](https://eslint.org/docs/rules/no-lone-blocks).
close #567
> Add `vue/no-lone-template` rule

- docs/rules/README.md
- docs/rules/no-dupe-v-else-if.md
- lib/configs/essential.js
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-dupe-v-else-if.js
- lib/utils/index.js
- tests/lib/rules/no-dupe-v-else-if.js
- typings/eslint-plugin-vue/util-types/ast/ast.ts
This PR adds `vue/no-dupe-v-else-if` rule.
`vue/no-dupe-v-else-if` rule disallows duplicate conditions in the same `v-if` / `v-else-if` chain.
```vue
<template>
<div v-if="isSomething(x)" />
<div v-else-if="isSomething(x)" />
<div v-if="isSomething(x)" />
<div v-else-if="isSomethingElse(x)" />
</template>
```
this rule was inspired by [no-dupe-else-if](https://eslint.org/docs/rules/no-dupe-else-if) rule.
> Add `vue/no-dupe-v-else-if` rule

- docs/rules/README.md
- docs/rules/no-sparse-arrays.md
- lib/index.js
- lib/rules/no-sparse-arrays.js
- tests/lib/rules/no-sparse-arrays.js
This PR adds the wrapper rule of the [no-sparse-arrays](https://eslint.org/docs/rules/no-sparse-arrays) core rule to apply to the expressions in `<template>`.
> Add `vue/no-sparse-arrays` rule

- docs/rules/README.md
- docs/rules/require-explicit-emits.md
- lib/configs/vue3-strongly-recommended.js
- lib/rules/require-explicit-emits.js
That is also recommended in the official guide.
https://v3.vuejs.org/guide/component-custom-events.html#defining-custom-events
> Change category of `vue/require-explicit-emits` rule to `vue3-strongly-recommended`

- docs/rules/attributes-order.md
- docs/rules/no-unsupported-features.md
- lib/rules/attributes-order.js
- lib/rules/no-unregistered-components.js
- lib/rules/no-unsupported-features.js
- lib/rules/no-unused-components.js
- lib/rules/syntaxes/v-is.js
- lib/utils/index.js
- tests/lib/rules/attributes-order.js
- tests/lib/rules/no-unregistered-components.js
- tests/lib/rules/no-unsupported-features/v-is.js
- tests/lib/rules/no-unused-components.js
- Change the `vue/attributes-order` rule to handle `v-is` as `DEFINITION` category.
- Change the `vue/no-unregistered-components` rule to handle `v-is` like `:is`.
- Change the `vue/no-unused-components` rule to handle `v-is` like `:is`.
- Add `"v-is"` to the syntax checked by the `vue/no-unsupported-features` rule.
> Change the rules to support "v-is".

- lib/rules/no-unused-properties.js
- lib/utils/index.js
- tests/lib/rules/no-unused-properties.js
> Fix false positives for watch handler methods in `vue/no-unused-properties` rule

- docs/rules/require-explicit-emits.md
- lib/rules/no-reserved-component-names.js
- lib/rules/require-explicit-emits.js
- lib/rules/require-valid-default-prop.js
- lib/utils/casing.js
- tests/lib/rules/require-explicit-emits.js
Even if you declare it in props, a warning message and fallthrough can be stopped, so I add an option to allow this.
https://github.com/vuejs/vue-next/blob/00ab9e2e8506d108958895cda4e977dfb16b53f9/packages/runtime-core/src/componentEmits.ts#L50
By default this option remains disabled.
> Add `allowProps` option to `vue/require-explicit-emits` rule.

- docs/rules/README.md
- docs/rules/v-for-delimiter-style.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/v-for-delimiter-style.js
- tests/lib/rules/v-for-delimiter-style.js
> Add `v-for-delimiter-style` rule

- docs/user-guide/README.md
> Docs: Add "Trouble with Visual Studio Code" section to FAQ

- docs/rules/README.md
- docs/rules/no-template-key.md
- docs/rules/no-v-for-template-key.md
- lib/configs/essential.js
- lib/index.js
- lib/rules/no-template-key.js
- lib/rules/no-v-for-template-key.js
- tests/lib/rules/no-template-key.js
- tests/lib/rules/no-v-for-template-key.js
This PR separates the rule reporting keys placed on `<template v-for>` from `vue/no-template-key` rule.
This PR makes the following changes.
- Change `vue/no-template-key` to allow `v-for` key.
- Add `vue/no-v-for-template-key` rule that disallow the key placed on the `<template v-for>`.
- Add `vue/no-v-for-template-key` rule to `plugin:vue/essential` config.
refs #1279
> Separate rule that report <template v-for key> from no-template-key rule

- lib/rules/require-v-for-key.js
- lib/rules/valid-v-for.js
- tests/lib/rules/require-v-for-key.js
- tests/lib/rules/valid-v-for.js
This PR makes the following changes.
- Change `vue/valid-v-for` rule to not report when placing key on `<template>`
- Change `vue/require-v-for-key` rule to not report when placing key on `<template>`
refs #1279
> Change `vue/valid-v-for` and `vue/require-v-for-key` rules to not report when placing key on `<template>`

- docs/rules/README.md
- docs/rules/no-v-for-template-key-on-child.md
- docs/rules/no-v-for-template-key.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-v-for-template-key-on-child.js
- tests/lib/rules/no-v-for-template-key-on-child.js
This PR adds `vue/no-v-for-template-key-on-child` rule that reports the key of the `<template v-for>` placed on the child elements.
close #1279
> Add `vue/no-v-for-template-key-on-child` rule

- docs/rules/no-potential-component-option-typo.md
> Fix doc of vue/no-potential-component-option-typo rule

- docs/rules/README.md
- docs/rules/no-deprecated-props-default-this.md
- lib/configs/vue3-essential.js
- lib/index.js
- lib/rules/no-deprecated-props-default-this.js
- tests/lib/rules/no-deprecated-props-default-this.js
This PR add `vue/no-deprecated-props-default-this`  rule.
The `vue/no-deprecated-props-default-this`  rule reports the use of `this` within the props default value factory functions.
> Add `vue/no-deprecated-props-default-this` rule

- lib/rules/no-unregistered-components.js
- package.json
In some really specific cases when the project patches `require()` to alias some modules (e.g. to fix an issue with ESLint sharable configs) this plugin may crash. This happens because it requires itself globally using its name which is redundant. 
Other plugins that are testes on the same project have no such issue.
This PR converts such paths to relative paths.
> Avoid redundant global self-require of the plugin

- docs/rules/no-unregistered-components.md
- lib/rules/no-unregistered-components.js
- tests/lib/rules/no-unregistered-components.js
Right now when we use recursive components (when we want to use the current component inside of itself - with the example of a `Note` component that can have a number of replies, that look and behave exactly like the `Note` component, and they stack inside of one another), eslint-plugin-vue complains against it, making us disable this rule every time we want to use a recursive component. 
The suggestion is to include a new argument to the rule, `ignoreRecursive`, which, if `true`, checks whether the name of the parent component is the same as the child component (making it thus a recursive component), not warning about this rule on it.
Resolves #1304
> Make rule vue/no-unregistered-components ignore recursive components

- docs/rules/custom-event-name-casing.md
- lib/rules/custom-event-name-casing.js
- tests/lib/rules/custom-event-name-casing.js
Hi, currently there are some components from library that still uses pascalCase when passing the function
`<customComponent @maskClick="handleMaskClick"/>` this changes added options so it can ignore some event naming just like in `component-name-in-template-casing`.
What do you think?
> added options for events that ignore custom-event-name-casing

- docs/rules/valid-v-slot.md
- lib/rules/valid-v-slot.js
- tests/lib/rules/valid-v-slot.js
- resolve #1165 
Add `allowModifiers` option to `valid-v-slot` rules. When this option is set to `true`, modifiers in the argument of `v-slot` are ignored, and invalid modifiers like `v-slot.foo` are still disallowed.
> Add allowModifiers option to valid-v-slot

- README.md
- docs/developer-guide/README.md
- docs/rules/html-indent.md
- docs/rules/no-restricted-syntax.md
- docs/rules/script-indent.md
- package.json
- tests/lib/rules/v-on-function-call.js
- typings/eslint-plugin-vue/util-types/ast/v-ast.ts
fix #766
fix #879
fix #1265
fix #1274
> Upgrade vue-eslint-parser to 7.1.1 and fixed CRLF issues.

- lib/rules/no-unused-properties.js
- tests/lib/rules/no-unused-properties.js
> Fixed false positives when used via argument in `vue/no-unused-properties`

- docs/rules/README.md
- docs/rules/block-tag-newline.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/block-tag-newline.js
- tests/lib/rules/block-tag-newline.js
This PR adds `vue/block-tag-newline` rule.
`vue/block-tag-newline` rule that enforces a line break (or no line break) after opening and before closing block tags.
close #1325
> Add vue/block-tag-newline rule

- docs/rules/README.md
- docs/rules/array-bracket-newline.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/array-bracket-newline.js
- tests/lib/rules/array-bracket-newline.js
`vue/array-bracket-newline` rule that applies `array-bracket-newline` rule to expressions in <template>.
> Add `vue/array-bracket-newline` rule

- lib/rules/valid-v-bind-sync.js
- package.json
- tests/lib/rules/valid-v-bind-sync.js
Fixes #1298 
Signed-off-by: Moulik Aggarwal <qwertymoulik@gmail.com>
> fix(eslint-plugin-vue): [valid-v-bind-sync] Added Case: when valid is then valid .sync

- docs/rules/README.md
- docs/rules/custom-event-name-casing.md
- lib/configs/essential.js
- lib/configs/vue3-essential.js
- lib/rules/custom-event-name-casing.js
- tests/lib/rules/custom-event-name-casing.js
This PR adds casing option (`"kebab-case"` and `"camelCase"`) to `vue/custom-event-name-casing` rule.
The recommended casings for Vue3 will change. So this rule adds an option so that you can enforce either.
Also, I think the user needs to select the casing, so remove the rule from configurations (`"plugin:vue/essential"` and `"plugin:vue/vue3-essential"`).
close #1347
> Add casing option to vue/custom-event-name-casing rule & remove from configs.

- docs/rules/no-deprecated-filter.md
- docs/user-guide/README.md
- package.json
- tests/lib/rules/no-deprecated-filter.js
> Upgrade vue-eslint-parser to v7.2.0

- lib/rules/valid-v-slot.js
- tests/lib/rules/valid-v-slot.js
> Fix false positives when using v-for variable for v-slot in `vue/valid-v-slot` rule

- lib/rules/require-toggle-inside-transition.js
- lib/rules/valid-v-bind-sync.js
- lib/utils/index.js
- tests/lib/rules/valid-v-bind-sync.js
- tests/lib/rules/valid-v-model.js
- tests/lib/rules/valid-v-slot.js
> Fix false positives when using <svg> in `vue/valid-v-slot` and `vue/valid-v-model` rule

- lib/rules/no-arrow-functions-in-watch.js
- lib/rules/no-unused-properties.js
- lib/utils/index.js
- tests/lib/rules/no-arrow-functions-in-watch.js
- tests/lib/rules/no-unused-properties.js
> Fix false negatives when using handler property in `vue/no-arrow-functions-in-watch` rule

- lib/rules/v-on-function-call.js
- tests/lib/rules/v-on-function-call.js
> Fix false positives for methods whose arguments should not be changed in the `vue/v-on-function-call` rule.

- docs/rules/README.md
- docs/rules/no-restricted-props.md
- lib/index.js
- lib/rules/no-restricted-props.js
- tests/lib/rules/no-restricted-props.js
This PR adds `vue/no-restricted-props` rule.
`vue/no-restricted-props` rule that allows you to specify props that you don't want to use in your application.
> Add vue/no-restricted-props rule

- docs/rules/README.md
- docs/rules/no-restricted-custom-event.md
- lib/index.js
- lib/rules/no-restricted-custom-event.js
- tests/lib/rules/no-restricted-custom-event.js
This PR adds `vue/no-restricted-custom-event` rule.
`vue/no-restricted-custom-event` rule that allows you to specify custom event that you don't want to use in your application.
> Add vue/no-restricted-custom-event rule

- lib/rules/no-unregistered-components.js
- tests/lib/rules/no-unregistered-components.js
Hi 👋 First, thank you for your work on this project 🙏 
It is my first open-source PR, I hope it is the right way to do. 
In components' templates using multiple `<template>` to target named `slot`s, I noticed the `vue/no-unregistered-component` linter warnings were repeated as many times as there are `<template>`s, for the same unregistered components.
It is not very convenient, especially for large projects ongoing refactoring. 
```
<template>
<TableView>
<template #name>
{{ tableViewName }}
</template>
<template #footer>
<TableViewFooter>
<template #action>
<CustomButton />
</template>
</TableViewFooter>
</template>
</TableView>
</template>
```
<details><summary>
Would display these errors:
</summary>
```
warning: The "TableView" component has been used but not registered …
```
> Fix multiple reporting of same warnings in `vue/no-unregistered-component`

- docs/rules/README.md
- docs/rules/no-restricted-call-after-await.md
- lib/index.js
- lib/rules/no-restricted-call-after-await.js
- tests/lib/rules/no-restricted-call-after-await.js
- typings/eslint/index.d.ts
This PR adds `vue/no-restricted-call-after-await` rule.
`vue/no-restricted-call-after-await` rule reports your restricted calls after the `await` expression.
You can use this rule to check if for example `useI18n()` of `vue-i18n` are called asynchronously in the `setup()` function.
> Add vue/no-restricted-call-after-await rule

- docs/rules/attributes-order.md
- lib/rules/attributes-order.js
- tests/lib/rules/attributes-order.js
This PR fixes false positives for `v-bind="object"` syntax in `vue/attributes-order` rule.
For example, there were the following false positives:
```vue
<template>
<div
v-bind="object"
id="x"> 
</div>
</template>
```
However, in Vue3, changing this order will change the behavior.
`v-bind="object"` changes the rule to report an error only if it's okay to change the order.
> Fixed false positives for `v-bind="object"` syntax in `vue/attributes-order` rule

- docs/rules/README.md
- docs/rules/attribute-hyphenation.md
- docs/rules/custom-event-name-casing.md
- docs/rules/prop-name-casing.md
- docs/rules/v-on-event-hyphenation.md
- lib/index.js
- lib/rules/v-on-event-hyphenation.js
- tests/lib/rules/v-on-event-hyphenation.js
This PR adds `vue/v-on-event-hyphenation` rule.
`vue/v-on-event-hyphenation` rule enforces using hyphenated v-on event names on custom components in Vue templates.
> Add vue/v-on-event-hyphenation rule

- docs/rules/no-unused-properties.md
- lib/rules/no-unused-properties.js
- lib/utils/index.js
- tests/lib/rules/no-unused-properties.js
This PR adds `deepData` option to `vue/no-unused-properties` rule.
If `true`, the object of the property defined in `data` will be searched deeply. Include `"data"` in `groups` to use this option.
e.g. 
```vue
<template>
<Foo :param="state.used">
</template>
<script>
export default {
data() {
return {
state: {
/* ✓ GOOD */
used: null,
/* ✗ BAD (`state.unused` data not used) */
unused: null
}
}
}
}
</script>
```
> Add `deepData` option to `vue/no-unused-properties` rule

- docs/rules/no-async-in-computed-properties.md
- lib/rules/no-async-in-computed-properties.js
- lib/utils/index.js
- tests/lib/rules/no-async-in-computed-properties.js
This PR adds support for composition api's computed function to `vue/no-async-in-computed-properties`.
refs #1393
> Add composition api's computed function support to vue/no-async-in-computed-properties refs #1393

- docs/rules/README.md
- docs/rules/no-ref-as-operand.md
- lib/rules/no-ref-as-operand.js
- tests/lib/rules/no-ref-as-operand.js
This PR makes `vue/no-ref-as-operand fixable` fixable. close #1394 
The auto fix adds `.value` after the `Ref` value where it is needed.
> Make no-ref-as-operand fixable close #1394

- docs/rules/README.md
- docs/rules/no-constant-condition.md
- lib/index.js
- lib/rules/no-constant-condition.js
- tests/lib/rules/no-constant-condition.js
> Add `vue/no-constant-condition` rule

- lib/rules/no-ref-as-operand.js
- tests/lib/rules/no-ref-as-operand.js
> Fix false positives for assignments in `no-ref-as-operand` rule

- docs/rules/README.md
- docs/rules/next-tick-style.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/next-tick-style.js
- tests/lib/rules/next-tick-style.js
Closes #1318.
Before reviewing, please have a look at #1399. Does it make sense to merge these two rules into one? If so, I'll try to implement that.
> Add `vue/next-tick-style` rule

- docs/rules/return-in-computed-property.md
- lib/rules/return-in-computed-property.js
- tests/lib/rules/return-in-computed-property.js
This PR adds support for composition api's computed function to `vue/return-in-computed-property `.
refs #1393
> Add composition api's computed function support to vue/return-in-computed-property refs #1393

- docs/rules/no-side-effects-in-computed-properties.md
- lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
This PR adds support for composition api's computed function to `vue/no-side-effects-in-computed-properties`.
close #1393
With computed properties, this rule only warned about mutating `this`.
But since computed functions does not use `this`, I made it warn about mutating any variables which are not declared inside the computed function.
For example
```ts
const foo = ref(0)
const bar = computed(() => {
foo.value = 3 // here it will be warned, since `foo` is not declared inside computed
return foo.value + 3
})
const baz = computed(() => {
const foobar = [3,5,6]
return foobar.sort().map(v => v + foo.value) // here it will not be warned, since `foobar` is declared inside computed
})
```
Is this approach ok? Any other one is better?
If it is ok, should I change the behavior with computed …
> Add composition api's computed function support to vue/no-side-effects-in-computed-properties close #1393

- lib/rules/one-component-per-file.js
- lib/rules/require-name-property.js
- lib/utils/index.js
- tests/lib/rules/one-component-per-file.js
- tests/lib/rules/require-name-property.js
> Fix false positives for mixin in vue/one-component-per-file and vue/require-name-property rules

- lib/rules/no-unused-properties.js
- tests/lib/rules/no-unused-properties.js
> Fix crash for toLocaleString() in `vue/no-unused-properties` rule

- docs/rules/attributes-order.md
- lib/rules/attributes-order.js
- tests/lib/rules/attributes-order.js
This PR adds the "SLOT" option to `vue/attributes-order` rule.
This PR has taken over and changed #1311.
The difference from #1311 is that if the order setting is omitted, the order of the omitted attributes will be excluded from the check.
close #1311
> Add "SLOT" option to vue/attributes-order rule to specify v-slot order.

- lib/rules/attributes-order.js
- lib/rules/component-tags-order.js
- lib/rules/max-attributes-per-line.js
- lib/rules/new-line-between-multi-line-property.js
- lib/rules/no-bare-strings-in-template.js
- lib/rules/no-duplicate-attributes.js
- lib/rules/no-potential-component-option-typo.js
- lib/rules/no-reserved-component-names.js
- lib/rules/no-use-v-if-with-v-for.js
- lib/rules/no-useless-mustaches.js
- lib/rules/no-useless-v-bind.js
- lib/rules/valid-v-slot.js
- tests/lib/rules/attributes-order.js
This PR modifies the option schema of some rules to be strict.
This change causes an error to be thrown if the user specifies an incorrect option.
Targets:
- vue/attributes-order
- vue/component-tags-order
- vue/max-attributes-per-line
- vue/new-line-between-multi-line-property
- vue/no-bare-strings-in-template
- vue/no-duplicate-attributes
- vue/no-potential-component-option-typo
- vue/no-reserved-component-names
- vue/no-use-v-if-with-v-for
- vue/no-useless-mustaches
- vue/no-useless-v-bind
- vue/valid-v-slot
> Change options schema to strictly.

- docs/rules/README.md
- docs/rules/html-button-has-type.md
- lib/configs/recommended.js
- lib/rules/html-button-has-type.js
- tests/lib/rules/html-button-has-type.js
- Enable type checking
- Format
- Exclude from recommended category
- Exclude `Button` component from check
> Change vue/html-button-has-type rule

- lib/rules/attributes-order.js
- tests/lib/rules/attributes-order.js
> Fix false negatives for v-bind="object" in vue/attributes-order rule

- package.json
- tests/lib/rules/no-restricted-syntax.js
This PR upgrades vue-eslint-parser to v7.5.0.
This change fixes an issue that caused a crash when traversing a template using queries such as `:nth-child`.
fixed #870
> Upgrade vue-eslint-parser to v7.5.0

- docs/rules/no-unused-properties.md
- lib/rules/no-unused-properties.js
- tests/lib/rules/no-unused-properties.js
- typings/eslint-utils/index.d.ts
> Add `ignorePublicMembers` option to `vue/no-unused-properties` rule

- lib/rules/this-in-template.js
- tests/lib/rules/this-in-template.js
This PR fixes false negatives for the `vue/this-in-template` rule.
The following code was not reported.
```vue
<template>
{{ this.$foo }}
</template>
```
> Fix false negatives for member access with `$` in `vue/this-in-template` rule

- package.json
- tests/fixtures/html-indent/address-component-01.vue
- tests/fixtures/html-indent/input-component-01.vue
- tests/fixtures/html-indent/input-component-02.vue
- tests/lib/rules/html-end-tags.js
- tests/lib/rules/html-self-closing.js
- tests/lib/rules/no-multiple-template-root.js
- tests/lib/rules/no-parsing-error.js
close #1292
close #1300
close #1439
> Upgrade vue-eslint-parser to 7.6.0

- docs/user-guide/README.md
`prettier/vue`, `prettier/@typescript-eslint`, etc. have been removed in `eslint-config-prettier` v8.0.0.
They are needed no longer.
See https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
I've also removed the "If [Prettier] conflicts with the rule you have set, turn off that rule" part because that's exactly what `eslint-config-prettier` is for.
> docs: remove mention of "prettier/vue"

- lib/rules/require-direct-export.js
- tests/lib/rules/require-direct-export.js
This PR allows two cases below with rule `require-direct-export` enabled:
```js
import Vue from 'vue'
export default Vue.extend({})
```
```js
import { defineComponent } from 'vue'
export default defineComponent({})
```
which will benefit TypeScript users.
Fixes #907
> Update: allow more cases in `require-direct-export`

- docs/rules/valid-v-show.md
- lib/rules/valid-v-show.js
- tests/lib/rules/valid-v-show.js
> Update: disallow `v-show` on `<template>` tag

- docs/rules/max-attributes-per-line.md
- lib/rules/max-attributes-per-line.js
- tests/lib/rules/max-attributes-per-line.js
**What rule do you want to change?**
`max-attributes-per-line`
**Does this change cause the rule to produce more or fewer warnings?**
More
**How will the change be implemented? (New option, new default behavior, etc.)?**
Lower the minimum value on `singleline`/`singleline.max` to 0 on the schema.
Update:
Add a `singleline.allowFirstLine` option that defaults to `true`, but prevents single attributes from being on the same line if set to `false`.
**Please provide some example code that this change will affect:**
When setting `singleline.max = 0`, the following should be marked incorrect:
Update:
When setting `singleline.allowFirstLine = false`, the following should be marked incorrect:
```vue
<template>
<component name="John Doe" />
</template>
```
**What does the rule currently do for …
> feat(max-attributes-per-line): singleline.allowFirstLine option

- lib/rules/require-valid-default-prop.js
- tests/lib/rules/require-valid-default-prop.js
fix #1468.
This PR ensure that eslint-plugin-vue reports `Type of thye default value for 'foo' prop must be function` in following case.
(It works the same for `Object` or `Function`.)
```vue
<script lang="ts">
import Vue from "vue";
import { PropType } from "vue";
export default Vue.extend({
props: {
foo: {
type: Array as PropType<string[]>,
default: [],
},
},
});
</script>
```
Note: In following case, type cheking based on annotated type of the return value of the default function will not work.
```vue
<script lang="ts">
import Vue from "vue";
import { PropType } from "vue";
export default Vue.extend({
props: {
foo: {
type: Array as PropType<string[]>,
default: (): number[] => [], // The function should return array of string, but this PR can't check it.
},
},
});
</script>
```
> Fix false negative with require-valid-default-prop on props with type assertion

- docs/rules/no-invalid-model-keys.md
- lib/index.js
- lib/rules/no-invalid-model-keys.js
- tests/lib/rules/no-invalid-model-keys.js
This PR adds the rule `vue/no-invalid-model-keys` which check `model` prop keys
REF: https://github.com/vuejs/eslint-plugin-vue/issues/824
> New: Add `vue/no-invalid-model-keys` rule

- docs/rules/README.md
- docs/rules/no-unused-refs.md
- lib/index.js
- lib/rules/no-unused-refs.js
- tests/lib/rules/no-unused-refs.js
Ths PR adds `vue/no-unused-refs` rule.
`vue/no-unused-refs`rule that reports refs that are defined using the `ref` attribute in `<template>` but are not used via `$refs`.
> Add `vue/no-unused-refs` rule

- lib/rules/require-emit-validator.js
This PR fixes rule `require-emit-validator` doesn't appear at [Available rules](https://eslint.vuejs.org/rules/) page.
> Fix rules index for `require-emit-validator`

- lib/rules/no-deprecated-destroyed-lifecycle.js
- tests/lib/rules/no-deprecated-destroyed-lifecycle.js
in Vue 3.x:
- `destroyed` lifecycle option has been renamed to `unmounted`
- `beforeDestroy` lifecycle option has been renamed to `beforeUnmount`
see in https://v3.vuejs.org/guide/migration/introduction.html#other-minor-changes.
so we should fix them instead of giving suggestion
> update `no-deprecated-destroyed-lifecycle` rule

- docs/rules/README.md
- docs/rules/no-this-in-before-route-enter.md
- lib/index.js
- lib/rules/no-this-in-before-route-enter.js
- tests/lib/rules/no-this-in-before-route-enter.js
> feat(no-this-in-before-router-enter): create rule

- lib/utils/index.js
- tests/lib/rules/object-curly-spacing.js
> Fix crash when using `objectsInObjects` option in `vue/object-curly-spacing` rule.

- lib/rules/syntaxes/slot-attribute.js
- lib/rules/syntaxes/slot-scope-attribute.js
- lib/rules/syntaxes/utils/can-convert-to-v-slot.js
- lib/rules/valid-v-slot.js
- lib/utils/index.js
- tests/lib/rules/no-deprecated-slot-attribute.js
- tests/lib/rules/no-deprecated-slot-scope-attribute.js
> Fix that `vue/no-deprecated-slot-attribute` and `vue/no-deprecated-slot-scope-attribute` rules had wrong auto-fix

- lib/rules/no-deprecated-props-default-this.js
- tests/lib/rules/no-deprecated-props-default-this.js
> Fix false positives for default with type Function in `vue/no-deprecated-props-default-this` rule

- lib/utils/indent-common.js
- tests/fixtures/script-indent/import-declaration-11.vue
> Fix false positives for trailing comma with import in `vue/script-indent` rule

- docs/.vuepress/components/eslint-code-block.vue
- docs/rules/README.md
- docs/rules/jsx-uses-vars.md
- docs/rules/script-setup-uses-vars.md
- lib/configs/base.js
- lib/index.js
- lib/rules/no-reserved-component-names.js
- lib/rules/no-unregistered-components.js
- lib/rules/script-setup-uses-vars.js
- lib/utils/index.js
- lib/utils/vue2-builtin-components.js
- lib/utils/vue3-builtin-components.js
- package.json
- tests/lib/rules/jsx-uses-vars.js
- tests/lib/rules/script-setup-uses-vars.js
- typings/eslint-plugin-vue/util-types/parser-services.ts
This PR adds `vue/script-setup-uses-vars` rule
The `vue/script-setup-uses-vars` rule that will find variables in `<script setup>` used in `<template>` and mark them as used.
refs #1248
> Add `vue/script-setup-uses-vars` rule

- lib/rules/no-mutating-props.js
- lib/utils/index.js
- tests/lib/rules/no-mutating-props.js
- typings/eslint-plugin-vue/util-types/utils.ts
> Update `vue/no-mutating-props` rule to support `<script setup>`

- lib/rules/no-mutating-props.js
- tests/lib/rules/no-mutating-props.js
> Fix false negatives for with `withDefaults` in `vue/no-mutating-props` rule.

- lib/rules/no-reserved-keys.js
- lib/utils/index.js
- lib/utils/ts-ast-utils.js
- tests/lib/rules/no-reserved-keys.js
- typings/eslint-plugin-vue/global.d.ts
- typings/eslint-plugin-vue/util-types/ast/es-ast.ts
- typings/eslint-plugin-vue/util-types/ast/ts-ast.ts
- typings/eslint-plugin-vue/util-types/utils.ts
> Update `vue/no-reserved-keys` rule to support `<script setup>`

- lib/rules/no-async-in-computed-properties.js
- tests/lib/rules/no-async-in-computed-properties.js
> Update `vue/no-async-in-computed-properties` rule to support `<script setup>`

- lib/rules/no-side-effects-in-computed-properties.js
- lib/utils/index.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
> Update `vue/no-side-effects-in-computed-properties` rule to support `<script setup>`

- lib/rules/require-prop-type-constructor.js
- lib/utils/index.js
- tests/lib/rules/require-prop-type-constructor.js
> Update `vue/require-prop-type-constructor` rule to support `<script setup>`

- lib/rules/no-lifecycle-after-await.js
- lib/utils/index.js
- tests/lib/rules/no-lifecycle-after-await.js
- typings/eslint-plugin-vue/util-types/utils.ts
> Update `vue/no-lifecycle-after-await` rule to support `<script setup>`

- lib/rules/require-valid-default-prop.js
- lib/utils/index.js
- tests/lib/rules/require-valid-default-prop.js
> Update `vue/require-valid-default-prop` rule to support `<script setup>`

- lib/rules/return-in-emits-validator.js
- lib/utils/index.js
- lib/utils/ts-ast-utils.js
- tests/lib/rules/return-in-emits-validator.js
- typings/eslint-plugin-vue/global.d.ts
- typings/eslint-plugin-vue/util-types/ast/ts-ast.ts
- typings/eslint-plugin-vue/util-types/utils.ts
> Update `vue/return-in-emits-validator` rule to support `<script setup>`

- lib/rules/require-default-prop.js
- lib/utils/index.js
- tests/lib/rules/require-default-prop.js
> Update `vue/require-default-prop` rule to support `<script setup>`

- lib/rules/no-setup-props-destructure.js
- tests/lib/rules/no-setup-props-destructure.js
> Update `vue/no-setup-props-destructure` rule to support `<script setup>`

- lib/rules/no-watch-after-await.js
- tests/lib/rules/no-watch-after-await.js
> Update `vue/no-watch-after-await` rule to support `<script setup>`

- lib/rules/no-template-shadow.js
- tests/lib/rules/no-template-shadow.js
> Update `vue/no-template-shadow` rule to support `setup()` and `<script setup>`

- lib/rules/prop-name-casing.js
- tests/lib/rules/prop-name-casing.js
> Update `vue/prop-name-casing` rule to support `<script setup>`

- lib/rules/require-prop-types.js
- tests/lib/rules/require-prop-types.js
> Update `vue/require-prop-types` rule to support `<script setup>`

- lib/rules/custom-event-name-casing.js
- tests/lib/rules/custom-event-name-casing.js
> Update `vue/custom-event-name-casing` rule to support `<script setup>`

- lib/rules/no-restricted-call-after-await.js
- tests/lib/rules/no-restricted-call-after-await.js
> Update `vue/no-restricted-call-after-await` rule to support `<script setup>`

- lib/rules/no-restricted-props.js
- lib/utils/index.js
- tests/lib/rules/no-restricted-props.js
> Update `vue/no-restricted-props` rule to support `<script setup>`

- lib/rules/no-unregistered-components.js
- tests/lib/rules/no-unregistered-components.js
> Update `vue/no-unregistered-components` rule to support `<script setup>`

- docs/rules/no-unsupported-features.md
- lib/rules/no-unsupported-features.js
- lib/rules/syntaxes/script-setup.js
- tests/lib/rules/no-unsupported-features/script-setup.js
> Update `vue/no-unsupported-features` rule to support `<script setup>`

- lib/rules/no-unused-properties.js
- tests/lib/rules/no-unused-properties.js
> Update `vue/no-unused-properties` rule to support `<script setup>`

- lib/rules/no-unused-refs.js
- tests/lib/rules/no-unused-refs.js
> Update `vue/no-unused-refs` rule to support `setup()` and `<script setup>`

- lib/rules/require-name-property.js
- tests/lib/rules/require-name-property.js
> Update `vue/require-name-property` rule to support `<script setup>`

- docs/rules/README.md
- docs/rules/valid-define-props.md
- lib/index.js
- lib/rules/valid-define-props.js
- lib/utils/index.js
- tests/lib/rules/valid-define-props.js
This PR adds `vue/valid-define-props` rule.
`vue/valid-define-props` rule reports `defineProps` compiler macros in the following cases:
- `defineProps` are referencing locally declared variables.
- `defineProps` has both a literal type and an argument. e.g. `defineProps<{/*props*/}>({/*props*/})`
- `defineProps` has been called multiple times.
- Props are defined in both `defineProps` and `export default {}`.
- Props are not defined in either `defineProps` or `export default {}`.
Related to #1248
> Add `vue/valid-define-props` rule

- docs/rules/README.md
- docs/rules/no-export-in-script-setup.md
- docs/user-guide/README.md
- lib/index.js
- lib/rules/no-export-in-script-setup.js
- package.json
- tests/lib/rules/no-export-in-script-setup.js
This PR adds `vue/no-export-in-script-setup` rule that disallows ES export in `<script setup>`.
Related to #1248
TODO 
https://github.com/vuejs/vue-eslint-parser/pull/115
> Add `vue/no-export-in-script-setup` rule

- docs/rules/README.md
- docs/rules/valid-define-emits.md
- lib/index.js
- lib/rules/valid-define-emits.js
- tests/lib/rules/valid-define-emits.js
This PR adds `vue/valid-define-props` rule.
`vue/valid-define-emits` rule reports `defineEmits` compiler macros in the following cases:
- `defineEmits` are referencing locally declared variables.
- `defineEmits` has both a literal type and an argument. e.g. `defineEmits<(e: 'foo')=>void>(['bar'])`
- `defineEmits` has been called multiple times.
- Custom events are defined in both `defineEmits` and `export default {}`.
- Custom events are not defined in either `defineEmits` or `export default {}`.
Related to #1248
> Add `vue/valid-define-emits` rule

- lib/rules/no-unsupported-features.js
- package.json
> Downgrade to `semver` compatible with Node v8

- docs/rules/README.md
- docs/rules/require-expose.md
- lib/index.js
- lib/rules/require-explicit-emits.js
- lib/rules/require-expose.js
- lib/rules/require-render-return.js
- lib/utils/index.js
- tests/lib/rules/require-expose.js
This PR adds `vue/require-expose` rule.
`vue/require-expose` rule that enforces the component to explicitly declare the exposed properties to the component using `expose`.
- [Vue RFCs - 0042-expose-api](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0042-expose-api.md)
> Add `vue/require-expose` rule

- docs/rules/no-unsupported-features.md
- lib/rules/no-unsupported-features.js
- lib/rules/no-unused-properties.js
- lib/rules/script-setup-uses-vars.js
- lib/rules/syntaxes/style-css-vars-injection.js
- lib/utils/style-variables/index.js
- package.json
- tests/lib/rules/no-parsing-error.js
- tests/lib/rules/no-unsupported-features/style-css-vars-injection.js
- tests/lib/rules/no-unused-properties.js
- tests/lib/rules/script-setup-uses-vars.js
This PR updates the following rules to support style CSS variable injection.
- `vue/no-parsing-error` rule
- `vue/no-unused-properties` rule
- `vue/script-setup-uses-vars` rule
- `vue/no-unsupported-features` rule
refs #1248
Related to https://github.com/vuejs/vue-eslint-parser/pull/118
> Update some rules to support style CSS vars injection

- lib/rules/comma-spacing.js
- lib/rules/dot-notation.js
- lib/rules/eqeqeq.js
- lib/rules/func-call-spacing.js
- lib/rules/keyword-spacing.js
- lib/rules/no-extra-parens.js
- lib/rules/no-restricted-syntax.js
- lib/rules/no-useless-concat.js
- lib/rules/prefer-template.js
- lib/rules/space-in-parens.js
- lib/rules/space-infix-ops.js
- lib/rules/space-unary-ops.js
- lib/rules/template-curly-spacing.js
- lib/utils/index.js
- lib/utils/style-variables/index.js
- package.json
- tests/lib/rules/comma-spacing.js
- tests/lib/rules/dot-notation.js
- tests/lib/rules/eqeqeq.js
- tests/lib/rules/func-call-spacing.js
- tests/lib/rules/no-extra-parens.js
- tests/lib/rules/no-restricted-syntax.js
- tests/lib/rules/no-useless-concat.js
- tests/lib/rules/prefer-template.js
- tests/lib/rules/space-in-parens.js
- tests/lib/rules/space-infix-ops.js
- tests/lib/rules/space-unary-ops.js
- tests/lib/rules/template-curly-spacing.js
- typings/eslint-plugin-vue/util-types/ast/ast.ts
- typings/eslint-plugin-vue/util-types/parser-services.ts
This PR updates the following core wrapper rules to support style CSS variable injection.
Related to #1248
Related to https://github.com/vuejs/vue-eslint-parser/pull/119
> Update core wrapper rules to support style CSS vars injection

- lib/utils/index.js
- tests/lib/rules/no-mutating-props.js
> Fix false positives for call expression in `vue/no-mutating-props` rule.

- docs/rules/README.md
- docs/rules/block-lang.md
- lib/index.js
- lib/rules/block-lang.js
- lib/utils/index.js
- tests/lib/rules/block-lang.js
This PR adds `vue/block-lang` rule.
`vue/block-lang` rule that  disallows the use of languages other than those available in the your application for the lang attribute of block elements.
close #1458
> Add `vue/block-lang` rule.

- lib/rules/require-default-prop.js
- tests/lib/rules/require-default-prop.js
- tests/lib/utils/index.js
> Fix false positives for type-only defineProps in `vue/require-default-prop` rule

- lib/rules/no-use-computed-property-like-method.js
- tests/lib/rules/no-use-computed-property-like-method.js
> fix(no-use-computed-property-like-method): Check the case CallExpression's arguments has include CallExpression at least

- docs/rules/README.md
- docs/rules/valid-v-memo.md
- lib/index.js
- lib/rules/valid-v-memo.js
- tests/lib/rules/valid-v-memo.js
- typings/eslint-plugin-vue/util-types/ast/ast.ts
This PR adds `vue/valid-v-memo` rule.
`vue/valid-v-memo` rule that enforce valid `v-memo` directives.
v-memo is a directive that will be added in Vue 3.2.
See also https://github.com/vuejs/docs/blob/3.2/src/api/directives.md#v-memo-
> Add `vue/valid-v-memo` rule

- lib/rules/no-restricted-v-bind.js
- lib/rules/valid-v-bind.js
- tests/lib/rules/no-restricted-v-bind.js
- tests/lib/rules/valid-v-bind.js
This PR update rules to support the `attr` modifier.
`attr` modifier that will be added in Vue 3.2.
See also https://github.com/vuejs/docs/blob/3.2/src/api/directives.md#v-bind
> Update `vue/no-restricted-v-bind` and `vue/valid-v-bind` rules to support `attr` modifier.

- docs/rules/no-unsupported-features.md
- lib/rules/no-unsupported-features.js
- lib/rules/syntaxes/v-bind-attr-modifier.js
- lib/rules/syntaxes/v-bind-prop-modifier-shorthand.js
- lib/rules/syntaxes/v-memo.js
- tests/lib/rules/no-unsupported-features/v-bind-attr-modifier.js
- tests/lib/rules/no-unsupported-features/v-bind-prop-modifier-shorthand.js
- tests/lib/rules/no-unsupported-features/v-memo.js
This PR updates `vue/no-unsupported-features` rule to support the Vue 3.2 syntaxes.
> Update `vue/no-unsupported-features` rule to support Vue 3.2 syntaxes.

- docs/rules/README.md
- docs/rules/no-v-text.md
- lib/index.js
- lib/rules/no-v-text.js
- tests/lib/rules/no-v-text.js
close #1435
Add rule `vue/no-v-text`.
- Fixable
- But in the case of selfclose element, it can't be fixed.
> Add `vue/no-v-text` rule

- docs/rules/README.md
- docs/rules/component-api-style.md
- lib/index.js
- lib/rules/component-api-style.js
- lib/utils/index.js
- package.json
- tests/lib/rules/component-api-style.js
This PR adds `vue/component-api-style` rule.
close #1624
> Add `vue/component-api-style` rule

- docs/rules/README.md
- docs/rules/no-restricted-class.md
- lib/index.js
- lib/rules/no-restricted-class.js
- tests/fixtures/no-restricted-class/forbidden.json
- tests/lib/rules/no-restricted-class.js
I had to refactor the rule somewhat from my original implementation to make it work with Typescript. This made it a bit harder to read, so any suggestions for improving that are welcome.
> Add vue/no-restricted-class rule

- docs/rules/README.md
- docs/rules/no-useless-template-attributes.md
- lib/index.js
- lib/rules/no-useless-template-attributes.js
- tests/lib/rules/no-useless-template-attributes.js
close #1637.
This PR adds`vue/no-useless-template-attributes` rule to prevent any useless attribute on `<template>` tags.
> Add vue/no-useless-template-attributes rule

- lib/rules/v-on-event-hyphenation.js
- tests/lib/rules/v-on-event-hyphenation.js
> Fix unable to autofix event name with `update:`.

- docs/rules/no-restricted-class.md
Doc template was copied from another rule
overlooked renaming one entry
> docs: fix typo in rule example

- lib/rules/valid-define-emits.js
- lib/rules/valid-define-props.js
- tests/lib/rules/valid-define-emits.js
- tests/lib/rules/valid-define-props.js
> Fix false positives for vars inside functions in `vue/valid-define-emits` and `vue/valid-define-props` rules

- lib/rules/multi-word-component-names.js
- tests/lib/rules/multi-word-component-names.js
> Fix false positive for filename in `vue/multi-word-component-names` rule

- docs/rules/component-api-style.md
- lib/rules/component-api-style.js
- tests/lib/rules/component-api-style.js
> Add `composition-vue2` style in `vue/component-api-style`

- docs/rules/README.md
- docs/rules/no-potential-component-option-typo.md
- docs/rules/no-restricted-custom-event.md
- docs/rules/no-restricted-props.md
- docs/rules/no-unused-vars.md
- docs/rules/require-emit-validator.md
- docs/rules/require-explicit-emits.md
- docs/rules/require-expose.md
- docs/rules/valid-next-tick.md
- tools/update-docs-rules-index.js
- tools/update-docs.js
See a similar PR here: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1576
> Docs: Add hints for rules that provide suggestions

- README.md
These changes further refine the README updates from [#1706](https://github.com/vuejs/eslint-plugin-vue/pull/1706):
- Spelling corrections ("abtract" becomes "abstract")
- Refined usage of definite articles (ex. "the")
- Modifies pluralized "ASTs" sentence to use singular grammar
- Replaces "Vue" with "Vue.js"
- Hyperlink single file components
- Clarifies "plain" JavaScript as "non-standard syntax"
> README Corrections

- docs/rules/README.md
- docs/rules/no-child-content.md
- lib/index.js
- lib/rules/no-child-content.js
- lib/utils/index.js
- tests/lib/rules/no-child-content.js
> Add `vue/no-child-content` rule

- docs/rules/README.md
- docs/rules/no-expose-after-await.md
- lib/index.js
- lib/rules/no-expose-after-await.js
- tests/lib/rules/no-expose-after-await.js
This PR adds `vue/no-expose-after-await` rule that reports the `expose()` after `await` expression.  
close #1704
> Add `vue/no-expose-after-await` rule

- .circleci/config.yml
- lib/rules/no-export-in-script-setup.js
- package.json
- tests/lib/rules/no-export-in-script-setup.js
> False positives for type-only exports in `vue/no-export-in-script-setup` rule

- lib/rules/no-mutating-props.js
- tests/lib/rules/no-mutating-props.js
This PR fixes two false reports in the `vue/no-mutating-props` rule.
1. fixes false negatives for `v-bind.sync`.
close #1714
2. fixes false positives for shadowed props.
close #1702
> Fix false positives and false negatives in `vue/no-mutating-props` rule

- docs/rules/README.md
- docs/rules/component-options-name-casing.md
- lib/index.js
- lib/rules/component-options-name-casing.js
- tests/lib/rules/component-options-name-casing.js
> Add `vue/component-options-name-casing` rule

- docs/rules/README.md
- docs/rules/prefer-separate-static-class.md
- lib/index.js
- lib/rules/prefer-separate-static-class.js
- tests/lib/rules/prefer-separate-static-class.js
> Add new rule `vue/prefer-separate-static-class`

- lib/rules/valid-define-emits.js
- lib/rules/valid-define-props.js
- tests/lib/rules/valid-define-emits.js
- tests/lib/rules/valid-define-props.js
> Fix false positives for import binding in `vue/valid-define-emits` and `vue/valid-define-props` rules

- tests/lib/rules/component-name-in-template-casing.js
To make the behavior described in #1722 explicit. Closes #1722.
> Add built-in component tests in `vue/component-name-in-template-casing`

- lib/rules/no-async-in-computed-properties.js
- lib/rules/no-side-effects-in-computed-properties.js
- tests/lib/rules/no-async-in-computed-properties.js
- tests/lib/rules/no-side-effects-in-computed-properties.js
> Report `$set` and `$nextTick` in computed properties

- lib/utils/indent-common.js
- tests/lib/rules/html-indent.js
> Fix crash on `<textarea>` without end tag in `vue/html-indent` rule

- lib/rules/no-boolean-default.js
- lib/rules/no-deprecated-props-default-this.js
- lib/rules/no-mutating-props.js
- lib/rules/no-reserved-keys.js
- lib/rules/no-reserved-props.js
- lib/rules/no-restricted-props.js
- lib/rules/prop-name-casing.js
- lib/rules/require-default-prop.js
- lib/rules/require-emit-validator.js
- lib/rules/require-explicit-emits.js
- lib/rules/require-prop-type-constructor.js
- lib/rules/require-prop-types.js
- lib/rules/require-valid-default-prop.js
- lib/rules/return-in-emits-validator.js
- lib/utils/index.js
- tests/lib/rules/require-explicit-emits.js
- tests/lib/utils/index.js
- typings/eslint-plugin-vue/util-types/utils.ts
> Fix false positive for unknown emits definition in `vue/require-explicit-emits` rule

- docs/rules/README.md
- docs/rules/no-v-text-v-html-on-component.md
- lib/index.js
- lib/rules/no-v-text-v-html-on-component.js
- tests/lib/rules/no-v-text-v-html-on-component.js
This PR adds `vue/no-v-text-v-html-on-component` rule that disallows the use of v-text / v-html on component.
close #1724
> Add `vue/no-v-text-v-html-on-component` rule

- lib/utils/property-references.js
- tests/lib/rules/no-undef-properties.js
- tests/lib/rules/no-unused-properties.js
> Add support for Vue2 functional component to `vue/no-unused-properties` and `vue/no-undef-properties` rules

- docs/rules/README.md
- docs/rules/object-shorthand.md
- lib/index.js
- lib/rules/object-shorthand.js
- tests/lib/rules/object-shorthand.js
This PR adds `vue/object-shorthand` rule that applies `object-shorthand` rule to expressions in `<template>`.
> Add `vue/object-shorthand` rule

- docs/rules/README.md
- docs/rules/quote-props.md
- lib/index.js
- lib/rules/quote-props.js
- lib/utils/index.js
- tests/lib/rules/quote-props.js
- typings/eslint-plugin-vue/util-types/parser-services.ts
- typings/eslint/index.d.ts
This PR adds `vue/quote-props` rule that applies `quote-props` rule to expressions in `<template>`.
> Add `vue/quote-props` rule

- lib/utils/indent-common.js
- tests/fixtures/script-indent/import-declaration-12.vue
> Fix false positives for import brace in `vue/script-indent` rule

- lib/rules/attributes-order.js
- tests/lib/rules/attributes-order.js
> Fix false positives for `v-bind="obj"` with `v-model` in `vue/attributes-order` rule

- lib/rules/no-extra-parens.js
- tests/lib/rules/no-extra-parens.js
> Fix false positives for CSS `v-bind()` in `vue/no-extra-parens` rule

- lib/rules/name-property-casing.js
- lib/rules/no-confusing-v-for-v-if.js
- lib/rules/no-unregistered-components.js
- tools/update-docs-rules-index.js
- tools/update-docs.js
As noticed by @privatenumber in https://github.com/vuejs/eslint-plugin-vue/pull/1763#discussion_r793596573.
> Meta: Fix `replacedBy` position

- lib/rules/no-unused-properties.js
- tests/lib/rules/no-unused-properties.js
> Fix false positives due to conflicts with other rules in `vue/no-unused-properties` rule

- docs/rules/README.md
- docs/rules/prefer-true-attribute-shorthand.md
- lib/index.js
- lib/rules/prefer-true-attribute-shorthand.js
- tests/lib/rules/prefer-true-attribute-shorthand.js
> Add `prefer-true-attribute-shorthand` rule

- docs/rules/README.md
- docs/rules/component-tags-order.md
- lib/rules/component-tags-order.js
- tests/lib/rules/component-tags-order.js
Fixes #1463.
This PR reflects the comments from @ota-meshi in #1512 . It yields a fix for each reported error, so eslint-disable comments work normally. Added a test case for eslint-disable comment.
> Auto-fix for vue/component-tags-order

- docs/rules/README.md
- docs/rules/prefer-prop-type-boolean-first.md
- docs/rules/prefer-true-attribute-shorthand.md
- lib/index.js
- lib/rules/prefer-prop-type-boolean-first.js
- tests/lib/rules/prefer-prop-type-boolean-first.js
> Add `prefer-prop-type-boolean-first` rule

- docs/rules/attribute-hyphenation.md
- lib/rules/attribute-hyphenation.js
- tests/lib/rules/attribute-hyphenation.js
> Fix #1808: Lint slots in attribute-hyphenation

- .github/workflows/CI.yml
- lib/rules/component-tags-order.js
- tests/lib/rules/component-tags-order.js
This PR adds some simple GitHub actions workflow.
I noticed that CircleCI didn't build some pull requests.
https://github.com/vuejs/eslint-plugin-vue/pull/1842#issuecomment-1094562455
If the problem persists for a long time, we should consider migrating to GitHub actions. However, it may be a temporary problem, so I would like to use it in parallel and see what happens.
> Add github workflows

- lib/utils/ts-ast-utils.js
- tests/lib/rules/require-valid-default-prop.js
> Fix false positives for script setup with ts literal type in `vue/require-valid-default-prop`

- docs/rules/no-v-for-template-key.md
fix the warning note on rule conflicts between  vue/no-v-for-template-key and vue/no-v-for-template-key-on-child
> Improve warning wording in `vue/no-v-for-template-key` docs

- docs/rules/no-v-for-template-key-on-child.md
fix the warning note on rule conflicts between vue/no-v-for-template-key and vue/no-v-for-template-key-on-child
> Improve warning wording in `vue/no-v-for-template-key-on-child` docs

- docs/rules/multi-word-component-names.md
Rule `vue/multi-word-component-names`
> Improve `vue/multi-word-component-names` rule docs

- docs/rules/README.md
- docs/rules/match-component-file-name.md
- lib/rules/match-component-file-name.js
- tests/lib/rules/match-component-file-name.js
- typings/eslint-plugin-vue/util-types/ast/es-ast.ts
fix #1816 
This plugin has always helped me.
Thank you very much.
There are two fixes.
1. Add 'Literal#raw' property
2. fixable match-component-file-name rule
> feat: fixable match-component-file-name rule

- lib/rules/block-tag-newline.js
- lib/rules/html-closing-bracket-newline.js
- lib/rules/html-closing-bracket-spacing.js
- tests/lib/rules/html-closing-bracket-newline.js
- tests/lib/rules/html-closing-bracket-spacing.js
Fixes #1879.
This should be released in the next major version since the bug fix could also be considered a breaking change.
> Enable `vue/html-closing-bracket-*` for top-level tags

- docs/rules/custom-event-name-casing.md
- lib/rules/custom-event-name-casing.js
- tests/lib/rules/custom-event-name-casing.js
> Change default casing of `vue/custom-event-name-casing` rule to camelCase

- docs/rules/README.md
- docs/rules/jsx-uses-vars.md
- docs/rules/script-setup-uses-vars.md
- docs/user-guide/README.md
- lib/configs/base.js
- lib/index.js
- lib/rules/script-setup-uses-vars.js
- package.json
- tests/lib/script-setup-vars.js
- tools/update-lib-index.js
This PR upgrades the parser to v9.
As a result, the following features have been deprecated.
- `vue/script-setup-uses-vars` rule
- `vue/setup-compiler-macros` environment
> Upgrade vue-eslint-parser

- package.json
Note that [eslint-plugin-eslint-plugin](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/) was not updated because v4.x doesn't seem to recognize ESLint rules in our codebase.
> Bump devDependencies to their newest versions

- lib/rules/define-macros-order.js
- tests/lib/rules/define-macros-order.js
In PR https://github.com/vuejs/eslint-plugin-vue/pull/1861 was decided to create separate PR for these improvements
There are two fixes here:
1. Fix extra newlines appear
2. Fix corner case `a();b() -> b()a();`
> Improve auto-fix for `vue/define-macros-order` rule

- lib/rules/prefer-import-from-vue.js
- tests/lib/rules/prefer-import-from-vue.js
For example, in the dts generated by unplugin-vue-components, we use `import '@vue/runtime-core'` to let TypeScript aware of the context. I guess similar cases where ppl import without names, they are probably intentional to rely on its side-effects.
https://github.com/antfu/vitesse/blob/168fe3560999b1132f4b7a4ffa0a3a67859b0ca7/src/components.d.ts
> fix(prefer-import-from-vue): skip side-effect import in `.d.ts` files

- lib/rules/no-unused-components.js
- tests/lib/rules/no-unused-components.js
Hi,
I just saw that ES Lint no longer detects unused components in Vue. So I checked in the no-unused-components rule and noticed a change [here](https://github.com/vuejs/eslint-plugin-vue/commit/ba2911413acd6c61cd966ab8471037ea4563451e#diff-431a19a18ef6f160af08eeb4967020d8d755928dd7091471ea32754aa419d684).
Before, a filter was applied to get all unused components and throw an error in context for everyone.
But after PR, return stop for and check only first component if it is used. Rule stop and is useless at the moment. I think we want to continue in for for all registered components.
> Fix regression on no-unused-components rule

- docs/rules/no-unsupported-features.md
- lib/rules/no-unsupported-features.js
- lib/rules/syntaxes/script-setup.js
- lib/rules/syntaxes/style-css-vars-injection.js
- tests/lib/rules/no-unsupported-features/script-setup.js
- tests/lib/rules/no-unsupported-features/style-css-vars-injection.js
> feat: support script setup and css var inj for vue 2.7

- lib/rules/component-name-in-template-casing.js
- tests/lib/rules/component-name-in-template-casing.js
> Update `vue/component-name-in-template-casing` rule to support `<script setup>`

- lib/rules/custom-event-name-casing.js
- lib/rules/no-restricted-custom-event.js
- lib/rules/require-explicit-emits.js
- tests/lib/rules/custom-event-name-casing.js
- tests/lib/rules/no-restricted-custom-event.js
- tests/lib/rules/require-explicit-emits.js
> Fix false negatives for template literals in `vue/custom-event-name-casing`, `vue/no-restricted-custom-event`, and `vue/require-explicit-emits` rules

- lib/utils/index.js
- tests/lib/rules/no-mutating-props.js
> fix: report delete operation for mutation props

- .circleci/config.yml
It seems that using typescript-eslint v4 and typescript v4.8 together breaks the AST due to incompatibility.
This PR changes typescript-eslint v4 tests to use typescript v4.7.
> Chore: fix typescript-eslint v4 test

- .github/workflows/CI.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- lib/rules/no-undef-components.js
- tests/lib/rules/no-undef-components.js
- tsconfig.json
- typings/eslint-plugin-vue/util-types/ast/es-ast.ts
- typings/eslint/index.d.ts
fix https://github.com/vuejs/eslint-plugin-vue/issues/1963
> Report type-only imports in `no-undef-components`

- .eslintrc.js
- docs/.vuepress/components/eslint-code-block.vue
- docs/.vuepress/config.js
- docs/.vuepress/enhanceApp.js
- docs/.vuepress/shim/globby.js
- docs/.vuepress/shim/module.js
- docs/rules/valid-define-emits.md
- docs/rules/valid-define-props.md
This PR modifies the documentation site demo so that it parses well using typescript.
https://deploy-preview-1972--eslint-plugin-vue.netlify.app/rules/valid-define-emits.html
https://deploy-preview-1972--eslint-plugin-vue.netlify.app/rules/valid-define-props.html
We'll need to clear the cache in netlify for this to take effect.
Related to https://github.com/vuejs/eslint-plugin-vue/pull/1968#issuecomment-1244839400
> Chore: ts-parser support in demo

- lib/rules/no-undef-components.js
- tests/lib/rules/no-undef-components.js
- typings/eslint-plugin-vue/util-types/ast/es-ast.ts
> Fix false positives for script setup with ts

- lib/rules/padding-line-between-tags.js
- tests/lib/rules/padding-line-between-tags.js
> Add `consistent` option to `vue/padding-line-between-tags`

- docs/user-guide/README.md
I noticed that VueCLI is in maintenance mode.
https://cli.vuejs.org/
So remove the way to install plugin via VueCLI.
close #1999
> Chore: remove from docs how to install via VueCLI

- lib/rules/no-ref-as-operand.js
- lib/utils/ref-object-references.js
- tests/lib/rules/no-ref-as-operand.js
> Fix false positives for uninitialized vars in `vue/no-ref-as-operand` rule

- docs/rules/no-required-prop-with-default.md
This PR fixes syntax errors and wrong options due to typos in the no-required-prop-with-default documentation.
> chore: fix no-required-prop-with-default doc

- docs/rules/padding-line-between-tags.md
Follow-up to #1982. CC @dev1437
> Add `consistent` option to `vue/padding-line-between-tags` docs

- docs/rules/README.md
- docs/rules/multiline-ternary.md
- docs/rules/no-required-prop-with-default.md
- lib/configs/no-layout-rules.js
- lib/index.js
- lib/rules/multiline-ternary.js
- tests/lib/rules/multiline-ternary.js
Wrap multiline ternary rule for vue.
Not sure about the indenting, maybe it is not an issue and would be handled by other rules. Looks strange.
> Create `vue/multiline-ternary` extension rule

- docs/rules/component-name-in-template-casing.md
- lib/rules/component-name-in-template-casing.js
- tests/lib/rules/component-name-in-template-casing.js
Currently the `component-name-in-template-casing` can't check globally registered components. This PR adds an option to explicitly list global components to check.
> Add `globals` option to `component-name-in-template-casing`

- docs/rules/no-restricted-class.md
- lib/rules/no-restricted-class.js
- tests/lib/rules/no-restricted-class.js
Closes #1877
This PR adds support for RegEx to the `no-restricted-class` rule and an update to the example in the docs.
I didn't add all the `buildMatcher` logic like in the example linked in the Issue (`no-restricted-custom-event`: https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/no-restricted-custom-event.js) because this rule seemed a little more straightforward.
Please let me know if you need anything else. Thanks!
> Allow restricting classes by regexp in `vue/no-restricted-class`

- docs/rules/no-restricted-static-attribute.md
From the conversation of https://github.com/vuejs/eslint-plugin-vue/pull/2020, after some unnecessary work and the valuable comments from @FloEdelmann, I then added a example to the document to make it clearer.
The example of the `element` property about the rule `vue/no-restricted-static-attribute`:
```javascript
options = [
{
"key": "style",
"element": /^([A-Z$][a-zA-Z_$]*)$/,
"message": "Using \"style\" is not allowed in custom component. Use \"class\" instead."
}
]
```
> Add example for rule `vue/no-restricted-static-attribute`

- lib/rules/no-textarea-mustache.js
- tests/lib/rules/no-textarea-mustache.js
> Ignore `<Textarea>` components in `vue/no-textarea-mustache`

- lib/rules/no-unused-properties.js
- lib/rules/require-prop-comment.js
- lib/utils/comments.js
- tests/lib/utils/comments.js
and add tests for them.
Follow-up to #2019. This was the commit that @czb3279338858 removed accidentally.
> Extract JSDoc comment recognition into util functions

- docs/rules/README.md
- docs/rules/require-name-property.md
- lib/rules/require-name-property.js
- tests/lib/rules/require-name-property.js
this is a pull request for issues: #2033
> Add suggestion for `vue/require-name-property` rule

- docs/rules/no-setup-props-destructure.md
The 1st argument for watch() should be a ref/reactive/getter function/array of ref, reactive, getter function. But in the example code, the watch callback has been used as the 1st argument
> fix(docs): update example code for watch()

- lib/rules/component-name-in-template-casing.js
- tests/lib/rules/component-name-in-template-casing.js
Vue does not treat built-in HTML tags as components, so them should be always excluded from verification.
e.g.
```html
<template>
<div/>
<template>
<script setup>
import Div from "component"
</script>
```
will be compiled to
```javascript
import Div from "component"
const __sfc__ = {
__name: 'App',
setup(__props) {
return (_ctx, _cache) => {
// `Div` is not used.
return (_openBlock(), _createElementBlock("div"))
}
}
```
> Ignore well known tags in `component-name-in-template-casing`

- docs/.vitepress/public/service-worker.js
I've noticed that the latest docs site doesn't display from some devices.
This is because previously we were using `@vuepress/plugin-pwa` and the cache is displayed by the service worker.
https://vuepress.vuejs.org/plugin/official/plugin-pwa.html
This PR adds a script to remove service workers.
See also below for how to remove.
https://github.com/NekR/self-destroying-sw
> Chore: add script to site that remove service-worker

- lib/utils/indent-common.js
- lib/utils/indent-ts.js
- package.json
- tests/fixtures/script-indent/ts-abstract-accessor-property-01.vue
- tests/fixtures/script-indent/ts-accessor-property-01.vue
- tests/fixtures/script-indent/ts-accessor-property-02.vue
- tests/fixtures/script-indent/ts-accessor-property-03.vue
- tests/fixtures/script-indent/ts-accessor-property-04.vue
- tests/fixtures/script-indent/ts-accessor-property-05.vue
- tests/fixtures/script-indent/ts-call-expression-01.vue
- tests/fixtures/script-indent/ts-instantiation-expression-01.vue
- tests/fixtures/script-indent/ts-new-expression-01.vue
- tests/fixtures/script-indent/ts-satisfies-operators-01.vue
- typings/eslint-plugin-vue/util-types/ast/es-ast.ts
This PR adds support for more typescript syntax to indent rules.
```ts
// Type parameters given to call expression, and new expressions
foo<T>(arg)
// ^^^
new Foo<T>(arg)
//     ^^^
// Instantiation expression
const ErrorMap = Map<string, Error>
//               ^^^^^^^^^^^^^^^^^^
// Satisfies operator
var a = {} satisfies Foo
//         ^^^^^^^^^
// Accessor property
class Foo {
accessor foo;
//^^^^^^^^^^^^
}
```
> Improve indent rule to support more ts syntax

- lib/rules/component-name-in-template-casing.js
- lib/utils/vue2-builtin-components.js
- tests/lib/rules/component-name-in-template-casing.js
Modified at Jan. 07.
This pull request is a fix for issue #2048.
Linter check is ignored if type-only import and registeredComponentsOnly=true.
The logic to check whether type-only import or not is the same as for [no-undef-components](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/no-undef-components.js#L127-L145).
> fix: [vue/component-name-in-template-casing] False positive for dynamic component in template

- lib/rules/component-api-style.js
- tests/lib/rules/component-api-style.js
in the component-api-style rule, the output used to join by `,` which would lead to something like: `you should use a,b or c`.
this simply adds a space such that it becomes `a, b or c`.
i also added a test to hit this branch of code since there wasn't already one.
> fix (vue/component-api-style): add spacing around comma in report message

- tests/lib/rules/max-attributes-per-line.js
passing a multiline max value as an object wasn't tested before, this simply adds such a test.
> test (vue/max-attributes-per-line): add test for max value as object

- lib/rules/define-macros-order.js
- tests/lib/rules/define-macros-order.js
as per #2067 
```ts
code: `
<script setup>
defineEmits(['update:test'])
console.log('test1')
defineProps({ test: Boolean })
</script>
`,
output: `
<script setup>
defineEmits(['update:test'])
defineProps({ test: Boolean })
console.log('test1')
</script>
`,
options: optionsEmitsFirst,
```
the output ends up as:
```html
<script setup>
defineProps({ test: Boolean })
defineEmits(['update:test'])
console.log('test1')
</script>
```
which contradicts the options passed (emits _then_ props).
this PR fixes that and adds tests for some gaps we had.
> fix (vue/define-macros-order): hoist secondary expressions correctly

- lib/rules/no-undef-components.js
- tests/lib/rules/no-undef-components.js
> Fix false positives for circular references in <script setup> in `vue/no-undef-components`

- docs/rules/attributes-order.md
- lib/rules/attributes-order.js
- tests/lib/rules/attributes-order.js
This PR adds `[ 'ATTR_STATIC', 'ATTR_DYNAMIC', 'ATTR_SHORTHAND_BOOL' ] ` attribute to `vue/attributes-order`. And `OTHER_ATTR` become an alias for [ 'ATTR_STATIC', 'ATTR_DYNAMIC', 'ATTR_SHORTHAND_BOOL' ]
close https://github.com/vuejs/eslint-plugin-vue/issues/1728, close #1870
> Add new attributes order for dynamic and static props

- .eslintignore
- .gitignore
- docs/.vitepress/vite-plugin.ts
- lib/rules/order-in-components.js
- package.json
I noticed that the demo on the order-in-components rule documentation page is not working.
https://eslint.vuejs.org/rules/order-in-components.html
This PR modifies the source code to make it work in the demo.
The cause seems to be that the conversion by [`@originjs/vite-plugin-commonjs`](https://www.npmjs.com/package/@originjs/vite-plugin-commonjs) does not work.
This PR will fix the problem by changing this repository to do the same logic as `@originjs/vite-plugin-commonjs`.
> Chore: Fix order-in-components rule doc page demo not working

- docs/rules/no-deprecated-destroyed-lifecycle.md
- docs/rules/no-deprecated-dollar-listeners-api.md
- docs/rules/no-deprecated-v-on-native-modifier.md
Added a migration guide in further reading.
Vue 3 Migration Guide - v-on.native modifier removed
https://v3-migration.vuejs.org/breaking-changes/v-on-native-modifier-removed.html
Vue 3 Migration Guide - VNode Lifecycle Events
https://v3-migration.vuejs.org/breaking-changes/vnode-lifecycle-events.html#migration-strategy
Vue 3 Migration Guide - $listeners removed
https://v3-migration.vuejs.org/breaking-changes/listeners-removed.html
> Link to Vue 3 migration guide in docs

- docs/rules/multi-word-component-names.md
Ref: [Is "all HTML elements are a single word" grammatically correct?](https://ell.stackexchange.com/questions/334216/is-all-html-elements-are-a-single-word-grammatically-correct)
> docs: fixed grammar

- lib/utils/index.js
This PR fixes a bug found in https://github.com/vuejs/eslint-plugin-vue/pull/2101#pullrequestreview-1383007618.
> Fixed false negatives in `vue/camelcase` when using ESLint>=v8.38

- docs/rules/no-unused-properties.md
- lib/rules/no-unused-properties.js
- lib/utils/property-references.js
- tests/lib/rules/no-unused-properties.js
Ref #1636, this is my first stab at adding an option to not treat generic access to `this` as 'using' properties / data / computed, etc. If this is the right approach, I can try adding tests if needed. It's more general I think than what you'd proposed in that issue, but for my use case it works well.
> Add option to show warnings when props could be accessed via this

- .eslintrc.js
- lib/utils/index.js
I looked into #2145 and found that the CI #2145 test was failing due to rules not compatible with ESLint v8.40.
This PR fixes that issue.
> Fixed rules incompatible with ESLint v8.40.

- lib/processor.js
Related issue: nothing
Related PR: https://github.com/vuejs/vue-eslint-parser/pull/190
This PR’s purpose is to support ESLint flat config.
Loading eslint-plugin-vue in flat config, ESLint check processor’s name and version in meta object.
https://github.com/eslint/eslint/blob/main/lib/config/flat-config-array.js#L220
https://github.com/eslint/eslint/blob/main/lib/config/flat-config-array.js#L45-L76
> feat(processor): export meta object for flat config

- lib/index.js
- lib/meta.js
- lib/processor.js
- tests/lib/meta.js
- tools/update-lib-index.js
This PR is similar to #2145, but this PR adds a meta object to the plugin itself.
It seems that the plugin also needs it.
https://eslint.org/docs/latest/extend/plugins#metadata-in-plugins
> Add meta object to the plugin

- docs/rules/no-mutating-props.md
- lib/rules/no-mutating-props.js
- lib/utils/index.js
- tests/lib/rules/no-mutating-props.js
Ref https://github.com/vuejs/eslint-plugin-vue/issues/1371
> Add `shallowOnly` option to `vue/no-mutating-props`

- lib/utils/index.js
- typings/eslint-plugin-vue/util-types/utils.ts
This PR changes `utils.defineScriptSetupVisitor` to also visit `defineSlots` and `defineOptions`.
This change has been separated from #2154.
> Added support for `defineOptions` and `defineSlots` to `defineScriptSetupVisitor`

- docs/rules/define-macros-order.md
- lib/rules/define-macros-order.js
- lib/utils/index.js
- tests/lib/rules/define-macros-order.js
- typings/eslint-plugin-vue/util-types/utils.ts
This PR adds support for `defineOptions` and `defineSlots` in `vue/define-macros-order` rule. (Default behavior is unchanged.)
This PR also includes changes that make `utils.defineScriptSetupVisitor` visit `defineSlots` and `defineOptions`.
> Add support for `defineOptions` and `defineSlots` to `vue/define-macros-order` rule

- lib/utils/ts-ast-utils.js
- tests/lib/rules/require-explicit-emits.js
- typings/eslint-plugin-vue/util-types/utils.ts
> Add support for new `defineEmits` type syntax to `vue/require-explicit-emits` rule

- lib/rules/multi-word-component-names.js
- lib/utils/index.js
- tests/lib/rules/multi-word-component-names.js
- typings/eslint-plugin-vue/util-types/utils.ts
> Added support for `defineOptions` to `vue/multi-word-component-names` rule

- lib/rules/no-reserved-component-names.js
- lib/utils/index.js
- tests/lib/rules/no-reserved-component-names.js
- typings/eslint-plugin-vue/util-types/utils.ts
related to https://github.com/vuejs/eslint-plugin-vue/issues/2118
> Added support for `defineOptions` to `vue/no-reserved-component-names` rule

- lib/rules/component-definition-name-casing.js
- tests/lib/rules/component-definition-name-casing.js
> Add support for `defineOptions` to `vue/component-definition-name-casing` rule

- lib/rules/match-component-file-name.js
- tests/lib/rules/match-component-file-name.js
> Add support for `defineOptions` to `vue/match-component-file-name` rule

- lib/rules/no-restricted-component-options.js
- tests/lib/rules/no-restricted-component-options.js
> Add support for `defineOptions` to `vue/no-restricted-component-options` rule

- lib/rules/padding-lines-in-component-definition.js
- tests/lib/rules/padding-lines-in-component-definition.js
> Add support for `defineOptions` to `vue/padding-lines-in-component-definition` rule

- docs/rules/index.md
- docs/rules/prefer-define-options.md
- lib/index.js
- lib/rules/prefer-define-options.js
- tests/lib/rules/prefer-define-options.js
This PR adds `vue/prefer-define-options` rule that enforce use of `defineOptions` instead of default export.
> Add `vue/prefer-define-options` rule

- docs/rules/index.md
- docs/rules/valid-define-emits.md
- docs/rules/valid-define-options.md
- docs/rules/valid-define-props.md
- lib/index.js
- lib/rules/valid-define-emits.js
- lib/rules/valid-define-options.js
- lib/rules/valid-define-props.js
- tests/lib/rules/valid-define-emits.js
- tests/lib/rules/valid-define-options.js
- tests/lib/rules/valid-define-props.js
This PR adds `vue/valid-define-options` rule that checks whether `defineOptions` compiler macro is valid.
> Add `vue/valid-define-options` rule

- lib/rules/no-deprecated-router-link-tag-prop.js
> Add `additionalProperties` to `vue/no-deprecated-router-link-tag-prop` schema

- lib/rules/no-dupe-keys.js
- tests/lib/rules/no-dupe-keys.js
> Extend `vue/no-dupe-keys` to support `<script setup>`

- lib/rules/no-duplicate-attr-inheritance.js
- tests/lib/rules/no-duplicate-attr-inheritance.js
> Add support for `defineOptions` to `vue/no-duplicate-attr-inheritance` rule

- lib/rules/no-undef-properties.js
- tests/lib/rules/no-undef-properties.js
fixes #2183
---
This PR fixes unknown properties to be ignored from check when encountered.
There was a false positive if the user did not enable type information for rules in the ESLint configuration and defined the prop type externally.
> Fix false positive for unknown prop in `vue/no-undef-properties` rule

- docs/rules/index.md
- docs/rules/no-console.md
- lib/index.js
- lib/rules/no-console.js
- tests/lib/rules/no-console.js
> Add `vue/no-console` rule

- docs/rules/index.md
- docs/rules/require-macro-variable-name.md
- lib/index.js
- lib/rules/require-macro-variable-name.js
- tests/lib/rules/require-macro-variable-name.js
> Add `vue/require-macro-variable-name` rule

- docs/rules/index.md
- docs/rules/require-typed-ref.md
- lib/index.js
- lib/rules/require-typed-ref.js
- lib/utils/index.js
- lib/utils/ref-object-references.js
- tests/lib/rules/require-typed-ref.js
> Add `vue/require-typed-ref` rule

- docs/rules/index.md
- docs/rules/no-restricted-component-names.md
- lib/index.js
- lib/rules/no-restricted-component-names.js
- tests/lib/rules/no-restricted-component-names.js
closes #2182 
---
I slightly changed the schema format that was proposed in the issue, as in [no-restricted-props](https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/no-restricted-props.js) rule.
> Add `vue/no-restricted-component-names` rule

- docs/rules/max-lines-per-block.md
- lib/rules/max-lines-per-block.js
- tests/lib/rules/max-lines-per-block.js
> Add `vue/max-lines-per-block` rule

- lib/rules/require-typed-ref.js
> Fix typo in `vue/require-typed-ref` message

- lib/rules/no-console.js
- lib/utils/index.js
- tests/lib/rules/no-console.js
> Restrict the `vue/no-console` rule to the `<template>` block

- docs/rules/index.md
- docs/rules/no-use-v-else-with-v-for.md
- docs/rules/no-use-v-if-with-v-for.md
- lib/index.js
- lib/rules/no-use-v-else-with-v-for.js
- lib/rules/no-use-v-if-with-v-for.js
- tests/lib/rules/no-use-v-else-with-v-for.js
> Add new `vue/no-use-v-else-with-v-for`

- lib/rules/attribute-hyphenation.js
- tests/lib/rules/attribute-hyphenation.js
> Prevent auto fix `vue/attribute-hyphenation` when it breaks props

- docs/rules/experimental-script-setup-vars.md
- docs/rules/index.md
- docs/rules/name-property-casing.md
- docs/rules/no-confusing-v-for-v-if.md
- docs/rules/no-invalid-model-keys.md
- docs/rules/no-unregistered-components.md
- docs/rules/script-setup-uses-vars.md
- docs/rules/v-on-function-call.md
- tools/lib/categories.js
- tools/update-docs-rules-index.js
- tools/update-docs.js
Needed for https://github.com/vuejs/eslint-plugin-vue/pull/2222#issuecomment-1626900433. Note that this currently does not change any configs at all.
Also updates emojis in docs to distinguish rules with type "problem" and deprecated rules:
<table>
<tr>
<th scope=col> Rule type
<th scope=col> Previous emoji
<th scope=col> New emoji
<tr>
<td>Rules with type "problem"
<td><code>:warning:</code> :warning:
<td><code>:warning:</code> :warning: (no change)
<tr>
<td>Deprecated rules
<td><code>:warning:</code> :warning: 
<td><code>:no_entry_sign:</code> :no_entry_sign: 
<tr>
<td>Removed rules
<td><code>:no_entry_sign:</code> :no_entry_sign: 
<td><code>:no_entry:</code> :no_entry: 
</table>
> Allow deprecated rules in configs

- docs/rules/no-deprecated-model-definition.md
- lib/rules/no-deprecated-model-definition.js
- tests/lib/rules/no-deprecated-model-definition.js
Follow-up to #2238.
I now tested the (unreleased) rule in a large codebase that is currently prepared for upgrading to Vue 3. There, I noticed that allowing anything different than `modelValue`/`update:modelValue` or `model-value`/`update:model-value` does not make sense: You'd still need to change `v-model` to `v-model:fooBar` in the actual Vue 3 migration if your model specified `fooBar`/`update:fooBar`.
So it's better to either rename the model definition to `modelValue`/`update:modelValue` or `model-value`/`update:model-value` and keep using `v-model`, or to rename the model definition to `fooBar`/`update:fooBar` and also update all `v-model`s to `:fooBar="…" @update:fooBar="… = $event"`, and after the Vue 3 migration change it to `v-model:fooBar` with #2237.
Therefore, I changed the …
> Only allow modelValue in `vue/no-deprecated-model-definition`

- lib/rules/no-setup-props-destructure.js
- tests/lib/rules/no-setup-props-destructure.js
- closes #1933
- closes #2007
- closes #2092
Previously, the rule did not catch some reactivity-breaking uses of `props`.
Accessing a prop in a function call.
```vue
<script setup>
const props = defineProps({ count: Number })
const count = ref(props.count)
</script>
```
Accessing a prop in an object.
```vue
<script setup>
const props = defineProps({ count: Number })
const counter = { count: props.count }
</script>
```
Accessing a prop in an array.
```vue
<script setup>
const props = defineProps({ count: Number })
const counts = [props.count]
</script>
```
Accessing a prop in a nested object structure.
```vue
<script setup>
const props = defineProps({ count: Number })
const counters = [{ counts: [props.count] }]
</script>
```
> Improve the `vue/no-setup-props-destructure` rule

- docs/rules/use-v-on-exact.md
`use-v-on-exact` rule documentation shows a useless code block in the "options" section, it should instead show "Nothing." for coherence and consistency with other rules documentation.
> Docs: fix options for use-v-on-exact

- lib/rules/define-emits-declaration.js
- lib/rules/define-props-declaration.js
- lib/rules/require-typed-ref.js
- lib/rules/valid-define-emits.js
- lib/rules/valid-define-options.js
- lib/rules/valid-define-props.js
- lib/utils/indent-common.js
- lib/utils/indent-ts.js
- lib/utils/index.js
- lib/utils/ts-utils/ts-ast.js
- tests/integrations/eslint-plugin-import.js
- typings/eslint-plugin-vue/util-types/ast/es-ast.ts
https://github.com/typescript-eslint/typescript-eslint/pull/5384
#2256 missed a few
> fix: replace typeParameters with typeArguments

- lib/rules/prefer-define-options.js
- tests/lib/rules/prefer-define-options.js
> Insert `defineOptions` after import declarations in `vue/prefer-define-options`

- lib/rules/require-toggle-inside-transition.js
- tests/lib/rules/require-toggle-inside-transition.js
fix: #2302 
Also, the following case that tansition with attribute `appear` should be valid.
```
<template>
<Transition appear>
<div />
</Transition>
</template>
```
> Fix require-toggle-inside-transition should respect "<slot>", "v-bind:key", attribute "appear"

- docs/rules/define-emits-declaration.md
- lib/rules/define-emits-declaration.js
- tests/lib/rules/define-emits-declaration.js
Fixes: #2242 
This PR adds support for a stricter check to always use the "type literal" type based `defineEmits` signature introduced in Vue 3.3.
i.e. 
```ts
defineEmits<{
// this line is good
change: [value: string]
// this line is bad
(e: 'change', value: string): void
}>()
```
Not included in this PR is a strict check on the use of named tuples. Maybe it can be added as an extra sub-option to the `type-literal` option in the future, if possible.
> Add support for stricter `type-literal` option in `vue/define-emits-declaration`

- lib/rules/define-emits-declaration.js
- lib/rules/define-props-declaration.js
- lib/rules/require-typed-ref.js
- lib/rules/valid-define-emits.js
- lib/rules/valid-define-options.js
- lib/rules/valid-define-props.js
- lib/utils/indent-common.js
- lib/utils/indent-ts.js
- lib/utils/index.js
- lib/utils/ts-utils/ts-ast.js
#2292
typeParameters was still being accessed when typeArguments is undefined
> fix: avoid calling typeParameters getter

- lib/configs/vue3-strongly-recommended.js
- lib/rules/v-on-event-hyphenation.js
> Make `vue/v-on-event-hyphenation` autofixable by default in Vue 3

- docs/rules/no-deprecated-slot-attribute.md
- lib/rules/no-deprecated-slot-attribute.js
- lib/rules/syntaxes/slot-attribute.js
- tests/lib/rules/no-deprecated-slot-attribute.js
closes: https://github.com/vuejs/eslint-plugin-vue/issues/2313
I have not yet updated the documentation for this rule. If the content of this PR and issue is accepted, I will start working on those.
> Add new option to specify tags to ignore `vue/no-deprecated-slot-attribute`

- lib/rules/define-emits-declaration.js
- tests/lib/rules/define-emits-declaration.js
- typings/eslint-plugin-vue/util-types/ast/es-ast.ts
> Fix crash for TSFunctionType with `type-literal` option in `vue/define-emits-declaration` rule

- lib/rules/jsx-uses-vars.js
- lib/rules/script-setup-uses-vars.js
- lib/utils/index.js
- tests/lib/rules/jsx-uses-vars.js
- tests/lib/rules/script-setup-uses-vars.js
- typings/eslint/index.d.ts
This PR is a follow-up PR for #2331.
I checked again and found that it still uses APIs that will be removed in ESLint v9. This PR aims to refactor those source codes to improve compatibility with ESLint v9.
> Improve compatibility with ESLint v9 (take2)

- docs/rules/index.md
- docs/rules/no-boolean-default.md
- docs/rules/no-deprecated-v-is.md
- eslint-internal-rules/no-invalid-meta-docs-categories.js
- eslint.config.js
- lib/rules/html-indent.js
- lib/rules/no-boolean-default.js
- lib/rules/no-deprecated-scope-attribute.js
- lib/rules/no-deprecated-slot-attribute.js
- lib/rules/no-deprecated-slot-scope-attribute.js
- lib/rules/no-deprecated-v-is.js
- lib/rules/no-unsupported-features.js
- lib/rules/padding-line-between-blocks.js
- lib/rules/padding-line-between-tags.js
- lib/rules/script-indent.js
- lib/rules/v-if-else-key.js
This PR enables the `catchNoFixerButFixableProperty` rule option of the [`eslint-plugin/require-meta-fixable` rule](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-fixable.md), which increases the number of false-positives, but also catches two non-fixable rules that were incorrectly described.
> Document non-fixable rules correctly

- docs/rules/no-v-text-v-html-on-component.md
- lib/rules/no-v-text-v-html-on-component.js
- tests/lib/rules/no-v-text-v-html-on-component.js
Fixes https://github.com/vuejs/eslint-plugin-vue/issues/2321
This is my first time contributing to this project, so feel free to provide any feedback or suggestions～
> feat(no-v-text-v-html-on-component): add `allow` option

- lib/rules/no-unused-emit-declarations.js
- tests/lib/rules/no-unused-emit-declarations.js
try to fix https://github.com/vuejs/eslint-plugin-vue/issues/2337
> fix(no-unused-emit-declarations): detect emits in templates

- lib/rules/require-explicit-emits.js
- tests/lib/rules/require-explicit-emits.js
This rule has a similar issue to https://github.com/vuejs/eslint-plugin-vue/issues/2337.
The unused emits in the template were not detected, so this PR fixes that.
> fix(require-explicit-emits): detect template emits

- lib/utils/property-references.js
- tests/lib/rules/no-unused-properties.js
fixes #2344 
@FloEdelmann could you please mark my issue as open again?
> feat(no-unused-properties): mark $props.<prop> as used

- docs/rules/define-macros-order.md
- lib/rules/define-macros-order.js
- lib/utils/index.js
- tests/lib/rules/define-macros-order.js
- typings/eslint-plugin-vue/util-types/utils.ts
will close https://github.com/vuejs/eslint-plugin-vue/issues/2235
I'll be thankful for any suggestions on these TODOs.
- open to suggestions for a better option name…
- should we include `defineExpose` within the `order` schema? There is a potential conflict in the options, like:
`{ order: ['defineExpose', 'defineProps'], defineExposeLast: true }`.
- any other test cases should we add to verify the fixer?
- update the docs.
> feat(define-macros-order): add `defineExposeLast` option

- docs/rules/no-unsupported-features.md
- lib/rules/html-quotes.js
- lib/rules/no-unsupported-features.js
- lib/rules/syntaxes/v-bind-same-name-shorthand.js
- lib/utils/index.js
- package.json
- tests/lib/rules/html-button-has-type.js
- tests/lib/rules/html-quotes.js
- tests/lib/rules/no-deprecated-slot-attribute.js
- tests/lib/rules/no-unsupported-features/v-bind-same-name-shorthand.js
- tests/lib/rules/no-unused-components.js
- tests/lib/rules/v-bind-style.js
- tests/lib/rules/valid-v-bind.js
> Upgrade vue-eslint-parser and add support for v-bind same-name shorthand

- docs/index.md
The described situation has changed/improved since the notice was added, so I think the notice can be dropped.
> Remove Vue 3 syntax status notice from docs

- docs/rules/define-macros-order.md
- docs/rules/no-unsupported-features.md
- lib/rules/define-macros-order.js
- lib/rules/no-undef-properties.js
- lib/rules/no-unsupported-features.js
- lib/rules/no-unused-emit-declarations.js
- lib/rules/no-unused-properties.js
- lib/rules/require-prop-types.js
- lib/rules/syntaxes/define-model.js
- lib/utils/index.js
- lib/utils/ref-object-references.js
- tests/fixtures/utils/ref-object-references/ref-objects/defineModel01/result.vue
- tests/fixtures/utils/ref-object-references/ref-objects/defineModel01/source.vue
- tests/fixtures/utils/ref-object-references/ref-objects/defineModel02/result.vue
- tests/fixtures/utils/ref-object-references/ref-objects/defineModel02/source.vue
- tests/lib/rules/define-macros-order.js
- tests/lib/rules/no-ref-as-operand.js
- tests/lib/rules/no-ref-object-reactivity-loss.js
- tests/lib/rules/no-undef-properties.js
- tests/lib/rules/no-unsupported-features/define-model.js
- tests/lib/rules/no-unused-emit-declarations.js
- tests/lib/rules/no-unused-properties.js
- tests/lib/rules/require-prop-types.js
- tests/lib/utils/ref-object-references.js
- typings/eslint-plugin-vue/util-types/ast/es-ast.ts
- typings/eslint-plugin-vue/util-types/utils.ts
> Add support for defineModel

- lib/rules/enforce-style-attribute.js
- lib/rules/no-mutating-props.js
- lib/rules/no-template-shadow.js
- lib/rules/no-unused-properties.js
- tests/lib/rules/no-unused-properties.js
This PR fixes a type error when running `npm run tsc`.
It also fixes false positive edge cases for Vuex support added in #2276.
> Fix type errors caused by TypeScript

- docs/rules/index.md
- docs/rules/no-restricted-static-attribute.md
- docs/rules/no-restricted-v-bind.md
- docs/rules/no-restricted-v-on.md
- lib/index.js
- lib/rules/no-restricted-v-on.js
- tests/lib/rules/no-restricted-v-on.js
This is an attempt at solving https://github.com/vuejs/eslint-plugin-vue/issues/2243
Keen for feedback 🫡
> Add new `vue/no-restricted-v-on` rule

- docs/rules/valid-v-bind.md
This syntax gets removed at the parser level and so will never be enforced, even in Vue 2.
See https://github.com/vuejs/eslint-plugin-vue/pull/2357.
> Remove v-bind shorthand syntax from list of examples rule will catch.

- lib/rules/no-unused-emit-declarations.js
- tests/lib/rules/no-unused-emit-declarations.js
Fix #2387
Don't know how to describe the commit message properly.
Feel free to edit it.
> fix(no-unused-emit-declarations): error in render functions

- lib/rules/define-macros-order.js
- tests/lib/rules/define-macros-order.js
Not a pro when it comes to AST stuff, but I think this should do it.
Should fix https://github.com/vuejs/eslint-plugin-vue/issues/2371
> fix: support multiple macro calls in vue/define-macros-order

- lib/rules/require-expose.js
- tests/lib/rules/define-macros-order.js
- tests/lib/rules/no-child-content.js
- tests/lib/rules/no-required-prop-with-default.js
- tests/lib/rules/no-unused-vars.js
- tests/lib/rules/prefer-true-attribute-shorthand.js
- tests/lib/rules/require-emit-validator.js
- tests/lib/rules/require-explicit-emits.js
- tests/lib/rules/require-expose.js
- tests/lib/rules/valid-next-tick.js
As reported by ESLint v9 in https://github.com/vuejs/eslint-plugin-vue/actions/runs/7875486583/job/21487466235?pr=2171
> Add missing suggestions and messages to tests

- lib/rules/no-useless-mustaches.js
- tests/lib/rules/no-useless-mustaches.js
Fixes #2384
I looked up the parser specification for the [inside tag case](https://html.spec.whatwg.org/multipage/parsing.html#data-state) for potential additional cases which would differ:
- `<`: already covered in the issue
- `EOF`: would already be an error
- `\0`: I guess/hope no one would do this but there is a [difference](https://play.vuejs.org/#eNp9kE1rAjEQhv9KmIsX2Ra8iRTa4qE9tKXtcS7LOq6r2UlIJrqw5L+bRPw4iLfJ+zwJ72SEV2urfSCYw0Kot7oWekFWahzVBPF5omLMxzQiL55uFJiC+MbwumurrTecXhiLCY3pbafJfVvpDHuEuSoks1prc/gsmbhA03PebKjZ3cm3fsgZwo8jT25PCBcmtWtJTnj590VDmi+wN6ugk/0A/pI3OuSOJ+0t8CrVvvFK24/eGicdt/9+OQixPy+Vi2YzFh8hfeP7g9WvdWfVrNxDjhCPljJ9KQ==)
- `&`: there are cases when combining the text with either before or [after the mustache](https://play.vuejs.org/#eNp9kLtuAjEQRX/FmiI0aFPQERQpiSiSIomSl …
> fix(no-useless-mustaches): escape < in fixes

- lib/rules/syntaxes/slot-attribute.js
- lib/rules/syntaxes/slot-scope-attribute.js
- lib/rules/syntaxes/utils/can-convert-to-v-slot.js
- tests/lib/rules/no-deprecated-slot-attribute.js
- tests/lib/rules/no-deprecated-slot-scope-attribute.js
Currently doing a Vue 2.7 migration in an old codebase...
I was thinking it should be possible to autofix cases of the deprecated `slot` attribute where the element is not `<template>`, by wrapping it in a `<template v-slot>`.
This PR demonstrates it, and the auto-fixes worked fine in my codebase. Want to get feedback to see if I'm missing any edge-cases.
> feat(no-deprecated-slot-attribute): improve autofix to wrap `<template v-slot>`

- docs/rules/no-setup-props-reactivity-loss.md
- lib/rules/no-setup-props-reactivity-loss.js
- tests/lib/rules/no-setup-props-reactivity-loss.js
Fix https://github.com/vuejs/eslint-plugin-vue/issues/2352
> fix(no-setup-props-reactivity-loss): false negative for conditional expressions

- docs/rules/require-explicit-slots.md
- lib/rules/require-explicit-slots.js
- tests/lib/rules/require-explicit-slots.js
solves https://github.com/vuejs/eslint-plugin-vue/issues/2391
1. The update now allows `node.key` to be a string, supporting both `Identifier` and `Literal` types. It also skips over dynamic slot names since `slotNameAttr` only detects nodes with `directive: false`.
2. The `memberNode` type has been narrowed down to only include `TSMethodSignature` and `TSPropertySignature`.
- `foo(): any`
- `foo: () => any`
> fix(require-explicit-slots): recognize slot names enclosed in quotes

- docs/rules/no-v-html.md
Removed further reading section. The link doesn't provide reader more information about the subject. It just redirects to a datadog marketing page.
> Remove dead link from docs

- docs/user-guide/index.md
- typings/eslint-plugin-vue/util-types/ast/jsx-ast.ts
- typings/eslint-plugin-vue/util-types/ast/ts-ast.ts
typescript-eslint repo master was renamed to main.
> Update links to GitHub repos with changed main branch name

- lib/rules/enforce-style-attribute.js
- lib/rules/require-explicit-slots.js
- lib/utils/index.js
- lib/utils/selector.js
- lib/utils/style-variables/index.js
resolves this https://github.com/vuejs/eslint-plugin-vue/pull/2397#discussion_r1479773243 as a perf improvement
> perf: remove unnecessary second filter for type narrowing

- lib/rules/v-for-delimiter-style.js
- tests/lib/rules/v-for-delimiter-style.js
fixes https://github.com/vuejs/vue-eslint-parser/issues/226 (`vue-eslint-parser` issue!)
Maybe we can simply ignore all 'Punctuator' type token, without the need to specifically declare `token.type !== 'Punctuator' || (token.value !== ')' && token.value !== ',')`?
> fix(v-for-delimiter-style): ignore Punctuator token

- docs/rules/index.md
- docs/rules/order-in-components.md
- lib/rules/order-in-components.js
- tests/lib/rules/order-in-components.js
> feat(order-in-components): add side effects suggestions

- lib/rules/no-restricted-class.js
- tests/lib/rules/no-restricted-class.js
> fix(no-restricted-class): error in empty value

- .github/workflows/CI.yml
- package.json
- tests/lib/rules/custom-event-name-casing.js
Fixes #2443.
ESLint v9 stable has been released now: https://eslint.org/blog/2024/04/eslint-v9.0.0-released/
> Allow ESLint v9 as peer dependency

- lib/rules/no-use-computed-property-like-method.js
- tests/lib/rules/no-use-computed-property-like-method.js
fixes #2037 
Before: The judgment of `maybeFunction` skipped `LogicalExpression`;
Now: The `LogicalExpression` will also be included in the judgment of whether it may be a function (by checking it's `left` and `right` node); if one of them may be, then calls like methods are allowed.
> fix(no-use-computed-property-like-method): extract LogicalExpression

- lib/rules/no-unused-properties.js
- tests/lib/rules/no-unused-properties.js
Changes are aimed at improving Pinia support.
Following Pinia methods will be checked: `mapGetters`, `mapState`, `mapWritableState` and `mapActions`, when no-unused-properties will be enabled.
Its not possible to support `mapStores` easily because de result variable is the store id + Store ([See more](https://pinia.vuejs.org/cookbook/options-api.html#Giving-access-to-the-whole-store)) and would fail always.
Fixes #1675.
> Support Pinia methods in `vue/no-unused-properties`

- lib/utils/index.js
- tests/lib/rules/require-default-prop.js
The rule `vue/require-default-prop` return an error for all optional props when using `withDefaults` and a spread operator as second argument
The rule seems to return an empty object if something different from `Property` is found. Ignoring it instead will allow the check for at least props defined in the file
> fix: Prevent spread operator from disabling the rule

- package.json
Upgrade `vue-eslint-parser` to the latest v9.4.3 to fix #2421.
> chore: upgrade vue-eslint-parser to v9.4.3

- docs/user-guide/index.md
Related to: https://github.com/vuejs/eslint-plugin-vue/issues/2448
📚 Description
This PR adds an example on how to use this plugin with TypeScript, which is a common use case.
📜 Notes
The getting started guide is getting a bit hard to follow with a lot of warnings, duplicated text for each configuration style. It might worth extracting the `.eslintrc` format to a different subpage like it is done in [the official eslint docs](https://eslint.org/docs/latest/use/configure/configuration-files).
> docs: add an example on how to use custom parser with flat config

- docs/.vitepress/build-system/build.mts
- docs/.vitepress/config.mts
- docs/.vitepress/vite-plugin.mts
- lib/rules/order-in-components.js
- package.json
Resolves #2492 
This PR uses [pathe](https://www.npmjs.com/package/pathe) instead of the built-in path module from Node.js to handle the different file separators between Windows and other operating systems.
I tested it, and works, it's only a draft because I'm not sure you want to add another dependency to the project, even if it is only a dev dependency.
> docs: fix build on windows

- docs/.vitepress/build-system/src/eslint.mjs
- docs/user-guide/index.md
- package.json
* Follows #2481.
* I somehow missed this in #2478, that's probably causing errors like [this](https://togithub.com/vuejs/eslint-plugin-vue/pull/2481#issuecomment-2182473055).
Fixes this issue in https://eslint.vuejs.org/rules/max-lines-per-block.html:
> ![Screenshot_20240703_145453](https://github.com/vuejs/eslint-plugin-vue/assets/202916/ac93e903-00b2-41f1-8de7-1b345f44eced)
because `SourceCode` is needed in
https://github.com/vuejs/eslint-plugin-vue/blob/c64bf9448099bd7ca3512dca705c81730afec4ab/lib/rules/max-lines-per-block.js#L7
> Improve docs

- lib/configs/flat/base.js
- lib/configs/flat/vue2-essential.js
- lib/configs/flat/vue2-recommended.js
- lib/configs/flat/vue2-strongly-recommended.js
- lib/configs/flat/vue3-essential.js
- lib/configs/flat/vue3-recommended.js
- lib/configs/flat/vue3-strongly-recommended.js
- tools/update-lib-flat-configs.js
This PR changes the all flat configs' name separator from `:` to `/`.
As ESLint recommended use `/` as the separator.
Refs:
- [Configuration Naming Conventions](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions)
> fix: change flat config name separator to `/`

- lib/rules/max-props.js
- tests/lib/rules/max-props.js
While trying out the new unreleased props rule, I noticed that the rule only highlights the very first prop if violated, instead of the entire props block. I think this is slightly confusing. 
Therefore I changed it to report the parent node and therefore the entire props block.
> Improve error range for `vue/max-props`

- docs/rules/define-macros-order.md
- docs/rules/index.md
- lib/rules/define-macros-order.js
- package.json
- tests/lib/rules/define-macros-order.js
**⚠️ Newbie alert ⚠️**
_This is my very first contribution to this project so I hope I did the things well; but don't hesitate to tell me what is not right._ 😄
This PR adds the ability to use the [define macro order rule](https://eslint.vuejs.org/rules/define-macros-order.html#defineexposelast-true) for any macro specified in the `order` array. This allows users to specify `definePage` for example or any macro wanted.
Basically, I added a `CallExpression` that checks whether the Identifier is included into the `order` array but **not** in the `ORDER_SCHEMA` as this is already checked with earlier events (`onDefineExposeExit` etc.)
I removed the `enum` from the `properties` of the rule as it's no longer limited to `ORDER_SCHEMA`. And finally, I've added new tests.
I also have some …
> Update rule `define-macros-order` for custom macros

- docs/rules/index.md
- docs/rules/max-template-depth.md
- lib/index.js
- lib/rules/max-template-depth.js
- tests/lib/rules/max-template-depth.js
This PR addresses issue https://github.com/vuejs/eslint-plugin-vue/issues/2524.
I believe it successfully implements the rule, that the test cases are exhaustive enough. 
Hoping for feedback! :)
> Implements proposed max-template-depth rule

- lib/rules/attribute-hyphenation.js
- tests/lib/rules/attribute-hyphenation.js
Close https://github.com/vuejs/eslint-plugin-vue/issues/2521
I'll just submit a pr first, so if there are any changes that need to be made please just point them out ❤️
> fix(attribute-hyphenation): skip auto-fix when suffixed with `.sync`

- lib/rules/syntaxes/slot-attribute.js
- tests/lib/rules/no-deprecated-slot-attribute.js
Fixes an edge-case where the slot is dynamic derived from a `v-for`.
Previously, it would move the `slot` directive in a new `<template>` above the `v-for`, which broke it.
Now, it also moves the `v-for` to the new `<template>`.
> fix(no-deprecated-slot-attribute): handle v-for with dynamic slot

- lib/rules/syntaxes/slot-attribute.js
- lib/rules/syntaxes/utils/can-convert-to-v-slot.js
- tests/lib/rules/no-deprecated-slot-attribute.js
> Warning: I made this PR on top of https://github.com/vuejs/eslint-plugin-vue/pull/2529 but I needed to open a PR against the `master` branch for it to show up in this repo
The `#slot` syntax doesn't work when passed into a native HTML `<div>` element for obvious reasons.
However, the old `slot="name"` syntax works... [Demo](https://vue2-sfc-playground.vercel.app/#eNqVUDsOwjAMvYplBhZoJMaqILgDY5YCAQI0sWoXBtS747QVVAxIbO8Xv9hP3BBl98ZhjgXva08C7KShlQ2F6QWFSsRVdCvFKQMoDv7eAYX7WFEMLgjknpcWp+pNLQ52nwW+RVGv5MNxZAFsz57hEesrv+NmNHvA/zRNUsd3w6525e+KDyrMaFWcodfSWuZVSdmFY9BDPVPcDgZbzKFTkqaXTNziWYQ4N6YJdD1l+nOj1nqhHSwJZo4rnWcxvWxtaLF9AdGye9Q=)
This can happen (and has happened in my work project) when a dynamic component renders a `div` to fallback when certain conditions aren't met:
> fix(no-deprecated-slot-attribute): no fix for dynamic components

- lib/rules/attribute-hyphenation.js
- lib/rules/require-prop-types.js
- tests/lib/rules/attribute-hyphenation.js
> fix(attribute-hyphenation): apply to v-model directive

- docs/rules/require-toggle-inside-transition.md
- lib/rules/require-toggle-inside-transition.js
- tests/lib/rules/require-toggle-inside-transition.js
> feat(require-toggle-inside-transition): add additionalDirectives option (#2535)

- lib/index.d.ts
- package.json
closes #2523 
these are really rudimentary, but at least it's a start
> Add TypeScript declarations for configs

- lib/rules/require-valid-default-prop.js
- lib/utils/index.js
- tests/lib/rules/require-valid-default-prop.js
This PR modifies the `vue/require-valid-default-prop` rule to add support for props destructure.
> Add support for props destructure to `vue/require-valid-default-prop` rule

- lib/rules/require-default-prop.js
- lib/utils/index.js
- tests/lib/rules/require-default-prop.js
This PR modifies the `vue/require-default-prop` rule to add support for props destructure.
> Add support for props destructure to `vue/require-default-prop` rule

- lib/rules/no-boolean-default.js
- lib/utils/index.js
- tests/lib/rules/no-boolean-default.js
This PR modifies the `vue/no-boolean-default` rule to add support for props destructure.
> Add support for props destructure to `vue/no-boolean-default` rule

- lib/rules/no-required-prop-with-default.js
- lib/utils/index.js
- tests/lib/rules/no-required-prop-with-default.js
This PR modifies the `vue/no-required-prop-with-default` rule to add support for props destructure.
> Add support for props destructure to `vue/no-required-prop-with-default` rule

- lib/rules/no-restricted-props.js
- lib/utils/index.js
- tests/lib/rules/no-restricted-props.js
This PR modifies the `vue/no-restricted-props` rule to add support for props destructure.
> Add support for props destructure to `vue/no-restricted-props` rule

- lib/rules/no-setup-props-reactivity-loss.js
- tests/lib/rules/no-setup-props-destructure.js
- tests/lib/rules/no-setup-props-reactivity-loss.js
This PR modifies the `vue/no-setup-props-reactivity-loss` rule to add support for props destructure.
> Add support for props destructure to `vue/no-setup-props-reactivity-loss` rule

- lib/utils/index.js
- tests/lib/utils/vue-component.js
I was testing `eslint-config-vue` integration with TypeScript projects.
I was surprised to find out that the rule `vue/multi-word-component-names` does not error on `.tsx` files, such as `Foo.tsx`, while it correctly showed errors for `Foo.jsx` and `Foo.vue`.
Digging into the rule source code I found that it's because `isVueFile('Foo.tsx')` always returns false:
https://github.com/vuejs/eslint-plugin-vue/blob/2dc606ca589ff5cdcd197c3c64ace7e575a6347d/lib/rules/multi-word-component-names.js#L120
> fix(utils): also recognize .tsx files as Vue files

- lib/index.d.ts
- typings/eslint/index.d.ts
Adds proper types for the configs (in the yet unreleased index.d.ts).
If this PR gets rejected, note that the `configs` key is still incorrectly typed with the current `index.d.ts` file.
If only a fix for that is wanted, without the types for the configs themselves, consider this:
```diff
configs: {
-    [name in keyof ConfigName]: any
+    [name in ConfigName]: any
}
```
> fix: type declarations for configs

- lib/index.d.ts
Thanks for adding TypeScript declarations in the latest v9.29.0.
I found an issue when using the new declaration. In the `lib/index.d.ts`, the `Linter` namespace is pointing to `typings/eslint/index.d.ts`. However, `typings/` is not included in the [final NPM package](https://unpkg.com/browse/eslint-plugin-vue@9.29.0/), therefore the declarations in `index.d.ts` is not working.
This issue can be fixed by adding a single line `import type { Linter } from 'eslint'` as shown in this PR. 
Other code-styling changes included in this PR are made by Prettier based on `eslint-plugin-vue`'s Prettier config.
---
Just FYI, the latest eslint has already includes TypeScript declarations, which means you don't need `@types/eslint` and perhaps also `typings/eslint/index.d.ts` anymore once …
> Fix Linter type import in index.d.ts

- lib/rules/require-valid-default-prop.js
- tests/lib/rules/require-valid-default-prop.js
This PR fixes false negatives and false positives when using destructuring and initial assignment.
It also fixes an issue where we weren't checking the return value of factory functions in `<script setup>`.
fixes #2578
> Fix false negatives and false positives in `vue/require-valid-default-prop` rule

- lib/rules/define-macros-order.js
- tests/lib/rules/define-macros-order.js
> fix(define-macros-order): skip TSModuleDeclaration statements

- docs/rules/no-reserved-component-names.md
- lib/rules/no-reserved-component-names.js
- tests/lib/rules/no-reserved-component-names.js
resolve #2556
Add an option to control case-sensitive matching for HTML element names to be considered conflicting. For instance, `Button` would be allowed, but `button` would still be disallowed.
> feat(no-reserved-component-names): add case sensitive option

- lib/rules/no-unused-emit-declarations.js
- lib/rules/require-explicit-emits.js
related to #2585
Refactored to store the `defineEmits` variable name for checking `defineEmits` variable name usage in the template.
> refactor: store the defineEmits variable name

- docs/rules/index.md
- docs/rules/no-empty-component-block.md
- lib/rules/no-empty-component-block.js
- package.json
- tests/lib/rules/no-empty-component-block.js
resolve #2564
~~Chose this approach is because I couldn't find a better way to handle reporting & fixing each `emptyBlock` within a for loop,  as removing the first block will affect the range of the second block😵‍💫.~~
UPDATE: support auto delete empty blocks
> feat(no-empty-component-block): support auto fix

- docs/rules/index.md
- docs/rules/prefer-use-template-ref.md
- lib/rules/prefer-use-template-ref.js
- tests/lib/rules/prefer-use-template-ref.js
This PR adds `shallowRef` support to rule `prefer-use-template-ref`.
> fix(prefer-use-template-ref): add support for `shallowRef`

- docs/rules/no-duplicate-attr-inheritance.md
- lib/rules/no-duplicate-attr-inheritance.js
- tests/lib/rules/no-duplicate-attr-inheritance.js
resolve #2596.
- since this will result in fewer errors, should we still consider adding an option to control this?
- multi root could also be a group of `v-if` / `v-else` / `v-else` nodes. Should we consider treating it as a "single" root?
> feat(no-duplicate-attr-inheritance): ignore multi root

- docs/rules/no-v-text-v-html-on-component.md
- lib/rules/no-v-text-v-html-on-component.js
- lib/utils/index.js
- tests/lib/rules/no-v-text-v-html-on-component.js
> feat(no-v-text-v-html-on-component): add ignore namespace option

- docs/rules/attribute-hyphenation.md
- docs/rules/v-on-event-hyphenation.md
- lib/rules/attribute-hyphenation.js
- lib/rules/v-on-event-hyphenation.js
- tests/lib/rules/attribute-hyphenation.js
- tests/lib/rules/v-on-event-hyphenation.js
resolve #2605 
Add an `exclude` option to exclude specified tag names in the `vue/attribute-hyphenation` and `vue/v-on-event-hyphenation` rules.
> feat: add `ignoreTags` option

- package.json
This PR will temporarily work around the ESLint style issue by pinning `@stylistic/eslint-plugin` to 2.10.
related to #2618
> Chore: workaround for ESLint Stylistic issue

- docs/rules/block-order.md
- docs/rules/component-tags-order.md
- docs/rules/index.md
- lib/configs/flat/vue2-recommended.js
- lib/configs/flat/vue3-recommended.js
- lib/configs/vue2-recommended.js
- lib/configs/vue3-recommended.js
- lib/rules/block-order.js
- lib/rules/component-tags-order.js
instead of `vue/component-tags-order`
> Add `vue/block-order` to recommended configs

- lib/rules/custom-event-name-casing.js
- tests/lib/rules/custom-event-name-casing.js
See https://github.com/vuejs/eslint-plugin-vue/blame/207eb981df3bbab5d63846d7456d0925ab82394c/lib/rules/custom-event-name-casing.js#L89-L93
> Remove legacy schema from `vue/custom-event-name-casing`

- docs/rules/restricted-component-names.md
This PR adds the missing value for option `allow` to rule `vue/restricted-component-names` docs.
> docs: fix missing options `allow` value

- docs/user-guide/index.md
> docs: align example variable name

- docs/rules/order-in-components.md
- lib/rules/order-in-components.js
- tests/lib/rules/order-in-components.js
* Related to #2125
* Fixes #2399
> Add `slots`+`expose` to `vue/order-in-components` default order

- README.md
- docs/index.md
> Change Versioning Policy

- docs/rules/index.md
- docs/rules/no-required-prop-with-default.md
- lib/configs/flat/vue2-recommended.js
- lib/configs/flat/vue3-recommended.js
- lib/configs/vue2-recommended.js
- lib/configs/vue3-recommended.js
- lib/rules/no-required-prop-with-default.js
> Add `vue/no-required-prop-with-default` to recommended preset configs

- docs/.vitepress/config.mts
| Without this PR | With this PR |
|-----------------|--------------|
| ![grafik](https://github.com/user-attachments/assets/619921f9-7876-4870-a65e-ba833e36a417) | ![grafik](https://github.com/user-attachments/assets/cb9db620-a2ec-473f-a3fb-fc109fd39106) |
> Fix sidebar categories in rule docs

- lib/rules/sort-keys.js
Related to
* #1865
* #1866
* #2166
Since this options is unused and undocumented, I think we should remove it in the next major version. Adding it again can be a backwards-compatible enhancement.
> Remove unused `runOutsideVue` option from `vue/sort-keys`

- docs/rules/index.md
- docs/rules/no-multiple-slot-args.md
- lib/rules/no-multiple-slot-args.js
This phrasing is more correct 🙂
> fix(no-multiple-slot-args): improve grammar of description

- docs/rules/index.md
- docs/rules/no-multiple-objects-in-class.md
- lib/rules/no-multiple-objects-in-class.js
This phrasing is more correct 🙂
> fix(no-multiple-objects-in-class): improve grammar of description

- lib/rules/attributes-order.js
- lib/rules/block-lang.js
- lib/rules/block-order.js
- lib/rules/html-comment-content-newline.js
- lib/rules/html-comment-indent.js
- lib/rules/html-indent.js
- lib/rules/max-attributes-per-line.js
- lib/rules/max-len.js
- lib/rules/no-restricted-call-after-await.js
- lib/rules/no-restricted-component-options.js
- lib/rules/no-restricted-static-attribute.js
- lib/rules/script-indent.js
- lib/rules/v-slot-style.js
See https://ajv.js.org/json-schema.html#oneof:
> The data is valid if it matches exactly one JSON Schema from this array.
See https://ajv.js.org/json-schema.html#anyof:
> The data is valid if it is valid according to one or more JSON Schemas in this array.
> Change `anyOf` to `oneOf` in rule schemas to make intent clearer

- tests/lib/rules/require-valid-default-prop.js
The documentation for Vue props, as well as the `require-valid-default-prop` rule, are not clear if setting a default value of `null` to a prop with type `Object` requires a factory function:
```js
props: {
foo: { type: Object, default: () => null },
},
```
vs.
```js
props: {
foo: { type: Object, default: null },
},
```
On one hand, `typeof null === 'object'`. On the other hand, the reason for using a factory function is so each instance of the prop has a different object reference, whereas `null` is always the same reference anyway.
This adds a valid test case for setting a default value of `null` to a prop with type `Object` without a factory function. The test passes, so it's evident that `null` does not require a factory function.
> feat: Add a test case to require-valid-default-prop

- package.json
This PR changes vue-eslint-parser to peer dependency.
I make it easy to change the version used by making vue-eslint-parser a peer dependency.
Also, recent npm installs peer dependencies automatically by default, so I don't think it will be inconvenient for users.
> Change `vue-eslint-parser` to peer dependency

- docs/user-guide/index.md
- lib/configs/base.js
- tools/update-lib-configs.js
> Change legacy base config so that vue-eslint-parser is only used for `.vue`

- docs/rules/index.md
- docs/rules/no-v-for-template-key.md
- docs/rules/no-v-model-argument.md
- docs/rules/valid-model-definition.md
- docs/rules/valid-v-bind-sync.md
- lib/rules/no-v-for-template-key.js
- lib/rules/no-v-model-argument.js
- lib/rules/valid-model-definition.js
- lib/rules/valid-v-bind-sync.js
These rules are currently in configs for Vue 2 (in all of `essential`, `strongly-recommended` and `recommended`), but not in configs for Vue 3:
- [vue/no-custom-modifiers-on-v-model](https://eslint.vuejs.org/rules/no-custom-modifiers-on-v-model.html)
→ could be useful as an uncategorized rule for Vue 3 to disallow [custom modifiers](https://vuejs.org/guide/components/v-model.html#handling-v-model-modifiers), so let's not deprecate it
- [vue/no-multiple-template-root](https://eslint.vuejs.org/rules/no-multiple-template-root.html)
→ could be useful as an uncategorized rule for Vue 3 to prevent [attribute inheritance problems](https://vuejs.org/guide/components/attrs.html#attribute-inheritance-on-multiple-root-nodes), so let's not deprecate it
- …
> Deprecate Vue 2 only rules

- lib/rules/max-props.js
- tests/lib/rules/max-props.js
> fix(max-props): count unique keys

- docs/rules/no-ref-as-operand.md
- lib/rules/no-ref-as-operand.js
- tests/lib/rules/no-ref-as-operand.js
> feat(no-ref-as-operand): use `ref.value` to replace `ref` when emit 

- lib/utils/ts-utils/ts-types.js
- tests/lib/rules/require-valid-default-prop.js
> feat: handle generic parameter types

- docs/rules/index.md
- docs/rules/no-import-compiler-macros.md
- lib/index.js
- lib/rules/no-import-compiler-macros.js
- tests/lib/rules/no-import-compiler-macros.js
> feat: add `vue/no-import-compiler-macros` rule

- docs/user-guide/index.md
Since version 10.0.0 this has become a peer dependency which is not installed by Yarn.
See https://github.com/vuejs/eslint-plugin-vue/pull/2670
> Add vue-eslint-parser to Yarn install

- lib/index.d.ts
This PR fixes #2699
Refs:
- https://github.com/vuejs/eslint-plugin-vue/pull/2648
> fix: sync `.eslintrc` configs name changes

- lib/utils/index.js
- tests/lib/rules/prefer-use-template-ref.js
This PR fixes #2696 and adds test cases for it.
When multiple script blocks exist and walk AST of node `Program`, `inScriptSetup(node)` will return false.
The range of node Program contains the range of script setup block.
> fix: fix walking program AST when multiple script blocks

- lib/rules/no-export-in-script-setup.js
- tests/lib/rules/no-export-in-script-setup.js
support autofix for no-export-in-script-setup rule. 
relates to #2690
> fix(no-export-in-script-setup): better report location

- README.md
This PR replaces Circle CI status badge with GitHub workflow CI status badge.
As CircleCI integration has been removed.
> docs: replace circle ci badge with github workflow badge

- lib/rules/no-duplicate-attr-inheritance.js
- lib/rules/no-unused-refs.js
This PR fixes typecheck of project.
> fix: fix typecheck

- docs/user-guide/index.md
Fixes #2708. We forgot to update the documentation in #2648.
> docs: fix old config names

- .github/workflows/check-for-resources-update.yml
This PR prevents the schedule workflow running on forks.
> ci: prevent action running on forks

- docs/rules/define-emits-declaration.md
Generally, it’s better to use `===` whenever possible.
> docs: use `===` instead of `==`

- lib/rules/no-dupe-keys.js
- tests/lib/rules/no-dupe-keys.js
> fix(no-dupe-keys): detect props destructure rename

- docs/rules/no-bare-strings-in-template.md
- lib/rules/no-bare-strings-in-template.js
- tests/lib/rules/no-bare-strings-in-template.js
resolve #2613
related #2730, #2695
> feat(no-bare-strings-in-template): `allowlist` support regex

- docs/rules/define-props-destructuring.md
- docs/rules/index.md
- lib/index.js
- lib/rules/define-props-destructuring.js
- tests/lib/rules/define-props-destructuring.js
> feat: add `define-props-destructuring` rule

- docs/rules/no-multiple-template-root.md
- lib/rules/no-multiple-template-root.js
- tests/lib/rules/no-multiple-template-root.js
> feat(no-multiple-template-root): support disallowComments property

- .changeset/crazy-impalas-pick.md
- docs/rules/no-restricted-html-elements.md
- lib/rules/no-restricted-html-elements.js
- tests/lib/rules/no-restricted-html-elements.js
This addition helps reduce duplication in a scenario like the following.
<br />
This:
```ts
'vue/no-restricted-html-elements': [
'error',
{ element: 'a', message: 'Use `<ULink>`.' },
{ element: 'NuxtLink', message: 'Use `<ULink>`.' },
{ element: 'RouterLink', message: 'Use `<ULink>`.' },
],
```
Becomes this:
```ts
'vue/no-restricted-html-elements': [
'error',
{
element: ['a', 'RouterLink', 'NuxtLink'],
message: 'Use `<ULink>`.'
},
],
```
<br />
Note: I purposely didn't change the key from `element` to `elements` to avoid breaking changes.
> feat(no-restricted-html-elements): support array of elements

- .changeset/neat-swans-argue.md
- .gitignore
- eslint.config.mjs
- lib/index.d.ts
- package.json
- tools/generate-typegen.mjs
Add TypeScript IntelliSense support via `eslint-typegen` with ESM migration for ESLint v9.0+ compatibility.
- Integrate `eslint-typegen` for TypeScript definitions
- Convert `eslint.config.js` to `eslint.config.mjs` (required for eslint-typegen)
- Install with `--legacy-peer-deps` due to ESLint version requirements
- Update all imports to ESM format
- TypeScript IntelliSense for ESLint configurations
- Modern ESLint v9.0+ compatibility
- Improved developer experience with type safety
| Before(No TypeScript Support) | After(TypeScript IntelliSense Active) |
|--------|--------|
| <img width="554" alt="No TypeScript Support" src="https://github.com/user-attachments/assets/52133b31-eba9-41e3-b1bb-e0be8643e3ad" /> | <img width="562" alt="TypeScript IntelliSense Active" …
> feat: add TypeScript IntelliSense support with eslint-typegen

- .changeset/beige-teams-camp.md
- docs/rules/no-deprecated-slot-attribute.md
- lib/rules/no-deprecated-slot-attribute.js
- lib/rules/syntaxes/slot-attribute.js
- lib/utils/index.js
- tests/lib/rules/no-deprecated-slot-attribute.js
Adds #2710
- #2710
---
Adds an `ignoreParents: string[]` option to `no-deprecated-slot-attribute` to allow ignoring web-component usecases:
````vue
<template>
<web-component>
<Entry slot="entry" />
</web-component>
</template>
````
Preview:
- [`rules/no-deprecated-slot-attribute` (new)](https://deploy-preview-2784--eslint-plugin-vue.netlify.app/rules/no-deprecated-slot-attribute.html)
- [`rules/no-deprecated-slot-attribute` (current)](https://eslint.vuejs.org/rules/no-deprecated-slot-attribute.html)
---
Note to self: Next PR(s):
- Increase the specificity of the rule test case assertions https://github.com/vuejs/eslint-plugin-vue/pull/2773#discussion_r2176359714
> feat(no-deprecated-slot-attribute): add ignoreParents option

- .changeset/eight-camels-refuse.md
- tools/generate-typegen.mjs
Fixes TypeScript compatibility issues between eslint-plugin-vue and ESLint types by setting `includeAugmentation: false` in the eslint-typegen configuration.
Set `includeAugmentation: false` to generate standalone type definitions instead of augmenting ESLint's built-in types. This approach is also used by [@antfu/eslint-config](https://github.com/antfu/eslint-config/blob/95963ac345d27cd06a4eeb5ebc16e1848cb2fd81/scripts/typegen.ts#L29-L33).
Closes  #2788
> fix: resolve TypeScript compatibility issues with eslint-typegen

- .changeset/true-pumas-open.md
- docs/rules/index.md
- docs/rules/no-negated-condition.md
- lib/index.js
- lib/rules/no-negated-condition.js
- tests/lib/rules/no-negated-condition.js
Resolve #2769
Related PR https://github.com/vuejs/eslint-plugin-vue/pull/2794
> Add new `vue/no-negated-condition` rule

- tests/lib/rules/no-deprecated-slot-attribute.js
Continuation of https://github.com/vuejs/eslint-plugin-vue/pull/2773#discussion_r2176359714
- https://github.com/vuejs/eslint-plugin-vue/pull/2773#discussion_r2176359714
> It might be helpful to include more detailed error information, such as `line`, `column`, `endLine`, and `endColumn`...
---
This PR converts all error assertions for `no-deprecated-slot-attribute` to include both error message and full location checks.
---
Is this kind of PR appreciated? If not, we can close it. If yes, I will create one for each rule one at a time.
> test(no-deprecated-slot-attribute): make tests more strict

- tests/lib/rules/array-bracket-newline.js
- #2793
---
This PR converts all error assertions for `array-bracket-newline` to include both error message and full location checks.
> test(array-bracket-newline): make tests more strict

- tests/lib/rules/arrow-spacing.js
- #2793
---
This PR converts all error assertions for `arrow-spacing` to include both error message and full location checks.
> test(arrow-spacing): make tests more strict

- tests/lib/rules/attribute-hyphenation.js
- #2793
---
This PR converts all error assertions for `attribute-hyphenation` to include both error message and full location checks.
> test(attribute-hyphenation): make tests more strict

- tests/lib/rules/block-spacing.js
- #2793
---
This PR converts all error assertions for `block-spacing` to include both error message and full location checks.
> test(block-spacing): make tests more strict

- tests/lib/rules/comma-style.js
- #2793
---
This PR converts all error assertions for `comma-style` to include both error message and full location checks.
> test(comma-style): make tests more strict

- tests/lib/rules/component-name-in-template-casing.js
- #2793
---
This PR converts all error assertions for `component-name-in-template-casing` to include both error message and full location checks.
> test(component-name-in-template-casing): make tests more strict

- tests/lib/rules/define-emits-declaration.js
- #2793
---
This PR converts all error assertions for `define-emits-declaration` to include both error message and full location checks.
> test(define-emits-declaration): make tests more strict

- tests/lib/rules/define-macros-order.js
- #2793
---
This PR converts all error assertions for `define-macros-order` to include both error message and full location checks.
> test(define-macros-order): make tests more strict

- tests/lib/rules/dot-location.js
- #2793
---
This PR converts all error assertions for `dot-location` to include both error message and full location checks.
> test(dot-location): make tests more strict

- tests/lib/rules/dot-notation.js
- #2793
---
This PR converts all error assertions for `dot-notation` to include both error message and full location checks.
> test(dot-notation): make tests more strict

- tests/lib/rules/enforce-style-attribute.js
- #2793
---
This PR converts all error assertions for `enforce-style-attribute` to include both error message and full location checks.
> test(enforce-style-attribute): make tests more strict

- tests/lib/rules/eqeqeq.js
- #2793
---
This PR converts all error assertions for `eqeqeq` to include both error message and full location checks.
> test(eqeqeq): make tests more strict

- tests/lib/rules/first-attribute-linebreak.js
- #2793
---
This PR converts all error assertions for `first-attribute-linebreak` to include both error message and full location checks.
> test(first-attribute-linebreak): make tests more strict

- tests/lib/rules/html-button-has-type.js
- #2793
---
This PR converts all error assertions for `html-button-has-type` to include both error message and full location checks.
> test(html-button-has-type): make tests more strict

- docs/rules/match-component-import-name.md
Fix typo: change identifer to identifier in [the match-component-import-name rule documentation](https://eslint.vuejs.org/rules/match-component-import-name.html#rule-details).
- ~~Fix typo in match-component-import-name rule documentation~~
- ~~Change "identifer" to correct spelling "identifier" in rule description~~
> docs: fix typo 'identifer' to 'identifier'

- tests/lib/rules/mustache-interpolation-spacing.js
- #2793
---
This PR converts all error assertions for `mustache-interpolation-spacing` to include both error message and full location checks.
> test(mustache-interpolation-spacing): make tests more strict

- tests/lib/rules/multiline-ternary.js
- #2793
---
This PR converts all error assertions for `multiline-ternary` to include both error message and full location checks.
> test(multiline-ternary): make tests more strict

- tests/lib/rules/multi-word-component-names.js
- #2793
---
This PR converts all error assertions for `multi-word-component-names` to include both error message and full location checks.
> test(multi-word-component-names): make tests more strict

- tests/lib/rules/max-template-depth.js
- #2793
---
This PR converts all error assertions for `max-template-depth` to include both error message and full location checks.
> test(max-template-depth): make tests more strict

- tests/lib/rules/max-props.js
- #2793
---
This PR converts all error assertions for `max-props` to include both error message and full location checks.
> test(max-props): make tests more strict

- tests/lib/rules/max-attributes-per-line.js
- #2793
---
This PR converts all error assertions for `max-attributes-per-line` to include both error message and full location checks.
> test(max-attributes-per-line): make tests more strict

- tests/lib/rules/match-component-import-name.js
- #2793
---
This PR converts all error assertions for `match-component-import-name` to include both error message and full location checks.
> test(match-component-import-name): make tests more strict

- tests/lib/rules/match-component-file-name.js
- #2793
---
This PR converts all error assertions for `match-component-file-name` to include both error message and full location checks.
> test(match-component-file-name): make tests more strict

- tests/lib/rules/html-self-closing.js
- #2793
---
This PR converts all error assertions for `html-self-closing` to include both error message and full location checks.
> test(html-self-closing): make tests more strict

- tests/lib/rules/html-quotes.js
- #2793
---
This PR converts all error assertions for `html-quotes` to include both error message and full location checks.
> test(html-quotes): make tests more strict

- tests/lib/rules/html-comment-content-newline.js
- #2793
---
This PR converts all error assertions for `html-comment-content-newline` to include both error message and full location checks.
> test(html-comment-content-newline): make tests more strict

- tests/lib/rules/html-comment-content-spacing.js
- #2793
---
This PR converts all error assertions for `html-comment-content-spacing` to include both error message and full location checks.
> test(html-comment-content-spacing): make tests more strict

- tests/lib/rules/html-end-tags.js
- #2793
---
This PR converts all error assertions for `html-end-tags` to include both error message and full location checks.
> test(html-end-tags): make tests more strict

- tests/lib/rules/html-indent.js
- #2793
---
This PR converts all error assertions for `html-indent` to include both error message and full location checks.
> test(html-indent): make tests more strict

- tests/lib/rules/no-boolean-default.js
- #2793
---
This PR converts all error assertions for `no-boolean-default` to include both error message and full location checks.
> test(no-boolean-default): make tests more strict

- tests/lib/rules/no-child-content.js
- #2793
---
This PR converts all error assertions for `no-child-content` to include both error message and full location checks.
> test(no-child-content): make tests more strict

- tests/lib/rules/no-console.js
- #2793
---
This PR converts all error assertions for `no-console` to include both error message and full location checks.
> test(no-console): make tests more strict

- tests/lib/rules/no-async-in-computed-properties.js
- #2793
---
This PR converts all error assertions for `no-async-in-computed-properties` to include both error message and full location checks.
> test(no-async-in-computed-properties): make tests more strict

- tests/lib/rules/no-deprecated-destroyed-lifecycle.js
- #2793
---
This PR converts all error assertions for `no-deprecated-destroyed-lifecycle` to include both error message and full location checks.
> test(no-deprecated-destroyed-lifecycle): make tests more strict

- tests/lib/rules/no-deprecated-delete-set.js
- #2793
---
This PR converts all error assertions for `no-deprecated-delete-set` to include both error message and full location checks.
> test(no-deprecated-delete-set): make tests more strict

- tests/lib/rules/no-deprecated-v-bind-sync.js
- #2793
---
This PR converts all error assertions for `no-deprecated-v-bind-sync` to include both error message and full location checks.
> test(no-deprecated-v-bind-sync): make tests more strict

- tests/lib/rules/no-deprecated-events-api.js
- #2793
---
This PR converts all error assertions for `no-deprecated-events-api` to include both error message and full location checks.
> test(no-deprecated-events-api): make tests more strict

- tests/lib/rules/no-deprecated-dollar-listeners-api.js
- #2793
---
This PR converts all error assertions for `no-deprecated-dollar-listeners-api` to include both error message and full location checks.
> test(no-deprecated-dollar-listeners-api): make tests more strict

- tests/lib/rules/no-deprecated-scope-attribute.js
- #2793
---
This PR converts all error assertions for `no-deprecated-scope-attribute` to include both error message and full location checks.
> test(no-deprecated-scope-attribute): make tests more strict

- tests/lib/rules/no-deprecated-inline-template.js
- #2793
---
This PR converts all error assertions for `no-deprecated-inline-template` to include both error message and full location checks.
> test(no-deprecated-inline-template): make tests more strict

- tests/lib/rules/no-deprecated-html-element-is.js
- #2793
---
This PR converts all error assertions for `no-deprecated-html-element-is` to include both error message and full location checks.
> test(no-deprecated-html-element-is): make tests more strict

- tests/lib/rules/func-call-spacing.js
- #2793
---
This PR converts all error assertions for `func-call-spacing` to include both error message and full location checks.
> test(func-call-spacing): remove obsolete compatibility code

- tests/lib/rules/no-deprecated-v-on-number-modifiers.js
- #2793
---
This PR converts all error assertions for `no-deprecated-v-on-number-modifiers` to include both error message and full location checks.
> test(no-deprecated-v-on-number-modifiers): make tests more strict

- tests/lib/rules/no-deprecated-vue-config-keycodes.js
- #2793
---
This PR converts all error assertions for `no-deprecated-vue-config-keycodes` to include both error message and full location checks.
> test(no-deprecated-vue-config-keycodes): make tests more strict

- tests/lib/rules/no-duplicate-attributes.js
- #2793
---
This PR converts all error assertions for `no-duplicate-attributes` to include both error message and full location checks.
> test(no-duplicate-attributes): make tests more strict

- .changeset/great-ravens-happen.md
- .github/workflows/CI.yml
- package.json
- tests/lib/rules/comma-style.js
- tests/lib/rules/func-call-spacing.js
- tests/test-utils/eslint-stylistic.js
Follow-up to https://github.com/vuejs/eslint-plugin-vue/pull/2830#discussion_r2231692191.
@ST-DDT It would be great if you could have a look at this :slightly_smiling_face:
> Test support for multiple versions of ESLint Stylistic

- tests/lib/rules/no-ref-as-operand.js
- #2793
---
This PR converts all error assertions for `no-ref-as-operand` to include both error message and full location checks.
> test(no-ref-as-operand): make tests more strict

- tests/lib/rules/no-mutating-props.js
- #2793
---
This PR converts all error assertions for `no-mutating-props` to include both error message and full location checks.
> test(no-mutating-props): make tests more strict

- tests/lib/rules/no-parsing-error.js
- #2793
---
This PR converts all error assertions for `no-parsing-error` to include both error message and full location checks.
> test(no-parsing-error): make tests more strict

- tests/lib/rules/no-side-effects-in-computed-properties.js
- #2793
---
This PR converts all error assertions for `no-side-effects-in-computed-properties` to include both error message and full location checks.
> test(no-side-effects-in-computed-properties): make tests more strict

- tests/lib/rules/no-multiple-template-root.js
- #2793
---
This PR converts all error assertions for `no-multiple-template-root` to include both error message and full location checks.
> test(no-multiple-template-root): make tests more strict

- tests/lib/rules/no-multiple-slot-args.js
- #2793
---
This PR converts all error assertions for `no-multiple-slot-args` to include both error message and full location checks.
> test(no-multiple-slot-args): make tests more strict

- tests/lib/rules/no-multiple-objects-in-class.js
- #2793
---
This PR converts all error assertions for `no-multiple-objects-in-class` to include both error message and full location checks.
> test(no-multiple-objects-in-class): make tests more strict

- tests/lib/rules/no-import-compiler-macros.js
- #2793
---
This PR converts all error assertions for `no-import-compiler-macros` to include both error message and full location checks.
> test(no-import-compiler-macros): make tests more strict

- tests/lib/rules/no-dupe-v-else-if.js
- #2793
---
This PR converts all error assertions for `no-dupe-v-else-if` to include both error message and full location checks.
> test(no-dupe-v-else-if): make tests more strict

- tests/lib/rules/no-dupe-keys.js
- #2793
---
This PR converts all error assertions for `no-dupe-keys` to include both error message and full location checks.
> test(no-dupe-keys): make tests more strict

- tests/lib/rules/no-expose-after-await.js
- #2793
---
This PR converts all error assertions for `no-expose-after-await` to include both error message and full location checks.
> test(no-expose-after-await): make tests more strict

- tests/lib/rules/no-empty-pattern.js
- #2793
---
This PR converts all error assertions for `no-empty-pattern` to include both error message and full location checks.
> test(no-empty-pattern): make tests more strict

- tests/lib/rules/no-empty-component-block.js
- #2793
---
This PR converts all error assertions for `no-empty-component-block` to include both error message and full location checks.
> test(no-empty-component-block): make tests more strict

- tests/lib/rules/no-duplicate-attr-inheritance.js
- #2793
---
This PR converts all error assertions for `no-duplicate-attr-inheritance` to include both error message and full location checks.
> test(no-duplicate-attr-inheritance): make tests more strict

- lib/utils/index.js
Since our [`package.json`](https://github.com/vuejs/eslint-plugin-vue/blob/1d59e53b2d4b1a9eec02844f96397e34e1c11951/package.json#L58) explicitly defines the Node version requirement, I think this polyfill is now redundant and can be safely deleted without side effects.
> fix: remove useless polyfill

- .changeset/rude-heads-serve.md
- docs/rules/component-name-in-template-casing.md
- lib/rules/component-name-in-template-casing.js
- tests/lib/rules/component-name-in-template-casing.js
> feat(component-name-in-template-casing): `global` option support regex

- tests/lib/rules/require-typed-ref.js
found here:
https://github.com/oxc-project/oxc/pull/13857#discussion_r2355378236
> test(required-typed-ref): remove invalid `}` outside `<script>`
